### ISSUE TITLE
US can't load 2GB assets?

### ISSUE THREAD

**Issue by alonezhby** [Perfare/UnityStudio#10]
I use US(64 bit) open a 2GB assets file, it display "Building asset list from file sharedassets1.assets", after a whole night there is no any progress... I checked cpu usage is 0%, memory only used 300MB.

But UABE can open this file.

Would like to check it?

Thanks.

**Comment by Perfare** [comment]
I think I'll check if you upload it...

**Comment by killerrotoz** [comment]
I am having the same problem, the latest version doesn't open 2GB assets files.

I get the message:

Non-negative number required.
Parameter name: value.

It works fine with the other ones tough, the max size i've tested was 600,000 kb

Here's the file i'm trying to load, its from a game called master of orion

https://www.dropbox.com/s/5pebo5mwfnqpfad/resources.assets?dl=0

**Comment by Perfare** [comment]
@killerrotoz Thank you for uploading file
I fixed this issue in commit 86e30c5dc0bd61c1afc4024976b4950cad345a75
