### ISSUE TITLE
Export All 3D Objects (Split) Not Working.

### ISSUE THREAD

**Issue by OffensiveLemon** [Perfare/UnityStudio#100]
When I try to export Besiege's model data by hitting "Export" -> "All 3D objects (Split)," the program crashes, regardless of how much stuff I have in the hierarchy.  For example:
![image](https://user-images.githubusercontent.com/31805871/30243239-76669474-9573-11e7-9389-12ca387436be.png)
![image](https://user-images.githubusercontent.com/31805871/30243243-8ab070b2-9573-11e7-86d5-90d61cce4e2d.png)
![image](https://user-images.githubusercontent.com/31805871/30243245-a7ef79a2-9573-11e7-88e9-023162fd72c4.png)
![image](https://user-images.githubusercontent.com/31805871/30243248-b3d862d8-9573-11e7-96a7-71302f59c020.png)
![image](https://user-images.githubusercontent.com/31805871/30243253-c59bd45a-9573-11e7-9bcf-56225e514d53.png)
The same thing happens when I export all assets, but that's probably because there are a LOT of assets.

**Comment by Perfare** [comment]
With your description, you not installed all the necessary software.
Also, you have to upload files to me so I can test and fix them

**Comment by OffensiveLemon** [comment]
Well, it failed with anything I put in, but here you go...
https://www.mediafire.com/file/k06etc893c43no4/sharedassets5.assets
At least, this is one of them.  There are actually a number of files that I'm trying to dump, but keep in mind that I did try extracting one at a time (with Split.  The others work fine...).  So, what exactly am I supposed to install?

**Comment by Perfare** [comment]
You need to put "sharedassets5.resource" and  "sharedassets5.assets.resS" in the same folder to make UnityStudio work properly.
Also, there is a bug that If these files are missing, UnityStudio will crashes when export.

**Comment by OffensiveLemon** [comment]
I imported all three sharedassets5 files, and it's still not working.  The other export methods work, but... All (Split) is far more convenient...  I don't know what I'm supposed to do.

**Comment by Perfare** [comment]
can you upload "sharedassets5.resource" and "sharedassets5.assets.resS" files to me?

**Comment by OffensiveLemon** [comment]
https://www.mediafire.com/file/32bg2lw79mkpnzp/sharedassets5.assets.resS
https://www.mediafire.com/file/x745xb78gcjx2f4/sharedassets5.resource

**Comment by Perfare** [comment]
I tested the file Export All 3D Objects (Split) work fine.
But I think I've found the reason. Did you choose a folder that didn't exist?

**Comment by OffensiveLemon** [comment]
I attempted to create a new one by typing a nonexistent name.  And I can't seem to save to an empty folder that already exists, it just leads me into the folder when I type in the name and hit Save.  Do I need to type in "sharedassets5?"

**Comment by Perfare** [comment]
Double click the empty folder, and then click the Save button

**Comment by OffensiveLemon** [comment]
![image](https://user-images.githubusercontent.com/31805871/31041094-e4a7b6e4-a55d-11e7-8599-c4f0c7aac22b.png)
Holy crap.

**Comment by Stellarspace** [comment]
@Perfare Why can't you program it to give an error message instead of crashing?
