### ISSUE TITLE
installing on linux?

### ISSUE THREAD

**Issue by PaperVb64** [Perfare/UnityStudio#1000]
can you even do that?

**Comment by silverhikari** [comment]
tried with wine 7.10 made a prefix and install the windows version of the dotnet 6.05 desktop runtime from the website but when running it will still ask to install dotnet 6.05 and click yes will cause the program to exit

**Comment by PaperVb64** [comment]
Actually got it working not to long ago (if you count 5 months-last year as not too long ago lol). turns out i was missing some repos. Closing this issue, as it kinda makesno sense to have it up anymore.
