### ISSUE TITLE
Unable to load shader in Slayers X Demo

### ISSUE THREAD

**Issue by LukeWarnut** [Perfare/UnityStudio#1002]
[Steam Page](https://store.steampowered.com/app/1931020/Slayers_X_Terminal_Aftermath_Vengance_of_the_Slayer/)
AssetStudioGUI v0.16.40

![image](https://user-images.githubusercontent.com/65521430/173443743-9cab8a00-3ee2-4fd8-b6f6-8f4f397a62cc.png)

**Comment by Perfare** [comment]
Delete the `unity default resources` file and reload it
