### ISSUE TITLE
Error while reading bundle file Lz4 decompression error

### ISSUE THREAD

**Issue by Hinkiii** [Perfare/UnityStudio#1003]
![image](https://user-images.githubusercontent.com/1348768/173576478-18f16a1e-cd64-4e1c-9023-5a4241c6e195.png)

With the game Agent 64 Demo from Steam [here](https://store.steampowered.com/app/1574480/Agent_64_Spies_Never_Die/)

**Comment by buzhishishi** [comment]
I have the same problem on my end

**Comment by ShenKang4181** [comment]
I have the same problem on my end

**Comment by maha-atman** [comment]
Recently I also encounter similar issue with asset with newer version of asset bundle file

for example asset bundle file with v2019.4.29f1 can be opened just fine but the same asset with v2020.3.33f1 cant be opened

**Comment by Perfare** [comment]
Fixed.
