### ISSUE TITLE
Error while reading assets file

### ISSUE THREAD

**Issue by Carpethop** [Perfare/UnityStudio#1007]
Hi, I'm trying to extract content from  iOS game called "Warped Kart Racers",  it wont open any of bundle file and only gives  me same error and that's it, it seems like all bundle files encrypted or something else.
![60c246403fec346bab75a9946bf572c7](https://user-images.githubusercontent.com/11527788/174448208-fa88fd00-f43b-43cb-a7a8-e0fa55ae0af8.png)

**Comment by gef12** [comment]
open the file with a hex editor(HxD) and see the contents from the beginning

**Comment by Carpethop** [comment]
> 

Here what's inside 
![image](https://user-images.githubusercontent.com/11527788/174460237-c1037c61-44a1-4d63-8b25-0d2cb97b6c43.png)

**Comment by gef12** [comment]
apparently it is not encrypted, it may be incompatibility with the program, if possible send the file so we can see if it is encrypted or not

**Comment by Carpethop** [comment]
Here's the file [common_3ae18f21bef82222ac1c78cfe4bd3db5.zip](https://github.com/Perfare/AssetStudio/files/8942832/common_3ae18f21bef82222ac1c78cfe4bd3db5.zip)

**Comment by gef12** [comment]
use 
![image](https://user-images.githubusercontent.com/22777207/174668042-82d18ea2-f915-47ed-bd05-419a7f4777f8.png)

AssetBundleExtractor_3.0beta1_64bit, error in version.

**Comment by gef12** [comment]
https://github.com/SeriousCache/UABE/releases

**Comment by Carpethop** [comment]
I tried to load decompressed bundle file in AssetStudio, but it still won't load ![image](https://user-images.githubusercontent.com/11527788/174671193-a58bfab6-6c6f-4a75-bdeb-ea0670b1e26b.png)

**Comment by gef12** [comment]
version UnityFS 5.x.x 2020.3.29f1 not suported or bug, use https://github.com/SeriousCache/UABE/releases, to open and export the data

**Comment by Carpethop** [comment]
I’ve already tried exporting the data, it gives me bunch of .dat files that won’t open in AssetStudio or Noesis even if I rename to FBX or other file formats that I think  it was inside before extraction from bundle file.

**Comment by MisterPrawn** [comment]
You'll want to find the Unity version of that file in the hex editor (in this case 2020.3.29f1) and in Asset Studio, go under options, then Specify Unity version, then type/paste in the unity version in that box. Load the files again, and you should be good to go.

**Comment by Carpethop** [comment]
> You'll want to find the Unity version of that file in the hex editor (in this case 2020.3.29f1) and in Asset Studio, go under options, then Specify Unity version, then type/paste in the unity version in that box. Load the files again, and you should be good to go.

Oh, it actually working now, thank you so much for your tip about version 🙏🏻
