### ISSUE TITLE
cannot extract audioClip

### ISSUE THREAD

**Issue by Zbuffers** [Perfare/UnityStudio#102]
Hi, Really nice tool ;)

I am trying to get audioclips from a 'sharedassets0.assets'. (Unity v5.0xx)
the file is read fine.
when trying to preview an audio clip, I get a messagebox "cannot find the file'...

I tried to understand what was goind on:

it should look for an external file named something like '00d5f7caed994a04c9d48e6b5370b284.resource' that contains the FSB data, and it cannot find the file.

I nailed the issue down to the 'AudioClip.cs' in the constructor.
more precisely, the line 'm_Source = a_Stream.ReadAlignedString(a_Stream.ReadInt32());
returns an empty string (instead of  the expected '00d5f7caed994a04c9d48e6b5370b284.resource'. (around line 90 or something)
the obvious for me is an incorrect length of the string is should look for. while messing around, I found that if I strip out the previous reads i can get the correct filename:
replacing
                    m_PreloadAudioData = a_Stream.ReadBoolean();
                    m_LoadInBackground = a_Stream.ReadBoolean();
                    m_Legacy3D = a_Stream.ReadBoolean();
                    a_Stream.Position += 1;
                    m_3D = m_Legacy3D;
                    m_Source = a_Stream.ReadAlignedString(a_Stream.ReadInt32());
with 
                    m_PreloadAudioData = true;
                    m_LoadInBackground = true; 
                    m_Legacy3D = true; 
                    m_3D = m_Legacy3D;
                    m_Source = a_Stream.ReadStringToNull();
gets the correct file name 
but now i Get an FMOD error! ERR_INVALID_PARAM...
note: the 005f4dcbaf84349488e0729552b1bb3f.resource corresponds to the 'xpOrbCollectA' entry in the asset list.

Edit, the data is a StreamedResource

I am unsure of how to resolve this...
any ideas ?

Kind regards

[Data.zip](https://github.com/Perfare/UnityStudio/files/1346521/Data.zip)

**Comment by Stellarspace** [comment]
Are you using the latest build?

**Comment by Perfare** [comment]
This file is generated by Unity 5.0 beta version, the format is different from any final version, UnityStudio unable to read the file correctly.
