### ISSUE TITLE
Exits on start with code 255

### ISSUE THREAD

**Issue by khang06** [Perfare/UnityStudio#105]
When I try running this fork of Unity Studio (doesn't matter if it's from Releases or if i built it myself), it exits instantly with exit code 255. 
![image](https://user-images.githubusercontent.com/11239786/31627406-39e3e806-b27b-11e7-87e7-aade8bef705c.png)
The original v0.5.1b3 of Unity Studio from 2015 works fine. I have also verified that I have the necessary redistributables installed for the right architecture.

Edit: For some reason, the x86 version runs fine.

**Comment by Perfare** [comment]
According to your description, I can't get any useful information, but it's probably a problem with your computer.
