### ISSUE TITLE
Skip All Errors Button

### ISSUE THREAD

**Issue by rayman3003** [Perfare/UnityStudio#1057]
Sometimes when AssetStudio is reading some files, it shows so many similar errors, saying that "unable to load objects".

Usually, these kind of errors, repeat itself for so many times (maybe 40-50 times or more), & I must click on "OK" for 40-50 times, to load the files completely at end.

I think if there is a "Skip All Errors" Button available in the error windows, then AssetStudio can skip all errors automatically & fasten the loading time. I mean something like this:

![01](https://user-images.githubusercontent.com/17022701/194725732-43046fdd-25df-48f8-a5ec-f5e43c231e66.jpg)

Could u please add this simple button to AssetStudio?

**Comment by MisakaCirno** [comment]
Menu-Debug-Show error message

**Comment by rayman3003** [comment]
> Menu-Debug-Show error message

Oh, OK. I didn't know about it. Thank u.

I will close the issue now.
