### ISSUE TITLE
"Show original file" not work on win XP?

### ISSUE THREAD

**Issue by ngovandang** [Perfare/UnityStudio#108]
I have did right click on asset then choose Show Original File, but nothing show up

**Comment by mhoangvslev** [comment]
Windows XP is not a real deal anymore. I suggest you to upgrade your windows.

**Comment by ngovandang** [comment]
Yeah yeah
My own PC is win 7 x64
But company computer is win XP
I dont have much time per day. So abuse all the time in company to work. Ok?
So dont blah blah blah about upgrading window.
There is a build for win 32bit, why not fix it?

**Comment by Perfare** [comment]
I don't have a win XP computer, don't know why can't work under XP, also I don't intend to fix any problems under XP.
