### ISSUE TITLE
Multiple UnityFS Bundles in an archive

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/UnityStudio#111]
Would it be possible to make it so UnityStudio can detect multiple UnityFS bundles in a single file, and decompress, export, or load them all https://mega.nz/#!48xhTB6B!HtepshL_KRZf8oLh50Rkkm9ZXcZKurEkuYx1rjwz7tE the first UnityFS headers starts at 0x3B0, which would obviously be different for other files.

**Comment by Perfare** [comment]
Because this is obviously not generated by unity3d, UnityStudio will not support it.
