### ISSUE TITLE
Cannot extract some version of assetbundle.

### ISSUE THREAD

**Issue by 1151505992** [Perfare/UnityStudio#113]
Cannot extract some version of assetbundle. 7 can be extracted without knowing why the 8 version 7 version can import and import can be extracted from the AssetBundle file will be displayed (no children) I don't know why. I'm a very strange game version of.7.0 when only part of the original document or import model. After the introduction of some models can be read but extraction when the error of flash back or only extract the 2KB file. But I am sure I installed the Framework 4 (.NET
Microsoft Visual C++ 2013 Redistributable
Microsoft Visual C++ 2015 Redistributable)
Before I extracted another game with 7 and 8. He should be the engine of Unity 5, but still unable to read T-T
Seek help！ T-T

**Comment by 1151505992** [comment]
http://pan.baidu.com/s/1qYC34qo        This is the link to the original file. Can you help me?

**Comment by Perfare** [comment]
http://blog.sina.com.cn/s/blog_b4721dbb0102wykj.html
