### ISSUE TITLE
x64 Bit version broken

### ISSUE THREAD

**Issue by erherhh4herh** [Perfare/UnityStudio#115]
When launching x64 bit version with debugging, i get this error: https://i.imgur.com/WFe4fyC.png
Launching x86 works fine. Please fix!

EDIT: Using commit 7ddbf3ce3e9b4e71f7645112054bd1f314d62e3a

**Comment by jeanfbrito** [comment]
+1

**Comment by Perfare** [comment]
I think it's opentk problem, but I don't have any solutions
