### ISSUE TITLE
UnityStudio not fully reading assets?

### ISSUE THREAD

**Issue by NWPlayer123** [Perfare/UnityStudio#118]
I'm trying to use this to browse Animal Crossing: Pocket Camp since it's the only thing that supports the newest versions of Unity (this is using 5.6.0p4.AndroidCrashPreview/Unity-2.1.4-73268f8), and apparently it doesn't read the text correctly, it sees the MonoBehaviour AssetBundleIndex_Android
```
[8]
CdAssetBundleInfo data
	string _assetBundleName = "3c1c9e59/f3c14602/38cb13fd/57123fb8"
	string _group = "tut001"
	string _cksum = "92aa56f6dd6c70ac4bfa59316b0043fb"
	int _size = 397741
	string _variant = ""
	vector _otherVariantList
		Array Array
		int size = 0
	int _encryptionMode = 1
	UInt8 _isStatic = 0
	vector _entryPathList
		Array Array
		int size = 6
			[0]
			string data = "cmps/MSData/US_English/10_System.bytes"
			[1]
			string data = "cmps/MSData/US_English/20_Message.bytes"
			[2]
			string data = "cmps/MSData/US_English/30_UI.bytes"
			[3]
			string data = "cmps/MSData/US_English/40_BuiltIn.bytes"
			[4]
			string data = "cmps/MSData/US_English/50_Operation.bytes"
			[5]
			string data = "cmps/MSData/US_English/RI.bytes"
	vector _dependAssetBundleNameList
		Array Array
		int size = 0
```
but I can't access the data there (this is in an in-app data download it puts in /sdcard/Android/data/com.nintendo.zaca/files/AssetBundle, so it's /AssetBundle/3c1c9e59/f3c14602/38cb13fd/57123fb8.unity3d)
[57123fb8.zip](https://github.com/Perfare/UnityStudio/files/1492006/57123fb8.zip)
I'd parse it manually but it's using some EncryptionMode that I assume you're able to support, any help would be appreciated

**Comment by Perfare** [comment]
I'm sorry I can't do anything for you, about the encryption you should go to some hack forum for help
