### ISSUE TITLE
Ability to set the minimum duration of a exported FSB that is loopable.

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/UnityStudio#119]
Some AudioClips are loopable, so the intro plays, and a specific part of the song loops if you have the loop button enabled, It would be handy if we can export these and specify a duration the song has to be greater than before finishing the audio.

**Comment by Perfare** [comment]
Sorry, I don't quite understand what you're talking about. I need a file to research

**Comment by MichaelPriebe** [comment]
[Looping FSB.zip](https://github.com/Perfare/UnityStudio/files/1496852/Looping.FSB.zip)

Here's an example if you look at fnfr_complete_lr.mt.32.cn4 it will play a little intro, and if you have the looping button selected it will skip so it loops seamlessly after its finished. This is because FSB's have looping data which is destroyed when its converted to wav. It would be cool to have a way to extend the exported wav to a selected duration using that looping section, or just entirely export that looping section to be looped manually with Audacity or something.

**Comment by Perfare** [comment]
You should use audio editing software instead of letting UnityStudio do it

**Comment by MichaelPriebe** [comment]
But currently there's no way to tell where this looping section is without just watching it as it loops and trying to recreate it in an audio editing software.

**Comment by Perfare** [comment]
Well, using FMOD.Sound.getLoopPoints() can get loop information, but I don't have any good idea to export this information

**Comment by MichaelPriebe** [comment]
https://github.com/kode54/vgmstream/tree/master/test I found this that can export fsb with optional loop amounts. Maybe take a look at the code? Doesn't use FMOD though I believe.

**Comment by Perfare** [comment]
I already know how to do it, recently I'll add support it

**Comment by Perfare** [comment]
I'm sorry to reply to you now, I have decided not to add this function feature.
You can choose not to convert into WAV, then use other tools to deal with FSB
