### ISSUE TITLE
enhancement: mouseWheel zoom

### ISSUE THREAD

**Issue by Zbuffers** [Perfare/UnityStudio#121]
Hi,
small enhancement:
adjust zoom with mousewheel:
add the handler to the mainform in the form constructor
`MouseWheel += Form_MouseWheel;`

        // mousewheel handler
        private void Form_MouseWheel(object sender, MouseEventArgs e)
        {
            if (glControl1.Visible)
            {
                viewMatrixData *= Matrix4.CreateScale(1 + e.Delta/1000f);
                glControl1.Invalidate();
            }
        }

next: rotate viewport with mouse ;)

**Comment by erherhh4herh** [comment]
Should probably make a pull request.
