### ISSUE TITLE
Sprites extracting as dat

### ISSUE THREAD

**Issue by greenhouse95** [Perfare/UnityStudio#123]
I'm trying to extract sprites but they extract as .DAT.
I guess that it's because they are encrypted or something like that. Is there any way to solve it?

**Comment by MichaelPriebe** [comment]
Sprites are cropped versions of Texture2D, the image you're looking fore is located somewhere in a Texture2D.

**Comment by greenhouse95** [comment]
Yes, makes sense. I thought I could get each sprite as an image instead of a PNG/TGA with all of them together. Thanks.

**Comment by MichaelPriebe** [comment]
It seems very easy to crop the atlas image that a sprite refers to, so not sure why its not supported, unless sprites don't give all the information we need. @Perfare you have any ideas?

**Comment by greenhouse95** [comment]
That would just be perfect, and would save me so many time.
