### ISSUE TITLE
Solution Build Errors

### ISSUE THREAD

**Issue by iantrudell** [Perfare/UnityStudio#124]
When attempting to build #40153f6, I'm getting the following errors:

![unity-studio-error1](https://user-images.githubusercontent.com/33202657/33753840-810f3220-dbb7-11e7-93d1-652c3ebc6780.png)
![unity-studio-error2](https://user-images.githubusercontent.com/33202657/33753841-811cf716-dbb7-11e7-9121-b511e48b4be3.png)

I was able to successfully build a few commits back, but this error cropped up recently. Something to do with EndianBinaryReader?

Any help would be much appreciated!

**Comment by Stellarspace** [comment]
Yeah, I suggest using 2017 and not 2015.
