### ISSUE TITLE
disunity 中的 "structdb.dat"

### ISSUE THREAD

**Issue by ye1088** [Perfare/UnityStudio#128]
请问下你对 disunity 中的 "structdb.dat" 这个文件有研究么?之前一直用的是disunity 来提取unity游戏的资源的,发现他提取 unity游戏是根据这个文件为模板来提取的,当unity版本更新后,之后更新下这个文件,就能立马匹配新版本的unity游戏,就是不知道他们为什么不更新了....

**Comment by Perfare** [comment]
没有哦。disunity两年前就已经停止更新了，我觉得你以其去研究一个早就不更新的软件，为什么不使用UABE呢

**Comment by ye1088** [comment]
@Perfare  只怪当初上了他的船啊.....o(╥﹏╥)o,不过还是谢谢你~~
