### ISSUE TITLE
3d models in the Scene Hierarchy list are now listed as "GameObject #(Numbers)"

### ISSUE THREAD

**Issue by Yuuyatails** [Perfare/UnityStudio#13]
Sorry for interrupting, but It appears that the change to the Unity Classes/GameObject.cs in commit fbfdb789f5b9c140d25be4094f772354c2ee05e1 causes most 3d models (except bones, meshes and textures) in the Scene Hierarchy list to be listed as "GameObject #(Numbers)".

Here's the prove of this bug (note the listing in the Scene Hierarchy list):
-Before commit
![image](https://cloud.githubusercontent.com/assets/10596039/21964500/207d007a-db88-11e6-85c0-0fad04e5f5ae.png)
-After commit
![image](https://cloud.githubusercontent.com/assets/10596039/21964506/30dd9e8e-db88-11e6-955b-99821a05d6da.png)

It can be solved by removing the line `a_Stream.Position -= 4;` in the GameObject.cs file, but I don't know if it will impacts other part of Unity Studio's functions.

**Comment by Perfare** [comment]
I'm writing code to make Unity Studio support Unity 5.5 now.
I might accidentally submit the test code.
This will be resolved before release

**Comment by Yuuyatails** [comment]
This issue has been fixed with the commit 08bf84146bf2b818ae93377777ad701a6cef42d8.
