### ISSUE TITLE
无法加载 DLL“PVRTexLibWrapper.dll”

### ISSUE THREAD

**Issue by helloxiaohui** [Perfare/UnityStudio#132]
打开是可以，导出会报如下错误：
System.DllNotFoundException: 无法加载 DLL“PVRTexLibWrapper.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 Unity_Studio.UnityStudioForm.DecompressPVR(Byte[] buffer, IntPtr bmp, Int32 len)
   在 Unity_Studio.UnityStudioForm.PreviewAsset(AssetPreloadData asset)
   在 Unity_Studio.UnityStudioForm.selectAsset(Object sender, ListViewItemSelectionChangedEventArgs e)
   在 System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   在 System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   在 System.Windows.Forms.ListView.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

我该怎么解决这个问题呢（win10的64专业版运行环境）

**Comment by Perfare** [comment]
https://github.com/Perfare/UnityStudio/blob/7e6ef31875da490ff8eb51f6607efa8630a22279/README.md#L28-L33
https://github.com/Perfare/UnityStudio/issues?q=is%3Aissue+PVRTexLibWrapper+is%3Aclosed
