### ISSUE TITLE
ReCore support

### ISSUE THREAD

**Issue by MARK2580** [Perfare/UnityStudio#134]
Hi, thank you very much for this program, I have long dreamed of getting a character model from the game ReCore, at the moment I can only browse the model but when the model is exported or the textures are viewed, the program crashes. Could you make support? I'm attaching an example of game resources.

Google - https://drive.google.com/open?id=1WJTMXDqyYuzuXXSwo_DnSXdpcVx-FtDk
MEGA (alt) - https://mega.nz/#!sIgBgbCJ!aUmtaOTfN9qJwVWQrLIbKNfnnx2NoTlKJPPM7AxC8I0

**Comment by Perfare** [comment]
This game is made with the Unity 5.4.0 beta version, the format of the beta version is different from the version of final and patch, and any beta version will not be supported.
