### ISSUE TITLE
Hyper Universe Support

### ISSUE THREAD

**Issue by MisterPrawn** [Perfare/UnityStudio#135]
This game called Hyper Universe is Unity Powered, but it seems the main content is stored in this 0000 folder, which I'm currently trying to extract from. Find the game itself here: http://store.steampowered.com/app/591530/Hyper_Universe/

I've provided some samples of the files contained in said folder, for potential support. Thanks!
[Samples.zip](https://github.com/Perfare/UnityStudio/files/1641249/Samples.zip)

**Comment by Perfare** [comment]
In my view, these files have been damaged or encrypted

**Comment by MisterPrawn** [comment]
That's the thing, though. Whenever I try to extract the files, even with AssetsBundleExtractor, they aren't able to. They're more than likely encrypted, so there may or may not be a way to decrypt them, unless there is a way.
