### ISSUE TITLE
Missing Bones in Hierarchy?

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/UnityStudio#141]
The AnimationClips seem to reference bones that aren't displayed in the Hierarchy, Any ideas? or is this the same dumb method Digimon World Next Order uses for the Digimon rigs. https://mega.nz/#!8shCERoT!NWLMcScDXyB2BWQVJId0TpnTHn5EmZkurhT-hksOTpI

**Comment by mafaca** [comment]
I think those animations are meant for different model, not for this one in asset file. U can extract those animations only after separate AnimationClip export is ready.
