### ISSUE TITLE
Can This Export ScriptableObject Assets?

### ISSUE THREAD

**Issue by ceyhuntasci** [Perfare/UnityStudio#143]
Apart from scriptableobject assets, this software seems to be able to export anything. Is it possible to see the .asset files which are instances created from scriptableobjects and see the data inside them?

**Comment by Perfare** [comment]
as far as I know, ScriptableObject is a yaml format text file, you can use a notepad to open it

**Comment by hanoi2233** [comment]
hi Perfare, im facing the same problem, how can i find the yaml format text file you discribe above? thank you so much

**Comment by Perfare** [comment]
@hanoi2233 If you use the following code to create ScriptableObject asset
`MyScriptableObject nameInfoObj = ScriptableObject.CreateInstance<MyScriptableObject>();`
`UnityEditor.AssetDatabase.CreateAsset(nameInfoObj, "Assets/test.asset");`
"test.asset" is a text file, no assets file

**Comment by hanoi2233** [comment]
ok, got it. but in using UnityStudio, how can i get this text file?
in my case, the data is stored in sharedassets0.assets. when using UnityStudio, i can only get the "header" info of ScriptableObject, no data in it. below is an example:

PPtr<GameObject> m_GameObject
	int m_FileID = 12
	int64 m_PathID = 0
UInt8 m_Enabled = 1
PPtr<MonoScript> m_Script
	int m_FileID = 1
	int64 m_PathID = 251
string m_Name = "AchieveDataBase"

**Comment by Perfare** [comment]
@hanoi2233 According to your description, you are referring to MonoBehaviour not ScriptableObject,  
you can try to use UABE to get the information

**Comment by ceyhuntasci** [comment]
@hanoi2233 @Perfare I've tried UABE but no luck. Couldn't find any way extract data.

**Comment by Perfare** [comment]
@ceyhuntasci So where do you want to get data?
If you want to get data from ScriptableObject, you just need to use a notepad to open the file.
If you want to get data from MonoBehaviour, make sure that you are using the latest version of UABE, using Tools-Get script information to get the data

**Comment by romen-h** [comment]
Why did this issue ever get closed?
hanoi2233 is right, this tool only shows some header info, not the actual *content* of the ScriptableObject.
Unless that gameobject it points to is supposed to be the one with the data? UABE can't extract it either so there's no point in going down that hole even if you find the object.

`ScriptableObject` can contain all sorts of data that can't be displayed in text format so I wouldn't expect a properly exported `ScriptableObject` to be useful in anything other than a hex editor. Unless you can somehow partially convert the object to yaml and keep some of its content in an encoded binary format.

**Comment by Perfare** [comment]
@romen-h First of all, ScriptableObject will be stored as MonoBehaviour type when it is saved in the asset.
At the time of this question, AssetStudio does not support reading MonoBehaviour, so only the head is shown.
But if you choose MonoBehaviour assets now, you will be asked to choose the folder where the assembly is located.
https://github.com/Perfare/AssetStudio#export-monobehaviour
The data should be read normally.

**Comment by romen-h** [comment]
> The data should be read normally.

That doesn't seem to be the case when I try to browse "MonoBehaviours" that I know to be ScriptableObjects.
(I am browsing assets from a game for modding purposes)

All of them show an error like this in the status bar and only produce the header information when I dump the asset:

![image](https://user-images.githubusercontent.com/44817261/147369462-cfe613bc-524d-40f6-91ec-947c522bc97c.png)

**Comment by Perfare** [comment]
@romen-h So have you selected the correct assembly folder? Need to ensure that the dll is not encrypted, and if it is il2cpp, please follow the readme operation. https://github.com/Perfare/AssetStudio#export-monobehaviour
In addition, I suggest that you open a new issue. Your issue is just a monobehaviour reading issue and has nothing to do with the current issue.

**Comment by romen-h** [comment]
Please ignore my deleted comment if you saw it already.
Things make a lot more sense when you load the assembly, thank you.

Could you please add a text prompt to actually say "Please locate the folder for the game assembly" because that Open File dialog is confusing when it pops up with no instruction, no expected file type (.dll) in the filter, or any explanation for why it opened at all.  
And second, when you close it there doesn't seem to be a way to get it back without restarting the program.
