### ISSUE TITLE
audioclip 无法预览和导出

### ISSUE THREAD

**Issue by Wsuika** [Perfare/UnityStudio#144]
audioclip 无法预览 下方提示FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called.
导出的话也有问题
选择转成wav的话就失败, 否则出来的fsb只有几kb~几百kb
文件较大传到了dropbox里
https://www.dropbox.com/s/iyf8zhxgko0rtxr/Data.zip?dl=0

**Comment by Perfare** [comment]
没有任何问题，fsb就是这个大小，你电脑没办法运行FMOD ，你可以尝试用其他工具转成wav
