### ISSUE TITLE
Export meshes which is in the scene and not assets

### ISSUE THREAD

**Issue by vizgl** [Perfare/UnityStudio#145]
Can't export meshes which is not assets, but only linked to MeshFilter in the scene

**Comment by Perfare** [comment]
Sorry, I don't understand what you're talking about. I need more information

**Comment by vizgl** [comment]
Create GameObject, add MeshFilter component and then proceduraly generate mesh and link to the MeshFilter(_meshFilter.sharedMesh = generatedMesh). Now, generated mesh exist only in scene as instance not as asset. At current state, UnityStudio doesn't process this situation. But if we save new mesh in the assets, then we will see it in the UnityStudio and can export

As an example look at video about MeshBaker tool https://youtu.be/AGChQ7lnMOc?t=174

**Comment by Perfare** [comment]
In my view, everything will be packed into an asset file when the game was built.

**Comment by JuGGerNaunT** [comment]
@Perfare He means US don't process procedurally generated mesh, those which generated by code during then game (not during the build process).
@vizgl I dont think anyone would implement this feature in US. This is very specific and useless, because u could still export original asset with US and rebuild baked structure by youself.

**Comment by vizgl** [comment]
Sorry for my english.

@JuGGerNaunT no, mesh generated in the editor not in the game. See example video above.
@Perfare yes, your right. Every mesh, which exist only in the scene is packed into file like **level0**. And I want to grab and export this mesh as fbx, but in the current state US is only export meshes which exist as assets in the files like **00c339229ef43484bba77b0caa26eb5b**

**Comment by Perfare** [comment]
@vizgl US can open the assets file regardless of the file name, if you're sure US can't open it, you can upload the file to me, and I'll check it.
