### ISSUE TITLE
Bleach brave soul

### ISSUE THREAD

**Issue by Ryuanime** [Perfare/UnityStudio#146]
Pls i need extract charects is game, pls android extract for unity

**Comment by Ryuanime** [comment]
Hello, I want to help with my feedback.
There is a bleach game for android your program presents files in .byte format, but we can not visualize, is there any forecast so we can extract the models and textures from this game?

**Comment by Perfare** [comment]
First, I only understand your last sentence.
I won't help anyone solve the problem caused by encryption.
