### ISSUE TITLE
Shader Not Working

### ISSUE THREAD

**Issue by ForgedInception** [Perfare/UnityStudio#147]
Any Workaround for this error plz.
When i try to import this shader in unity it shows that error and shader doesn't work.
[Error Image]
![shader error](https://user-images.githubusercontent.com/8958885/35775509-78af021e-09ab-11e8-889b-672d678a98cf.PNG)

[Shader File]
[RS_carpaint_MultiLayerCandyBack.txt](https://github.com/Perfare/UnityStudio/files/1692582/RS_carpaint_MultiLayerCandyBack.txt)

[Source File]
[source file.txt](https://github.com/Perfare/UnityStudio/files/1692583/source.file.txt)

**Comment by Perfare** [comment]
The file just allows you to see the code to help you rewrite it, rather than allowing you to import directly
