### ISSUE TITLE
Сan't export bundles

### ISSUE THREAD

**Issue by kontrq** [Perfare/UnityStudio#148]
In the archive there are 2 bundle files. One can be extracted, and the second one is cant be extracted or decompress. Maybe you could find a way to extract from the second bundle file? Maybe its crypted?
[google drive](https://drive.google.com/open?id=1dpkhYAZOJZMJTrKMeNsT2uoistciggKp)
[virustotal](https://www.virustotal.com/ru/file/a2482e6573b87eca70704b7738bdf8b9c0d5ae42153cc58d7ed38584a84f6e85/analysis/)

**Comment by Nicofisi** [comment]
In the issue you confused the URL display name with the actual URL, clicking it redirects to a non existing page ;)

**Comment by kontrq** [comment]
sorry :)

**Comment by Perfare** [comment]
I think it should be encrypted

**Comment by Nicofisi** [comment]
should be?
