### ISSUE TITLE
Export All 3D-objects issue

### ISSUE THREAD

**Issue by PiraSV** [Perfare/UnityStudio#15]
When export all 3D objects in the coordinate values of a comma instead of a point, which causes an error in the model.
When export selected 3D objects all is well.
Screenshot: https://drive.google.com/open?id=0B6B4IT12tcZpZEVxXzBEUGhzMjQ  (left OK, right Error)

**Comment by Perfare** [comment]
export all 3D and export selected 3D use the same code, It can't happen unless you do something

**Comment by Perfare** [comment]
export all 3D and export selected 3D Use the same code, It can't happen unless you do something

**Comment by PiraSV** [comment]
It's strange. I exported with the same settings and this is happening

**Comment by Perfare** [comment]
It's a strange phenomenon and I can't reproduce it on my computer, so I think this is not the problem of UnityStudio

**Comment by PiraSV** [comment]
I open the folder where many assets and export: "All 3D objects (split)"

**Comment by Perfare** [comment]
"All 3D objects (split)" use the same code too, I don't know why it happened and can't solved this strange phenomenon.
