### ISSUE TITLE
can not open this file at 9.0 edition

### ISSUE THREAD

**Issue by moenova** [Perfare/UnityStudio#153]
please take a look at the following file, it cannot be open by the 9.0 edition and previous one

[1992_Li_LOD1_show.zip](https://github.com/Perfare/UnityStudio/files/1742863/1992_Li_LOD1_show.zip)

好吧这是个王者荣耀的模型文件，只能打开人物模型，打不开这个皮肤模型，请问有人知道是怎么回事么？
以前的皮肤模型都是可以打开的

**Comment by Perfare** [comment]
UnityLz4是自定义的格式，相当于“加密过了”
