### ISSUE TITLE
用0.9.0导出的shader 不是unity可用的格式

### ISSUE THREAD

**Issue by dw317748627** [Perfare/UnityStudio#155]
导出的为
tring m_Name = ""
SerializedShader m_ParsedForm
	SerializedProperties m_PropInfo
		vector m_Props
			Array Array
			int size = 7 ...

**Comment by dw317748627** [comment]
5.3.5的还可以解析成可用的 5.5.5就变成这样了

**Comment by Perfare** [comment]
5.5后的shader就是现在这个样子
