### ISSUE TITLE
Jumbled DXTCrunched Output

### ISSUE THREAD

**Issue by dolopodog** [Perfare/UnityStudio#159]
Hello Perfare,

Recently, some crunched png Texture2D assets that I've extracted using UnityStudio have come out jumbled. The game in question used to be compatible with UnityStudio until a recent update.

Here is an example of one of the jumbled assets compared to what it should look like:
Correct: https://i.imgur.com/rkloWfH.png
Jumbled: https://i.imgur.com/ewnp0UU.png

I noticed you're making a few changes to the way crunched files are handled. Is this a recent issue caused by an incompatibility with crunch, or encrypted image assets?

Any feedback would be greatly appreciated.

**Comment by Perfare** [comment]
Unity using new crunch library after 2017.3.
For some reason, I don't upload the library for UnityStudio until release UnityStudio new version

**Comment by dolopodog** [comment]
Thank you for the response, that is reassuring. I will be eagerly awaiting your next release!
