### ISSUE TITLE
why Unity.Studio have no editing function

### ISSUE THREAD

**Issue by dujiaoshu** [Perfare/UnityStudio#161]
hello
why Unity.Studio have no editing function? Can't repalce the files of *.assets?

**Comment by dujiaoshu** [comment]
today i found Unity.Studio.x64.v0.9.0.22 can open a assets
 file,but can't edit it,What if 

it could have a modified function like AssetsBundleExtractor

download url：
http://dropcanvas.com/#5U7e6BmB7u79L3

**Comment by dujiaoshu** [comment]
new download url：
https://pan.baidu.com/s/1YUN0B7cBT_7IerBKdSReJA

**Comment by UlyssesWu** [comment]
That's mainly because US is not ABE. Using ABE solves your issue, so you can close this issue.
If US would support editing one day, that'll be great. But no one had promised that so you shouldn't have expect that either.

**Comment by dujiaoshu** [comment]
Thank you for the reply
But ABE con't open this file

**Comment by Perfare** [comment]
There is no reason why.
You should ask this question in UABE

**Comment by dujiaoshu** [comment]
Sorry, it may be different from the country that leads to a different expression.
What I really mean is, can Unity.Studio increase the replacement function?

**Comment by dujiaoshu** [comment]
And I also asked UABE, but there's no reply at the moment, so thank you first for your many replies.

**Comment by UlyssesWu** [comment]
请原谅我猜你是中国用户，因为这英语水平真是让人头大。
如果你能看懂这行字：你连作者是国人都不知道？

你的想法过于天真了，替换的实现难度是远高于查看、导出的。
当然，以这位作者大佬的功力，想必是能够实现的，但是这所需要的时间和精力，是你未曾想到过的。
与其伸手，不如fork下来自己改。如果你只是想替换其中的一两个/种资源，摸清了格式后未必不能实现。
