### ISSUE TITLE
hi, Please help me to open this bundle file from formacar :(

### ISSUE THREAD

**Issue by eibmoz0304** [Perfare/UnityStudio#167]
i extract this bunlde from cache in app name Formacar but nothing happen, please help me to open it

http://www.mediafire.com/file/6lu94906c35u1s1/07DE1363518A5ED6C6218E132240EC63

**Comment by Perfare** [comment]
This should be encrypted and I can't help you

**Comment by eibmoz0304** [comment]
But some file can open and some file can not, hope you can help me, have a
nice day
