### ISSUE TITLE
Building error on Visual 2010 on Windows XP

### ISSUE THREAD

**Issue by Yuuyatails** [Perfare/UnityStudio#18]
Sorry for interrupting, it seems that I can't build the latest commit on my PC. It shows the problem on the line `using static Unity_Studio.UnityStudio;` in the UnityStudioForm.cs file, as you can see in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/10596039/22860387/3cf9104e-f137-11e6-97b2-cf4ff7a1bb4f.png)

Update: Furthermore, there's more build errors on the same .cs file as well. They are:
Error	1	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	57	17	Unity Studio
Error	2	The name 'MergeSplitAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	62	25	Unity Studio
Error	3	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	62	42	Unity Studio
Error	4	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	67	29	Unity Studio
Error	5	The name 'unityFilesHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	68	29	Unity Studio
Error	6	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	71	47	Unity Studio
Error	7	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	73	45	Unity Studio
Error	8	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	75	77	Unity Studio
Error	9	The name 'LoadAssetsFile' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	76	29	Unity Studio
Error	10	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	76	44	Unity Studio
Error	11	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	83	47	Unity Studio
Error	12	The name 'LoadBundleFile' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	86	29	Unity Studio
Error	13	The name 'unityFilesHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	91	21	Unity Studio
Error	14	The name 'assetsfileListHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	92	21	Unity Studio
Error	15	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	109	17	Unity Studio
Error	16	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	110	38	Unity Studio
Error	17	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	111	19	Unity Studio
Error	18	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	111	52	Unity Studio
Error	19	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	113	38	Unity Studio
Error	20	The name 'MergeSplitAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	118	21	Unity Studio
Error	21	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	118	38	Unity Studio
Error	22	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	122	65	Unity Studio
Error	23	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	142	33	Unity Studio
Error	24	The name 'unityFilesHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	143	33	Unity Studio
Error	25	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	152	33	Unity Studio
Error	26	The name 'unityFilesHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	153	33	Unity Studio
Error	27	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	158	21	Unity Studio
Error	28	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	158	34	Unity Studio
Error	29	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	160	44	Unity Studio
Error	30	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	164	45	Unity Studio
Error	31	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	166	44	Unity Studio
Error	32	The name 'LoadAssetsFile' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	168	29	Unity Studio
Error	33	The name 'unityFilesHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	171	25	Unity Studio
Error	34	The name 'assetsfileListHash' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	172	25	Unity Studio
Error	35	The name 'extractBundleFile' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	197	43	Unity Studio
Error	36	The name 'extractBundleFile' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	232	43	Unity Studio
Error	37	The name 'BuildAssetStructures' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	247	13	Unity Studio
Error	38	The name 'productName' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	251	21	Unity Studio
Error	39	The name 'productName' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	253	53	Unity Studio
Error	40	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	253	75	Unity Studio
Error	41	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	253	113	Unity Studio
Error	42	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	255	26	Unity Studio
Error	43	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	257	70	Unity Studio
Error	44	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	257	108	Unity Studio
Error	45	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	261	53	Unity Studio
Error	46	The name 'fileNodes' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	267	50	Unity Studio
Error	47	The name 'fileNodes' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	268	21	Unity Studio
Error	48	The name 'AllClassStructures' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	274	45	Unity Studio
Warning	49	Unreachable code detected	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	276	25	Unity Studio
Error	50	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	287	57	Unity Studio
Error	51	The name 'mainPath' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	289	54	Unity Studio
Error	52	The name 'AllClassStructures' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	318	17	Unity Studio
Error	53	The name 'AllClassStructures' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	323	44	Unity Studio
Error	54	The name 'AllClassStructures' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	329	45	Unity Studio
Error	55	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	454	22	Unity Studio
Error	56	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	523	43	Unity Studio
Error	57	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	569	31	Unity Studio
Error	58	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	621	17	Unity Studio
Error	59	The name 'exportableAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	621	33	Unity Studio
Error	60	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	622	49	Unity Studio
Error	61	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	643	21	Unity Studio
Error	62	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	651	21	Unity Studio
Error	63	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	659	21	Unity Studio
Error	64	The name 'WriteFBX' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1220	49	Unity Studio
Error	65	The name 'productName' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1248	44	Unity Studio
Error	66	The name 'WriteFBX' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1263	37	Unity Studio
Error	67	The name 'exportableAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1280	17	Unity Studio
Error	68	The name 'exportableAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1286	38	Unity Studio
Error	69	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1290	38	Unity Studio
Error	70	The name 'ExportTexture' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1326	37	Unity Studio
Error	71	The name 'ExportAudioClip' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1332	37	Unity Studio
Error	72	The name 'ExportFileExists' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1338	38	Unity Studio
Error	73	The name 'ExportShader' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1340	37	Unity Studio
Error	74	The name 'ExportFileExists' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1346	38	Unity Studio
Error	75	The name 'ExportText' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1348	37	Unity Studio
Error	76	The name 'ExportFileExists' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1354	38	Unity Studio
Error	77	The name 'ExportMonoBehaviour' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1356	37	Unity Studio
Error	78	The name 'ExportFileExists' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1362	38	Unity Studio
Error	79	The name 'ExportFont' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1364	37	Unity Studio
Error	80	The name 'ExportFileExists' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1369	38	Unity Studio
Error	81	The name 'ExportRawFile' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1371	37	Unity Studio
Error	82	The name 'unityFiles' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1490	13	Unity Studio
Error	83	The name 'assetsfileList' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1491	13	Unity Studio
Error	84	The name 'exportableAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1492	13	Unity Studio
Error	85	The name 'visibleAssets' does not exist in the current context	D:\3dModel\US Source 2\UnityStudio-master\Unity Studio\UnityStudioForm.cs	1493	13	Unity Studio

The last good commit I used is commit b580b293f364ba4110c406c6350c71af1ce601d0.

**Comment by Perfare** [comment]
It's C# 6.0 syntax
you can install Microsoft.Net.Compilers to build, see http://stackoverflow.com/questions/27093908/how-to-enable-c-sharp-6-0-feature-in-visual-studio-2013

**Comment by Yuuyatails** [comment]
Unfortunately, Microsoft.Net.Compilers requires .NET Framework 4.5 to work, which is not supported on Windows XP.

**Comment by Yuuyatails** [comment]
Also, C# 6.0 syntax requires .Net Framework 4.6 to work, which requires Windows Vista SP2 and later.

**Comment by Perfare** [comment]
Well, that's a bad news. Thanks very much for all your help
