### ISSUE TITLE
What about animations?

### ISSUE THREAD

**Issue by MagistrAVSH** [Perfare/UnityStudio#19]
It is really? Fbx with animation clips.

**Comment by Perfare** [comment]
No, see [README](https://github.com/Perfare/UnityStudio/blob/master/README.md)

> Export to FBX, with complete hierarchy, transformations, materials and textures. Geometry is exported with normals, tangents, UV coordinates, vertex colors and deformers. Skeleton nodes can be exported either as bones or dummy deformers

**Comment by SowBiT** [comment]
I think there is no way to export animation clip right now.
