### ISSUE TITLE
Textures have to be set manually, bug with converted textures

### ISSUE THREAD

**Issue by MetalBreaker** [Perfare/UnityStudio#2]
Hi,

I don't know if this is a bug or not, but when 3D models are exported and the texture is set to be converted (I've set mine to PNG), I have to set the textures manually in 3DS Max (inconvenience when exporting a lot of 3D models). The texture path for the material is good, but the extension of the texture file is missing. (for example, if I have a file named MyTex.png, the path would be MyTex instead of MyTex.png)

Also, when the textures are converted, they are also flipped, but the UVs on the exported models aren't flipped, so I have to manually flip them so the textures don't appear incorrectly. Just a minor inconvenience, but it gets tedious if you have a lot of 3D models exported and some of them are skinned (FBX doesn't allow any modifiers to be above the Skin modifier except for TurboSmooth, so I have to move the Skin modifier if the model is skinned and collapse the modifier stack if the model isn't skinned).

Thanks in advance.

**Comment by Perfare** [comment]
I fix the flip problem, but the texture still needs to be set manually and I don't know how to solve it

**Comment by MetalBreaker** [comment]
Thanks!

I've found a workaround to the "texture needs to be set manually" problem. I just run the Replace function in Notepad++, and I replace the filename with filename.png in the exported FBX.
Once again, thank you!
