### ISSUE TITLE
Supporting Sprites?

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/UnityStudio#24]
I don't know much about unity but are Sprites just a cropped area of a Texture2D? If so is there any way you can support exporting Sprites to png?

**Comment by Perfare** [comment]
I'm not sure what you're talking about, sprite textures(Texture2D) can be extracted.

**Comment by XilasZ** [comment]
Hi,

I think he was talking about the unity object "Sprite", which is a cropped area of a Texture2D.

I added a quick support for visualization, it works well with assets from Hawk Freedom Squadron game (android).

Here : [add-simple-sprite-support.patch.txt](https://github.com/Perfare/UnityStudio/files/1245463/add-simple-sprite-support.patch.txt)
