### ISSUE TITLE
Wii U Asset support?

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/UnityStudio#25]
I'm not sure how worthwhile it would be to add this, as the few Unity Wii U games I've dumped are already supported since they don't use the Wii U compiled assets.

https://mega.nz/#!8xISXTja!_rc6SB8c2X1npnuSV-qfd8yX_BbD3BXYG0LQFolnbJc

**Comment by Perfare** [comment]
Wii U Asset is supported, Just have some bug, I fixed it in commit b4bce77381cd14fa2a36afb9b4b65869821c4f99

**Comment by KekMcGee** [comment]
It's working now, thanks.
