### ISSUE TITLE
if extract folder, stops in error.

### ISSUE THREAD

**Issue by YuK1Game** [Perfare/UnityStudio#27]
Can I skip if it is an exception?

> 問題の署名:
>   問題イベント名:	CLR20r3
>   問題の署名 01:	unity studio.exe
>   問題の署名 02:	0.6.6.0
>   問題の署名 03:	58aa9c2d
>   問題の署名 04:	mscorlib
>   問題の署名 05:	4.0.30319.18444
>   問題の署名 06:	52717d7e
>   問題の署名 07:	4436
>   問題の署名 08:	19
>   問題の署名 09:	System.IO.EndOfStreamException
>   OS バージョン:	6.1.7601.2.1.0.256.48
>   ロケール ID:	1041
>   追加情報 1:	8d2c
>   追加情報 2:	8d2c6a6d303b93140ed3f2799b4cf1f5
>   追加情報 3:	111b
>   追加情報 4:	111bdb9dea6efcc6f26f26115191e330

**Comment by Perfare** [comment]
try use File -> Load file

**Comment by Perfare** [comment]
Because you haven't replied to me for a week, I think you have solved the problem, if the problem has not been solved, it is best to upload files and i will check
