### ISSUE TITLE
Failed to open a unity3d file from the game Hearthstone

### ISSUE THREAD

**Issue by emilic** [Perfare/UnityStudio#3]
I was trying to use this to explore the Hearthstone unity3d files.  It opens most but it failed reading the 
cardtextures0.unity3d (C:\Program Files (x86)\Hearthstone\Data\Win), if it helps the file is quire large at 360MB.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Unity_Studio.UnityStudioForm.<>c__DisplayClass50_0.<BuildAssetStrucutres>b__0()

**Comment by Perfare** [comment]
I tested the cardtextures0.unity3d of the Hearthstone, load and export work properly.
I think I need more information to identify the reasons for the problem.

**Comment by emilic** [comment]
I just tested it again.  It seems to be working.   I blame windows.
