### ISSUE TITLE
When exporting models, if the texture is in another asset file it wont extract along with the model

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/UnityStudio#30]
Edit: Or this could be because of https://github.com/Perfare/UnityStudio/issues/29

**Comment by Perfare** [comment]
According to your description, You need to load file name is globalgamemanagers(unity 5.x) or maindata, In this way UnityStudio will load other assets and establish links between them.
If you still have problem, please upload the file.

**Comment by MichaelPriebe** [comment]
Yeah its most likely from https://github.com/Perfare/UnityStudio/issues/29 exporting stuff its not supposed to so it doesn't extract the textures.

**Comment by Perfare** [comment]
upload the file, or I can't help you

**Comment by MichaelPriebe** [comment]
https://mega.nz/#!y5EmRJgL!8z9p3tGi6GRMu-D4sWipZ3fUPA-jDjXa0y4ojB-gR6w

in level 5 export the DisneyStore folder and you will be greeted by the world being exported multiple times at different locations and only one object with textures
![](http://i.imgur.com/zRAIJbO.png)

**Comment by Perfare** [comment]
Because you upload the file does not have a resource file so I can not further test, But I looked at the FBX file the texture is extract find.
About your second problem, level5 file contains these things and UnityStudio just normal export them

**Comment by MichaelPriebe** [comment]
https://mega.nz/#!SgdVjCzI!bqKiK_FGIrNEtqQJ3hRs8Hr2zPtyfGhLtd5jrW1luEA
Here is all the files.
But it exporting like this is normal?
https://camo.githubusercontent.com/4817175468bb8fa42839973d7e8cb00f2f9773d2/687474703a2f2f692e696d6775722e636f6d2f565949306d426d2e706e67

**Comment by nkAlex** [comment]
I was also having such a problem with meshes when trying to extract FBX.

I think this only happens when you try to extract **static** baked meshes: instead of extracting individual objects, Unity Studio extracts the root mesh numerous times, setting the scale, rotation and position of every clone to an actual object's scale, rotation and position.

Extracting dynamic meshes usually works with no problems.

**Comment by Perfare** [comment]
@MichaelPriebe About your screenshot, I check it and didn't find something about 'exported multiple times', 
It seems to me that the scene is what it looks like. If UnityStudio does have problems, It's beyond my ability and I can't fix it.

**Comment by MichaelPriebe** [comment]
@Perfare dang, did you see what @nkAlex said though, that might be exactly the cause because the only objects I've seen export correctly are ones that move. (That sign for example)
