### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by Stellarspace** [Perfare/UnityStudio#33]
Would it be possible to make the program look prettier?

**Comment by SowBiT** [comment]
Yes it is possible but why ?

**Comment by Stellarspace** [comment]
@SowBiT The UI is really ugly.

**Comment by Stellarspace** [comment]
@SnowBiT Something like this:
File > Open...
File > Open folder
File > Export > Selected
File > Export > All
File > Exit
Edit > Copy
Edit > Cut
Edit > Paste
Edit > Select All
Edit > Preferences
Debug > Show All
Debug > Export > Logs
Debug > Export > Raw

**Comment by Perfare** [comment]
It would be possible, but I'm not good at designing the user interface

**Comment by Stellarspace** [comment]
@Perfare If I were to design a user interface, could you apply it?

**Comment by ordigdug** [comment]
@Stellarspace how good are you at deigning/implementing UI?  Do you have any examples of UI's you did?
