### ISSUE TITLE
Possibly missing assets?

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/UnityStudio#34]
I'm sorry to make an issue, I just wanted to ask a question,
My friend opened up one of the unity files in a text editor and found these strings

![](http://i.imgur.com/fPYyCRq.png)

Searching up some of these names in Unity Studio displays no results, what are they?

**Comment by Stellarspace** [comment]
Upload the assets and give the link please

**Comment by Perfare** [comment]
I don't get any useful information from your screenshot, in my opinion, this is not a proprietary format for unity3d
