### ISSUE TITLE
Could you guys add support to extract unity files with the "__data" file format? 

### ISSUE THREAD

**Issue by BS92** [Perfare/UnityStudio#39]
This program could do it (https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor), but I prefer Unity Studio a lot more since it has more useful features. 

I attached a zip file that contains the files so that you can test them. It's from a new mobile game, so I assume Unity Studio doesn't support it yet, but I hope it will in the nearest future. 

Keep up with the good work as always!

[Test.zip](https://github.com/Perfare/UnityStudio/files/870626/Test.zip)

**Comment by Perfare** [comment]
rename '__data' to ‘__data.unity3d’. It's supported

**Comment by BS92** [comment]
That does seem to work, but functions such as Load folder doesn't seem work like it did with another game I tested.

**Comment by BS92** [comment]
Thanks for responding back. That does seem to work. What I'd like to see is to see be done possible is to extract the files all at once without any having to rename and move them into a single folder. 

To give an example, this here is from a different game and the Load folder function is working (since the files are in CAB format) without having to make any changes and that makes extracting files easier and quicker for the user. 

[Shared.zip](https://github.com/Perfare/UnityStudio/files/870771/Shared.zip)

**Comment by Stellarspace** [comment]
They have to be in a single folder. The program looks for assets to extract from.

**Comment by BS92** [comment]
There are cases where they don't have to be in a single folder, as in the example of the Shared.zip. If you use Load folder in the Shared folder, it will load all of the folders inside it.

**Comment by Stellarspace** [comment]
That's a single folder, there are subfolders inside it, yes.

**Comment by BS92** [comment]
Ah okay, so what I mean is, is it possible to make it work with __data files as well? As in the example of Test.zip, since I'm getting errors when trying to load the Test folder, whereas I'm not when doing it with the Shared folder. The difference is only that __data files aren't supported when CAB files are. Also, when renaming it to .unity3d, loading the folder still doesn't work. I have to rename, take out the files out off the sub folders and then load them as files instead of folders all at once for it to work, and that's a very long process compared to where you can instantly load a folder and all the subfolders inside it.

**Comment by Perfare** [comment]
use 'Load File' instead of 'Load folder', __data is bundle file, 'Load folder' can only load asset file

**Comment by BS92** [comment]
Ah I see. I guess that's the only way then. Thanks for the clarification.
