### ISSUE TITLE
About Windows XP support

### ISSUE THREAD

**Issue by Yuuyatails** [Perfare/UnityStudio#4]
Sorry if I ask this so sudden.

According to RaduMC (Also known as Chipicao) on Xentax forum, Unity Studio should be able to run on Windows XP with the .NET framework 4.0 installed. But no, the application won't run on Windows XP at all. (It doesn't shows any error message window, either.) I checked the task manager at the moment I start the Unity Studio, but the application close itself without any error message.

Someone on Xentax forum was able to modify the application to make it runs on XP (If you are curious, the post in question is in the 13th page of the thread.)

I wonder if you can modify your forks of Unity Studio to make it runs on Windows XP. 

In case you are wondering, I have a PC that is runs on Windows XP Professional SP3 and I don't enough have money to brought a new PC or (for the reason that the hardware is old) upgrade the OS. I guess you will likely to tell me to brought a new PC despite my family's finance situation.

Edit: I just installed Visual Studio C# 2010 SP1 and tries to debug Unity Studio, <s>but Visual Studio shows me the 'Error while trying to run project: Cannot start debugging: the assembly to be debugged was built with a platform incompatible with the current system' error everytime I try to debug.</s>

Edit 2: Nevermind, I just set the whole solution to 'X86', however there's a error while I try to build it in Visual Studio: 'Invalid Resx file. The parameter is incorrect Line 836, position 5.' The error was from the file UnityStudioForm.resx. I just don't know how to fix this one.

**Comment by Perfare** [comment]
Sorry, I don't know how to solve this problem...

**Comment by Yuuyatails** [comment]
@Perfare: Apparently, it was these lines that causes the application to not able to start in Windows XP:

`<data name="$this.Icon" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">`
`<value>`
(This section is omitted due to overly long codes)
`</value>`
`</data>`

Removing those lines will allows the Unity Studio to run on Windows XP. I wonder why...

**Comment by Perfare** [comment]
I found some reasons, looks like the XP system only supports less than 128x128 resolution icon, but the resolution of this icon is 256x256

**Comment by Yuuyatails** [comment]
@Perfare: Then how can I change the icon to the one with 128x128 resolution? 

Note that I have Visual Studio 2010 Express installed in my PC.

**Comment by hozuki** [comment]
@Perfare You can use an icon editor to generate a series of icons.

Suggested:
32bpp RGBA: 256x256 48x48 32x32 16x16
256 Colors: 48x48 32x32 16x16

Windows will try to find the first readable (and fittest) sub-icon. So with this series in an icon file, Windows XP will try to load the 32bpp 16x16 for window icon, and 32bpp 48x48 for File Explorer (tile view), etc.

**Comment by Yuuyatails** [comment]
Okay, I can confirmed that the latest commit have fixed the issues of not able to build and run on Windows XP PC.

**Comment by Perfare** [comment]
@Yuuyatails Okay, thank you for your testing.
