### ISSUE TITLE
Got a problem with selecting multiple files in the Asset List

### ISSUE THREAD

**Issue by BS92** [Perfare/UnityStudio#40]
So when I sort the assets into types, and a type that I'm after is in the middle, how can I select multiple files of that type without selecting any other? I can't select the files unless I do it from the bottom, and that means I'm getting a lot of files that I don't want. Also filtering doesn't help either, since it doesn't apply to file types, just the file name.

**Comment by Stellarspace** [comment]
@BS92 Check in the checkbox next to the assets you want to export and click "Export > Selected Assets" I know the UI is terrible, I want to create a new one.

**Comment by BS92** [comment]
I know about Selected Assets. My issue is that I can't select assets without selecting them from the bottom of the files. I'm trying to hover over texture2d files, but I can only select one file unless I go to the bottom to hover over files, but a huge bunch of transform files lies at the bottom there, making it impossible for me to get only texture2d files unless I export both of them and delete the transform folder afterwards, in which case I could just ignored Selected Assets and export All Assets and delete the folders I don't want, but that would defeat the purpose of Selected Assets.

**Comment by Stellarspace** [comment]
@BS92 Once again, there is a checkbox next to each asset, you can check each asset you want to export with the Selected assets option. Transforms aren't even supported, the only way it shows up is if you have Developer options enabled.

**Comment by BS92** [comment]
The checkbox in scene hierarchy you mean? So if I check those, how do I know which assets they are tied to when loading multiple assets?

**Comment by Perfare** [comment]
I don't quite understand what you mean. In my opinion, you only need to select the first file you want to export -> Hold down shift and select the last file you want to export -> Export

**Comment by BS92** [comment]
Oh, I didn't know about the shift thing. That solves my problem. Thank you.
