### ISSUE TITLE
Split Assets

### ISSUE THREAD

**Issue by Stellarspace** [Perfare/UnityStudio#42]
Does Unity Studio support split assets? Also when exporting 3D Objects with their textures, the program stops responding, but it is still exporting then it says that it's done exporting.

**Comment by Perfare** [comment]
supported

**Comment by Stellarspace** [comment]
@Perfare Thank you, I just confirmed that it is supported. Now I was just wondering why it stops responding when I export a 170 MB FBX file.

**Comment by Stellarspace** [comment]
Also when I export as split, the program doesn't finish.
