### ISSUE TITLE
Exporting and Duplicate Objects

### ISSUE THREAD

**Issue by Stellarspace** [Perfare/UnityStudio#43]
When I export all the 3D Objects, I am unable to open the FBX file in Maya, etc. I am also unable to convert the FBX to another file format. I exported 3D Objects as split, opened it in Unity and the result was duplicated Objects. Any reason?

**Comment by Perfare** [comment]
Try using 3DS Max

**Comment by Stellarspace** [comment]
@Perfare The combined FBX imported successfully into 3DS Max, but I'll need to check for duplicated objects later.

**Comment by Perfare** [comment]
Do you mean exporte fbx contain multiple objects are the same? It will happen when multiple objects are use same mesh, you only need to select one of the export

**Comment by Stellarspace** [comment]
@Perfare I exported via split and the world wasn't displayed properly in 3DS Max. There were objects in places where it shouldn't have been.

**Comment by Perfare** [comment]
Choose what you want and export, don't use "All 3D objects (split)" if you don't know what this is

**Comment by Stellarspace** [comment]
@Perfare What is the "All 3D Objects (split)" option?

**Comment by Perfare** [comment]
split root objects with their first sub node

**Comment by Stellarspace** [comment]
@Perfare What does that mean?

**Comment by Perfare** [comment]
Well, if you can read the code, please read the code, I can't explain it more clearly in English
