### ISSUE TITLE
Shows nothing in the FBX output

### ISSUE THREAD

**Issue by Cedrusli** [Perfare/UnityStudio#44]
I am totally a beginner in this area. I am trying to get the 3D models from a android game(for collection
). It seems that the 3D models is split in the asset list. All exported 3D object show nothing at FBX viewer. Can it be fixed? OR It is encrypted? Here is a picture for reference... I am sorry for poor English and knowledge. 

![untitled](https://cloud.githubusercontent.com/assets/26855455/24589073/f7f805ee-1806-11e7-9193-40691c830c67.png)

**Comment by Perfare** [comment]
Please sort by size then choose the model you want, import it to 3ds MAX

**Comment by Cedrusli** [comment]
Oh, I see! Thank you very much! Sorry for asking a very stupid question.
