### ISSUE TITLE
Models don't have UV maps. (fix included)

### ISSUE THREAD

**Issue by volfin** [Perfare/UnityStudio#45]
in UnityStudio.cs, in ExportMesh() function, add this code after Colors #2 

                #region UVs1
                if (m_Mesh.m_UV1 == null)
                {
                    var uvs1 = new ManagedFbx.Vector2[m_Mesh.m_VertexCount];
                    for (int c = 0; c < m_Mesh.m_VertexCount; c++)
                    {
                        uvs1[c] = new ManagedFbx.Vector2(0.5f, 0.5f);
                    }
                    mesh.TextureCoords = uvs1;
                }
                else if (m_Mesh.m_UV1.Length == m_Mesh.m_VertexCount * 2)
                {
                    var uvs1 = new ManagedFbx.Vector2[m_Mesh.m_VertexCount];
                    for (int c = 0; c < m_Mesh.m_VertexCount; c++)
                    {
                        uvs1[c] = new ManagedFbx.Vector2(m_Mesh.m_UV1[c * 2], m_Mesh.m_UV1[c * 2+1]);
                    }
                    mesh.TextureCoords = uvs1;
                } 
                #endregion

Now models will be saved with UV map.

**Comment by Perfare** [comment]
Thank you, I will add it to the code
