### ISSUE TITLE
Textures not show 

### ISSUE THREAD

**Issue by GalatasarayForever** [Perfare/UnityStudio#47]
First of all you made really very good job, thank you very much.
My problem is:
I have a .asset file. When I export it with unitystudio some textures like bump, normal, diff.. maps were not show when I open in blender or other softwares. When I check the tree in blender the textures are there, but not show when render. I convert them by fbx converter to binary fbx and obj but nothing change. I think something with the mapping coordinates are not working. When I convert in obj, non of the textures were show when rendering. I check the mtl file, all textures are there. Ok i can export diffuse map and obj from the asset file with unityex and texture the obj in blender by easy way but i cannot and do not know how to add the bump, normal, diff... maps in blender. The model is human and have realistic textures. Please help

**Comment by Perfare** [comment]
Using 3DS Max, other software can not be guaranteed to correctly read FBX format
