### ISSUE TITLE
How to repack assets ?

### ISSUE THREAD

**Issue by jeason1997** [Perfare/UnityStudio#49]
I modify a game ,such as replace some texture, can I repack the assets ? thanks :)

**Comment by jeason1997** [comment]
好吧，我发现你是中国人==，编了半天做鸡的英语，我想问下，资源有重新打包的可能性吗？
最近在玩一款叫《武器店物语》的国产u3d游戏，想做一些美化MOD，提取出资源了，也修改了，却不知道怎么导回去。

**Comment by jeason1997** [comment]
@Perfare

**Comment by Perfare** [comment]
使用[UABE](https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor)

**Comment by cai-chenghui** [comment]
显然UABE已放弃对2018+版本Unity的支持，有兴趣重新考虑这个功能分支吗？
