### ISSUE TITLE
一些問題

### ISSUE THREAD

**Issue by kiletw** [Perfare/UnityStudio#5]
一個是目前好像不支援unity5.3.6版本，會無法解析。

另外一個是語音如果遇到FSB.vorbis格式的時候雖然可以撥放但是無法轉成wav提取出來

問問看有沒有解決辦法?

**Comment by Perfare** [comment]
1.上传文件给我
2.是不是没在设置里开启转换

**Comment by kiletw** [comment]
5.3.6的檔案
https://mega.nz/#!WgIh2ZBa!x58jg2NMjIlOUCDJbv2tkW_eW90SGt48A9qFR7o9ayA

確定有點轉換成.wav 
https://mega.nz/#!3wwmyYSL!KOB3YWOOHSuVagnnL33MlKKDJ9YLDWOSyTw7VAalBs8

他跑到UnityStudioForm.cs 3256行時就回傳false 跳出function

**Comment by lwlin** [comment]
第二个问题应该是你抓的资源问题或者解密出了问题,我自己抓了一次,不存在你那个档的提取问题

**Comment by Yuuyatails** [comment]
@kiletw: 关于第一个问题，事前必须要用UABE (至少2.0b版本) 来解压，然后从解压后的文件里把assets文件取出来。之后才能用Unity Studio来读取Assets文件。

**Comment by Perfare** [comment]
1. 新代码支持这种格式了
2. 我换了一种方式去转换FSB格式文件

**Comment by kiletw** [comment]
@lwlin   我見過你，在熊貓網站上(?  我用的解密程式是從官方dll代碼複製出來的啊，我想說預覽那邊可以    正常撥放，可是卻無法提取所以我不會去想說那是檔案的問題。


@Yuuyatails  我知道UABE可以解，只是想說UABE可以解那UnityStudio應該也可以研究一下支援才對

@Perfare  感謝修改  我再測試一下

**Comment by lwlin** [comment]
@kiletw 我又提取了一次,跟我上次提取的比对是完全一致,而且同样没问题,建议你真的可以再试试新提取一次.同时之前忘了说,你那个资源我测试了五次,有两次预览也会跳异常

**Comment by kiletw** [comment]
@lwlin 你解碼程式碼也是長這樣嗎?

 public static byte[] DecryptBytes(byte[] message)
        {
            if (message == null || message.Length == 0)
            {
                return message;
            }
            byte[] result;
            using (RijndaelManaged rijndaelManaged = new RijndaelManaged())
            {
                rijndaelManaged.Key = Convert.FromBase64String("ExmGM04QVp52sgGnwCwoTO+imSnWTXg5y+QrpVBCXNs=");
                rijndaelManaged.IV = Convert.FromBase64String("2vYybHoCnSa9SD8Nu6ssAA==");
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    using (ICryptoTransform cryptoTransform = rijndaelManaged.CreateDecryptor())
                    {
                        using (CryptoStream cryptoStream = new CryptoStream(memoryStream, cryptoTransform, CryptoStreamMode.Write))
                        {
                            cryptoStream.Write(message, 0, message.Length);
                            cryptoStream.FlushFinalBlock();
                            result = memoryStream.ToArray();
                        }
                    }
                }
            }
            return result;
        }

因為之前解圖片都沒問題只有語音出問題
