### ISSUE TITLE
Export Animation Clip

### ISSUE THREAD

**Issue by 38550727** [Perfare/UnityStudio#50]
Does it support export animation data of skeletal mesh?

**Comment by Perfare** [comment]
No, please see [README](https://github.com/Perfare/UnityStudio/blob/master/README.md)

> Export to FBX, with complete hierarchy, transformations, materials and textures. Geometry is exported with normals, tangents, UV coordinates, vertex colors and deformers. Skeleton nodes can be exported either as bones or dummy deformers

**Comment by Sn0wBiT** [comment]
Mesh with skeleton is supported. Animation is not yet.

**Comment by 38550727** [comment]
Is there any plan about this function?
Animation data is very important for a skeletal mesh.

**Comment by Perfare** [comment]
probably not
