### ISSUE TITLE
Unsupported assets

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/UnityStudio#52]
Crashes when attempting to load.

Version: "5.5.0x1-CollabPreview"
https://mega.nz/#!t4hS3CpK!P--shnW7NiOs_sYRRxIHhDUl87YX_k4ajSlWMDwL5lU

**Comment by Perfare** [comment]
fixed in b319e92b3e6ddb98440322e3c3db4aecc895262c

**Comment by KekMcGee** [comment]
Working now, thanks!
