### ISSUE TITLE
How to get resources path?

### ISSUE THREAD

**Issue by duduluu** [Perfare/UnityStudio#53]
我想要在提取文件的时候，按照文件原本打包时的原路径来提取，而不是给重名的文件加上 uniqueID。这是否可行？

I'd like to export files as their original path, not append uniqueID when has the same name. Is it possible?

**Comment by Perfare** [comment]
勾选"Display asset original name"，只对bundle类文件有效

**Comment by duduluu** [comment]
我提取的是游戏RimWorld的资源文件，不是bundle类。但我发现提取出来有个“ResourceManager.dat”文件里储存有路径信息。

`
public static void foo()
{
    List<string> allPaths = new List<string>();
    using (BinaryReader br = new BinaryReader(File.OpenRead("ResourceManager.dat")))
    {
        // 头4个字节储存路径的数量
        int count = br.ReadInt32();
        for (int i = 0; i < count; i++)
        {
            // 路径字符串长度
            int length = br.ReadInt32();
            string path = Encoding.ASCII.GetString(br.ReadBytes(length));
            // 路径末尾的填充0
            int mod = length % 4;
            if (mod > 0)
            {
                mod = 4 - mod;
                br.BaseStream.Position += mod;
            }
            // 0x3 ASCII end of text
            int end = br.ReadInt32();
            long pathID = br.ReadInt64();
            allPaths.Add(path);
        }
    }
}
`
