### ISSUE TITLE
Allow opening files with other extension

### ISSUE THREAD

**Issue by jack980517** [Perfare/UnityStudio#54]
Some unity games, especially unity5 games, uses assets downloaded after installation (i.e. not packaged within the app itself), and these assets often use non-standard extension, or no extension at all. Allowing opening these files directly would be much more convenient. It shouldn't be hard to decide the file type using the file header as they are very obvious.

有些Unity游戏，尤其是Unity5游戏，使用的是安装过后下载的assets，也就是没有包装在app内的assets。这些assets文件往往使用的不是标准的扩展名，或者根本没有扩展名。允许直接打开这些文件就方便得多，不用先重命名。用文件头部判断文件类型应该不难，因为都很明显。

**Comment by Perfare** [comment]
打开文件选择第三或第四个选项，另外asset的头不好判断
