### ISSUE TITLE
Exception on export or view 3ds model with bones - System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by dimmduh** [Perfare/UnityStudio#57]
Mesh.cs #1114
m_Skin[s][count].weight = (float)((double)(weightLevel - bitmax) / bitmax);
count is more than length

I put before
if (count > 3) break;
and it seems help

**Comment by Perfare** [comment]
I think you put the problem in the wrong place

**Comment by dimmduh** [comment]
What's the right place?

**Comment by Perfare** [comment]
I don't know where the right place is, but it's definitely not here.
Because I can't find the code anywhere [Mesh.cs#L1114](https://github.com/Perfare/UnityStudio/blob/master/Unity%20Studio/Unity%20Classes/Mesh.cs#L1114)
