### ISSUE TITLE
导出某些模型资源会导致Unitystudio自动关闭..

### ISSUE THREAD

**Issue by 1vr** [Perfare/UnityStudio#62]
版本是5.3.3,resourecs.assets打开后在场景层级中有子集的模型资源,勾选后使用导出选择的资源会导致程序关闭,没有任何提示.如导3D Object可以顺利导出obj模型.但是它没有UV.谢谢作者提供这么屌的工具.

ps:提取的shader能直接使用吗?

**Comment by Perfare** [comment]
1.上传文件给我，UV问题等我有空了会修
2.不能
