### ISSUE TITLE
AudioClip: Can't find the resource file 

### ISSUE THREAD

**Issue by ghost** [Perfare/UnityStudio#623]
I got this error when trying to open AudioClips. But it works fine on other extractors

Filename main.2775.com.naturalmotion.customstreetracer2.obb. Open it as zip file: https://apkcombo.com/csr-racing-2-%E2%80%93-free-car-racing-game/com.naturalmotion.customstreetracer2/download/apk

![image](https://user-images.githubusercontent.com/64008639/94990157-38addf00-057a-11eb-83c7-9a91c6e9ca07.png)

**Comment by Perfare** [comment]
This file exists in main.2855.com.naturalmotion.customstreetracer2.obb, make sure you unzip all the files and you have not deleted this file locally
