### ISSUE TITLE
AssetStudio v0.15.23 Stop Working

### ISSUE THREAD

**Issue by yuameshi** [Perfare/UnityStudio#624]
I have on-cloud ECS Server without graphics card by aliyun, running with 2gigs of RAM and Intel XEON Platinum 8269CY.(I think is is RAM problem), over Windows Server 2012R2
When I'm loading a directory , it sends an error message just like picture below. it said that there's an unknown software exception(**0xe0434352**) at position **0x9cc67afc**.
![Screenshot_2020-10-03-22-07-59](https://user-images.githubusercontent.com/64469437/94993749-bb0fc080-05c5-11eb-91e4-9f1b9be16a8b.jpg)
)

PS: Asset studio cannot run on my personal computer too.(that's why I use my server) When I loading directory, the software connot load a directory (I means:it **returned to the home screen with nothong loaded** just like the video below), but I can normally use it on version 0.14.x.
It runs with 8gigs of RAM and Intel Core i5 3450.
[ScreenRecord20201004094209.mp4.zip](https://github.com/Perfare/AssetStudio/files/5322554/ScreenRecord20201004094209.mp4.zip)

Please help me!

**Comment by Perfare** [comment]
抱歉，我认为这很有可能是操作系统或者硬件导致的原因，我无法修复它
