### ISSUE TITLE
Is there any way to get the .meta file?

### ISSUE THREAD

**Issue by a278327209** [Perfare/UnityStudio#625]

**Comment by Tosyk** [comment]
I think this files are only for unity to build the game. they are not present in the final game build,

**Comment by a278327209** [comment]
Thank you for your reply, i'm trying to export the sprite, it's made up of multiple pictures.  I only can get the .png file, the information like origin or width for every picture are missing. I think there may be a some kinds of file like .meta file to store Those information,even in the final game build.

**Comment by benediktwerner** [comment]
uTinyRipper is able to reconstruct the .meta files so the information must be stored in the final game build as well

**Comment by Perfare** [comment]
using [UtinyRipper](https://github.com/mafaca/UtinyRipper)
