### ISSUE TITLE
Genshin Impact shaders unreadable

### ISSUE THREAD

**Issue by TungstenSeraph** [Perfare/UnityStudio#626]
![image](https://user-images.githubusercontent.com/72622200/95644632-f149b600-0a85-11eb-9066-700897fa84f6.png)
As shown. At least 80 files error out in the same fashion on export, but they all appear to deal in shaders.

**Comment by TungstenSeraph** [comment]
From https://github.com/mafaca/UtinyRipper/issues/770 it seems that this may be due to a new way unity itself works.

**Comment by Perfare** [comment]
The game should use a custom Shader structure and will not consider support.
