### ISSUE TITLE
UV error

### ISSUE THREAD

**Issue by alittlered** [Perfare/UnityStudio#627]
https://mega.nz/file/jDZQWBRZ#mxU76a8vs7DVNwaD0YhZs_EBdrbqOJIkqo2OY5WUwl0

**Comment by Perfare** [comment]
I did not find any UV problems, if you still think there is a problem, please describe in detail.

**Comment by alittlered** [comment]
> I did not find any UV problems, if you still think there is a problem, please describe in detail.
Here, i add the texture file this time so you can see what the problem is.
https://mega.nz/file/6CgTVQhQ#qVROcS5tfLw_VQLgBrmNxhee4NdqHX_BHGbFFgkHxAk
