### ISSUE TITLE
Can't extract unity asset

### ISSUE THREAD

**Issue by SunnyLeu** [Perfare/UnityStudio#628]
[EB7746C26C82FAFB4E31948CAECA56E360B3776E.zip](https://github.com/Perfare/AssetStudio/files/5363871/EB7746C26C82FAFB4E31948CAECA56E360B3776E.zip)
(file zipped)
Someone asked this before( #590 ), but this problem stills bothers me.
The asset file can't be extracted, the version number(2019.3.0f6) was been erased, how can I add it back?

Also, I suggesed to add a feature:
If the file's version number is weird, AssetStudio can ask user which version to use to extract or set a default version to extract.

Thank you very much

**Comment by Perfare** [comment]
Sorry I will not consider adding this feature. Although it seems that the version number is only erased, there may be changes in other places. I do not plan to spend time on such encryption-like changes.
