### ISSUE TITLE
Error when trying to extract Texture2D

### ISSUE THREAD

**Issue by vorts** [Perfare/UnityStudio#632]
![ss](https://user-images.githubusercontent.com/72933464/96150249-7c093580-0f0a-11eb-8d3f-b8e0b27c934c.png)

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by vorts** [comment]
> Please upload the source file to me.

it wasn't a specific file, but every unity game i tried, but for some reason i'm not actually getting that error anymore, i think it was something to do with my PC, Texture2D are extracted perfectly fine now

**Comment by vorts** [comment]
> > Please upload the source file to me.
> 
> it wasn't a specific file, but every unity game i tried, but for some reason i'm not actually getting that error anymore, i think it was something to do with my PC, Texture2D are extracted perfectly fine now

the error is back again, even games that i successfully extracted before no longer work, apparently it happens at random (but i suspect it's related to Windows getting update, it seems it was magically resolved before after an update, and now it's back yet again right after another Windows update)

**Comment by Perfare** [comment]
I will change the export method of the image in the near future. no longer use GDI+. It should fix this problem.

**Comment by SpicyCatGames** [comment]
This is also happening to me when I attempt to export sprite or Texture2D on v0.15.32

**Comment by Perfare** [comment]
I have modified the library used by the image processing, this problem should have been resolved, but the new version has not been officially released, you can download the latest build version from here https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
