### ISSUE TITLE
Can i run Asset Studio in 32x bit machine?

### ISSUE THREAD

**Issue by RevVans** [Perfare/UnityStudio#633]
Can i run Asset Studio in 32x bit machine?

**Comment by mikowiec** [comment]
I compiled AssetStudio 0.15 last version to x86 target and it works nice.
You need to install fbxsdk v2020 for x86, but installer from Autodesk exists for x64 only.
I've obtained libs from this repo:
https://github.com/CarLoiD/CLD_SDK
  (\ThirdParty\FBX\)

**Comment by Perfare** [comment]
AssetStudio supports 32-bit systems, but due to 32-bit memory problems, it may not work properly.
