### ISSUE TITLE
Windows7 x64无法运行，启动时直接停止工作

### ISSUE THREAD

**Issue by olivblip** [Perfare/UnityStudio#634]
作者大大你好，我在Windows7 SP1的系统上尝试运行最新版的release版本，启动后报错信息如下：

问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	AssetStudioGUI.exe
  问题签名 02:	0.15.23.0
  问题签名 03:	fbe9d864
  问题签名 04:	AssetStudioGUI
  问题签名 05:	0.15.23.0
  问题签名 06:	fbe9d864
  问题签名 07:	1e0
  问题签名 08:	6
  问题签名 09:	System.TypeInitialization
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	decf
  其他信息 2:	decf9afcdb05a7d51839a3d9359dd1d0
  其他信息 3:	62d2

请问如何解决，或者是否还需要提供其他信息？

**Comment by Perfare** [comment]
应该已修复
