### ISSUE TITLE
Getting dll files from data.unityweb file

### ISSUE THREAD

**Issue by Blqck666** [Perfare/UnityStudio#635]
is there a support to get assembly-CSharp.dll ... from unity web game (*.unityweb) , or to visualize MonoBehaviour/c# code??

**Comment by 0x900x90** [comment]
https://github.com/DerPopo/UABE/issues/312

**Comment by USQREN** [comment]
> 0x900x90

How to reset assemblies ?

**Comment by 0x900x90** [comment]
What do you mean? Question is about unpacking .unityweb files.

**Comment by USQREN** [comment]
> What do you mean? Question is about unpacking .unityweb files.

How do I get the Assembly-CSharp.dll out of the unityweb build ?

**Comment by 0x900x90** [comment]
Are you sure your unityweb contains dlls? My utility unpacks everything from unityweb. Just run it from commandline like this:
wdu yourfilename.unityweb

Also you can upload your file somewhere and i'll check it.

**Comment by Blqck666** [comment]
I tried your utility, and you can unpack dlls with it , from what i learned the web build code is not a dll, it is compiled as web assembly and the only utility available as far as i know is this https://www.devxdevelopment.com/ , to do this we need to figure out how we decompile web build

**Comment by USQREN** [comment]
> Are you sure your unityweb contains dlls? My utility unpacks everything from unityweb. Just run it from commandline like this:
> wdu yourfilename.unityweb
> 
> Also you can upload your file somewhere and i'll check it.

You can see this build. It should definitely contain dll assemblies. And one more question, do you have an unpacker of the * .datagz extension type (Another kind of WebGL build)?

[build.zip](https://github.com/Perfare/AssetStudio/files/5468589/build.zip)

**Comment by NotOats** [comment]
> Are you sure your unityweb contains dlls? My utility unpacks everything from unityweb. Just run it from commandline like this:
> wdu yourfilename.unityweb

From what I gather they are trying to extract wasm files into a traditional unity .net assembly. Unfortunately "*.unityweb" by default has more than one file type. One is a packed bundle of files and the other, from what I can tell, is a processed wasm file.

When unity exports a project into web assembly it'll spit out:

<project_name>.data.unityweb <- bundle file
<project_name>.wasm.code.unityweb <- wasm file

**Comment by USQREN** [comment]
> > Are you sure your unityweb contains dlls? My utility unpacks everything from unityweb. Just run it from commandline like this:
> > wdu yourfilename.unityweb
> 
> From what I gather they are trying to extract wasm files into a traditional unity .net assembly. Unfortunately "*.unityweb" by default has more than one file type. One is a packed bundle of files and the other, from what I can tell, is a processed wasm file.
> 
> When unity exports a project into web assembly it'll spit out:
> 
> <project_name>.data.unityweb <- bundle file
> <project_name>.wasm.code.unityweb <- wasm file

wasm.code.unityweb is not unpacked. And in my opinion, it does not contain game assemblies.

**Comment by 0x900x90** [comment]
Modern builds does not contain dlls. As you can see there is Il2CppData folder inside unityweb file. All il code converted into cpp.

Abour datagz. GZ shows you that it compressed. Try winzip or 7zip to uncompress it. I use Total Commander plugin for this.

**Comment by USQREN** [comment]
> Modern builds does not contain dlls. As you can see there is Il2CppData folder inside unityweb file. All il code converted into cpp.
> 
> Abour datagz. GZ shows you that it compressed. Try winzip or 7zip to uncompress it. I use Total Commander plugin for this.

DevXUnityUnpacker software can show scripts somehow. I am looking for software that can reset Assembly-CSharp.dll (to show classes and methods). Similarities of software il2cppdumper.

**Comment by USQREN** [comment]
And one more question. Is it possible to pack back the unpacked unityweb build ?

**Comment by Perfare** [comment]
Il2CppDumper supports wasm, the wasm.code.unityweb file should be compressed by gzip or brotli, just unzip it. Then load the wasm file with Il2CppDumper to get the dummy dll.

**Comment by USQREN** [comment]
> Il2CppDumper supports wasm, the wasm.code.unityweb file should be compressed by gzip, just unzip it. Then load the wasm file with Il2CppDumper to get the dummy dll.

Your software requires GameAssembly lib

**Comment by Perfare** [comment]
@USQREN Sorry I don’t understand what you’re talking about, I wrote in the readme very clearly about the format supported by Il2CppDumper.
https://github.com/Perfare/Il2CppDumper#features
> Complete DLL restore (except code), can be used to extract MonoBehaviour and MonoScript
Supports ELF, ELF64, Mach-O, PE, NSO and WASM format

**Comment by USQREN** [comment]
@Perfare
have only global metadata in my hands

**Comment by Perfare** [comment]
@USQREN This is your problem, a webgl game will contain two files
<project_name>.data.unityweb <- contains global-metadata.dat
<project_name>.wasm.code.unityweb <- webassembly, compressed by gzip or brotli, can be confirmed by header information
You only need to unzip the global-metadata.dat and webassembly, and load it with Il2CppDumper.

**Comment by USQREN** [comment]
@Perfare Can I give you a Build.wasm.code.unityweb file to unpack? I can't unpack it at all.

**Comment by USQREN** [comment]
@Perfare Your software gives an error.

**Comment by Perfare** [comment]
@USQREN Please submit in Il2CppDumper's issue.

**Comment by USQREN** [comment]
@Perfare

Maybe a jamb on my part. I did as you said. Unpacked wasm.code.unityweb. I dropped it into your ilcppdumper along with global-metadata.dat and got an error.
