### ISSUE TITLE
Some Blendshapes/Shapekeys not Exporting correctly

### ISSUE THREAD

**Issue by UnariVR** [Perfare/UnityStudio#638]
![547ff96908e079968523bfb989ba5a3c](https://user-images.githubusercontent.com/64662984/97657755-07bdae80-1a41-11eb-92dd-c9d826a068f8.jpg)

From the game: Little witch Nobeta (demo)
Although this isn't the only game that has had this issue; "Superdimensional" is another example.

**Comment by Perfare** [comment]
This problem should be fixed now.
