### ISSUE TITLE
读取整个文件夹提示应用程序发生了未经处理的异常

### ISSUE THREAD

**Issue by tndwelcome** [Perfare/UnityStudio#64]
发现有游戏，0.7.0 单独读取文件没问题，整个文件夹的文件全选了也能读
但如果用读取文件夹的选项，0.7.0没反应，0.6.6是直接报错
0.6.6没试直接读文件，因为没有具体的后缀名，我自己也不知道应该改成什么好_(:з」∠)_
32位win7，64位win7，64位win10点文件夹都一样会报错
（win10里0.7.0打开没反应，可能是升级后遗症(⊙﹏⊙)b）

目前只发现了这一例，不知道是不是游戏本身的问题，下面是32位win7上0.6.6的报错信息

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: “1”的值对于“Value”无效。“Value”应介于 'minimum' 和 'maximum' 之间。
参数名: Value
   在 System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   在 Unity_Studio.UnityStudioForm.<>c__DisplayClass67_0.<SetProgressBarValue>b__0()

************** 已加载的程序集 **************
mscorlib
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Unity Studio
    程序集版本: 0.6.6.0
    Win32 版本: 0.6.6.0
    基本代码: file:///F:/Unity%20Studio/Unity%20Studio.exe
----------------------------------------
System.Windows.Forms
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408 built by: FX451RTMGREL
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Extensions
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.18408
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 built by: RTMRel
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本: 4.0.0.0
    Win32 版本: 4.0.30319.1 (RTMRel.030319-0100)
    基本代码: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by Perfare** [comment]
Load folder只能载入特定后缀的assets文件
