### ISSUE TITLE
SMT Nocturn HD Remaster: Model import and Blendshape issue

### ISSUE THREAD

**Issue by Retrodice** [Perfare/UnityStudio#640]
It appares that some of the assest don't extract correctly/Import into blender and there blendshapes/morphtargets are mostly broken. 
![unknown](https://user-images.githubusercontent.com/53626151/97784154-5f206380-1b94-11eb-9f8e-8a17fbd30a8b.png)
I have a sample file that has the main models that have this issues on a drive, if you could look into what the possible issue is I would be ever so greatful 

[https://drive.google.com/file/d/1gNEYwQtXTIi-oX55tJriGBGlYlYVQINl/view?usp=sharing](url)

**Comment by Perfare** [comment]
Sorry to reply to you so late, the sharing link seems to have expired, please re-upload if possible.

**Comment by Retrodice** [comment]
Oh yeah sure I'm a reupload it since I had to do some cleaning 
https://drive.google.com/file/d/1hQHnhZoWrLEHVcZUrkygFRrhkrk92QLD/view?usp=sharing
    On Thursday, 14 January 2021, 19:58:42 GMT, Perfare <notifications@github.com> wrote:  
 
 


Sorry to reply to you so late, the sharing link seems to have expired, please re-upload if possible.

**Comment by Perfare** [comment]
Sorry to reply you so late, this problem should have been fixed.
