### ISSUE TITLE
Program doesn't recognize new AssetBundle 

### ISSUE THREAD

**Issue by JosephTico** [Perfare/UnityStudio#641]
Greetings.

I'm trying to extract the contents of a Pokémon game, but seems like Asset Studio isn't able to read newer AssetBundles, while it was able to read older bundles. In this case, the only content of the bundles is a Texture2D.

Here are some sample files:

This one can be read successfully:
https://anonfiles.com/d7839al3p2/cap0199_f01_s0_unity3d

This one can't be opened by Asset Studio:
https://anonfiles.com/N88499l7p0/cap0199_f01_s0_r_unity3d

Quickly glancing through the file it seems the basic structure seems unchanged, but I don't really know what's different about the newer file.

**Comment by Perfare** [comment]
I'm sorry to reply you so late, because the file is no longer valid, I don't know the specific reason. But I guess this is usually caused by the new version of the game encrypting the AssetBundle.
