### ISSUE TITLE
crashing whlile opening a database file

### ISSUE THREAD

**Issue by Rebirth898** [Perfare/UnityStudio#644]
so i tried to open a database file from a unity game and it crashed

System.OutOfMemoryException: Die Arraydimensionen haben den unterstützten Bereich überschritten.
   bei System.Collections.Generic.List`1.set_Capacity(Int32 value)
   bei System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   bei System.Collections.Generic.List`1.Add(T item)
   bei AssetStudioGUI.Studio.BuildAssetData() in C:\projects\assetstudio\AssetStudioGUI\Studio.cs:Zeile 203.
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AssetStudioGUI.AssetStudioGUIForm.<BuildAssetStructures>d__52.MoveNext() in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:Zeile 194.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Perfare** [comment]
Are you using a 32-bit system? Due to the memory limitations of 32-bit systems, memory overflow is very common.
