### ISSUE TITLE
Loading png.v files

### ISSUE THREAD

**Issue by AciesGecko** [Perfare/UnityStudio#647]
I found some files AssetStudio can't open, they're labeled as xxx.png and then xxx.png.v and they don't load, here's an example, if someone could guide me in the right direction
[pngs.zip](https://github.com/Perfare/AssetStudio/files/5512760/pngs.zip)

**Comment by piratesephiroth** [comment]
That png file isn't a png image. Or if it is one, it's compressed/encoded/encrypted.
The .v file contains only a timestamp

**Comment by AciesGecko** [comment]
Thank you for the reply, I have no idea how could I decrypt it, I also took a look at the hexadecimal (I'm a noob at this and don't understand much) and it doesn't have the png header, I tried replacing it to no avail, I don't know what else can be done or who could help

**Comment by piratesephiroth** [comment]
someone has to analyze the game's code to figure it out
