### ISSUE TITLE
大数量的ab文件加载卡住

### ISSUE THREAD

**Issue by zhouhang95** [Perfare/UnityStudio#648]
我尝试解开诛仙新世界的包
12313个ab包，共1.3G
然而在底栏read assets时卡住

我不是unity/c#程序员 对这套工具链不熟

能否简要叙述一下加载的流程
特别是构建索引的地方
我对照源码 看看有没有可以优化的地方

**Comment by zhouhang95** [comment]
我把这1w多个文件 分成若干个文件夹 都能打开
但ab包似乎允许跨包的引用 导致无法正确的找到对应的资源

**Comment by bobkinect98** [comment]
translation:

Loading a large number of ab files is stuck

I try to unlock the new world of Zhuxian
12313 ab packages, a total of 1.3G
However, it gets stuck when reading assets in the bottom column

I am not a unity/c# programmer and I am not familiar with this tool chain

Can you briefly describe the loading process
Especially where the index is built
I compare the source code to see if there are any areas that can be optimized

I divide these 1w files into several folders and they can all be opened
But the ab package seems to allow cross-package references, which makes it impossible to find the corresponding resources correctly.

translated via google translate
