### ISSUE TITLE
Can not extract texture2d

### ISSUE THREAD

**Issue by takaaptech** [Perfare/UnityStudio#65]
When i load folder and export all assets from game: https://play.google.com/store/apps/details?id=com.superbox.aos.starhexa
The app crash, can you take a look?
And for that kind of game, i can not find dll file to decode MonoBehaviour, do you know any way to get deocded c# file?

**Comment by Perfare** [comment]
Please upload file I will test.
I can't solve your second problem.

**Comment by takaaptech** [comment]
Hi @Perfare,
Thank so much! You can download it from here:
https://apkpure.com/star-link-hexa/com.superbox.aos.starhexa

**Comment by Perfare** [comment]
sorry, I did not meet any errors when I tested

**Comment by Perfare** [comment]
Have you installed the requirements software ?

**Comment by takaaptech** [comment]
Hi @Perfare ,
After recheck and install 
Microsoft Visual C++ 2013 Redistributable
Microsoft Visual C++ 2015 Redistributable

The program run smooth! Thank so much!
Anyway, is there any way to extract c# from this kind of game?
It is easy if there is .dll file inside apk file. This apk does not include any dll file
Thank so much

**Comment by Perfare** [comment]
this app compiled with IL2CPP, there is no way to extract c# code
