### ISSUE TITLE
The program eats up a huge amount of ram.

### ISSUE THREAD

**Issue by MARK2580** [Perfare/UnityStudio#654]
Explain why your program uses such a huge amount of RAM? For example, I open a game that weighs about 3 gigabytes, and the program takes about 18 gigabytes, where is the logic? Fix memory leaks.
![5fuLS5xoO1](https://user-images.githubusercontent.com/11617079/100395404-d6d99500-3051-11eb-926b-9c649aa0cdd5.jpg)

**Comment by Perfare** [comment]
#581
