### ISSUE TITLE
Index was outside the bounds of the array - Gundam Battle

### ISSUE THREAD

**Issue by 09williamsad** [Perfare/UnityStudio#659]
Game: Gundam Battle CN
ID: com.kingnet.gundam.mg.normal
Game Version: v3.6.0(300)-20201102151204 (or higher)
Unity Version: 5.x.x 2019.4.13f1c1
Game files: https://mega.nz/file/eb4wEI6b#aBTxenfitTNgvkR28aKif4llYcKHm857eN1-o7psVc8

At the "Building asset list..." stage the following error in the attached text file occurs.
Files do not appear to be encrypted.
[error.txt](https://github.com/Perfare/AssetStudio/files/5649134/error.txt)

**Comment by Perfare** [comment]
Please upload the source file to me instead of the error message.

**Comment by 09williamsad** [comment]
I do not know which file is the cause, so I uploaded the all the games files.
"Game files: https://mega.nz/file/eb4wEI6b#aBTxenfitTNgvkR28aKif4llYcKHm857eN1-o7psVc8"
