### ISSUE TITLE
suggestion: allow ability to view as fbx and export as fbx

### ISSUE THREAD

**Issue by Wunder-Wulfe** [Perfare/UnityStudio#662]
a lot of the objects ive found have vertex color groups and i am unable to preserve them with obj export

**Comment by 09williamsad** [comment]
![export](https://user-images.githubusercontent.com/23011550/103219771-88e8d300-4916-11eb-8ee8-6226b353bf54.png)
Use the export options in the "Model" tab.
You can tick entities in the "Scene Hierarchy" for individual exports.
