### ISSUE TITLE
MonoBehaviour files on Switch games

### ISSUE THREAD

**Issue by JauCR** [Perfare/UnityStudio#663]
Hey, I'm trying to decrypt a Switch game, and I don't know what to do with the MonoBehaviour files since the game doesn't have an Assembly file. How can I extract those MonoBehaviour files?

**Comment by Perfare** [comment]
Switch games also use il2cpp, https://github.com/Perfare/AssetStudio#for-il2cpp
Use Il2CppDumper to load the nso file.
