### ISSUE TITLE
Huge memory/RAM issue when opening game assets

### ISSUE THREAD

**Issue by ghost** [Perfare/UnityStudio#664]
I'm aiming to open and extract assets from this game: https://ofihombre.itch.io/sugar-rush-superraceway

It has almost 5gb sized and this program has a huge issue to be able to even open it just to see files (i'm not including about exporting them): it gets stuck for hours and nothing else.

It also goes with RAM consumption up to almost 100% (my PC has 16gb of RAM)and if i use any other program, PC freezes and i'm forced to fully/hard restart it when this occurs.

I'm using v0.15.24 of it.

When possible, fix/solve this issue.

**Comment by Ofihombre77** [comment]
Hi Machow8, I'm Ofihombre. You want to extract the assets from Sugar Rush Superraceway, but you can't because of ram problems?
Don't worry, I have a pack of some assets (Click on the Drive link): [https://drive.google.com/file/d/137wwW1cm4okEUYPhInXUsQ9fpZEcA0Dp/view?usp=sharing](url)

**Comment by ghost** [comment]
This will help until this ram issue is solved, Ofihombre.

Thx for this!

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#load-assetsassetbundles
#581

**Comment by ghost** [comment]
None ot 'Extract file' and 'File-Extract folder' options worked for this game's url i showed here in first message.

Nothing shows up and there is a line with 'Finished extracting 0 files' text on right of progress bar on south of program' screen.

I made it load the root, Sugar Rush Superraceway v1.2_Data and other folders/files of this game and this still occurs.

I'm using v0.15.24 of it.
