### ISSUE TITLE
android mesh

### ISSUE THREAD

**Issue by DemonRem** [Perfare/UnityStudio#665]
mesh not exist on the android version from some reason,
its only show texture2d and i can confirm the game has a models

**Comment by KiruyaMomochi** [comment]
Can you upload the asset file?

**Comment by DemonRem** [comment]
https://f2h.io/l4pl2hhc55lo

**Comment by KiruyaMomochi** [comment]
Is these the mesh you're trying to find?
![image](https://user-images.githubusercontent.com/65301509/103175967-21e10500-48a9-11eb-9a27-47ee79f33f9e.png)
If yes, then the program works correctly for me. Make sure you're using the latest version.

**Comment by DemonRem** [comment]
maybe becuse the charactrers are live2d base then its only textures and not model

**Comment by Perfare** [comment]
I did not find any errors in the files you provided, all files can be loaded normally.
