### ISSUE TITLE
Cannot open include file: xxx: No such file or directory	

### ISSUE THREAD

**Issue by AndnixSH** [Perfare/UnityStudio#666]
I'm trying to compile it myself to see if the bug i got has been fixed, but i have a problem. some headers are missing
I don't get it because i'm using latest VS2019, have c++ and sdk installed and have pointed to correct location of FBX SDK 2020.0.1 VS2017

What i'm missing there?

![image](https://user-images.githubusercontent.com/40742924/102932790-3ab07b80-44a1-11eb-8176-91bc46b65b9f.png)

**Comment by Perfare** [comment]
I'm sorry I can't solve your problem, it seems to be a problem with your VS settings.
