### ISSUE TITLE
Exporting Animator and Animation Data Issue

### ISSUE THREAD

**Issue by Wojtazzzekkk** [Perfare/UnityStudio#668]
So I'm exporting Models from game and porting them to Blender for a long time but yesterday Asset Studio started to show me this error when I'm exporting Animator and AnimationData.

![Bez nazwy](https://user-images.githubusercontent.com/76519877/102992387-6a03ce80-451b-11eb-98ae-1eb821a0c2b6.png)

**Comment by Perfare** [comment]
Please upload the source file to me.
