### ISSUE TITLE
Cannot read and export custom vertex normals

### ISSUE THREAD

**Issue by deceptor666** [Perfare/UnityStudio#669]
love live school idol festival all stars has altered vertex normals in-game, however assetStudio didn't managed to read and exports the explicit normals properly. Hence I started to wonder whether this was a bug with the recent versions since I couldn't obtain the versions older than 0.14.x to check. Linked few samples just in case:

https://cdn.discordapp.com/attachments/745401167454142487/791833451539464232/00rj3o_0.dec
https://cdn.discordapp.com/attachments/745401167454142487/791833451631869972/00rj3o_393734.dec
https://cdn.discordapp.com/attachments/745401167454142487/791833455272394782/00imnf_0.dec

**Comment by Perfare** [comment]
By checking the file you provided, I think this problem has been fixed.
