### ISSUE TITLE
Error while read type,only be read with AssetsBundleExtractor(but need .dll)

### ISSUE THREAD

**Issue by pet345** [Perfare/UnityStudio#670]
I want to read the file about the type of Monobehaviour
But a window will pop up and ask me to choose a folder
![視窗](https://user-images.githubusercontent.com/66313068/103145382-9403fd80-4774-11eb-8259-597327b058ed.png)

Then only m_GameObject, m_Enabled, m_Script and m_Name can be seen
![缺失](https://user-images.githubusercontent.com/66313068/103145385-a847fa80-4774-11eb-8222-44ddbc253f88.png)

The message below says"Error while read type,read XXX bytes but expected XXXX bytes"
![錯誤](https://user-images.githubusercontent.com/66313068/103145388-b269f900-4774-11eb-863a-7755dd1a1201.png)

The version which I unpack is 2018.3.0f2
My AssetStudio version is 0.15.24

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#export-monobehaviour
