### ISSUE TITLE
TEXTURE2D EXPORTING ISSUE 

### ISSUE THREAD

**Issue by souravhchoursiya** [Perfare/UnityStudio#671]
I FOUND THIS ERROR EVERYTIME PLEASE FIX IT
UNITYFS HEADER
![Screenshot (845)](https://user-images.githubusercontent.com/68826118/103174160-d5380280-4885-11eb-95ff-f782e5a73bfe.png)

**Comment by KiruyaMomochi** [comment]
CAN YOU UPLOAD AN EXAMPLE FILE?
