### ISSUE TITLE
Previewable yet unexportable AudioClip

### ISSUE THREAD

**Issue by Poityu** [Perfare/UnityStudio#672]
I have encountered some AudioClips that are supposedly supported (2019 3.7f1),
can be successfully played/previewed by AssetStudio , yet cannot be exported. 
("Not extractable" mentioned in the message bar). 

It is possible that these files weren't parsed correctly, all of them have extra minutes of silence after the music/sound is over. (i.e. incorrect length)

Please use the following sample:
>>Removed due to files missing, see below.

Load it and filter down to AudioClip only, sort by size and look for the larger files.
env_ext_snow_oneshot is the smallest AudioClip that cannot be exported.
sfx_ui_animal_dialogstart_07 is the largest AudioClip that can be exported.

Versions used:
AssetStudio 0.15.24. on Win10
AssetStudio 0.14.38 on Win7

**Comment by 09williamsad** [comment]
Please include the resource file with your sample as the audio cannot previewed/loaded without it.
![image](https://user-images.githubusercontent.com/23011550/103353830-c7f75f80-4aa1-11eb-996a-767078bcde89.png)

**Comment by Poityu** [comment]
I am terribly sorry, I only tested that sample once by putting it directly outside of the PrjName_Data folder, looks like AssetStudio was smart enough to look for other dependencies within subfolders, so I did not realize a single *.assets file wasn't enough.

Here are the *.assets and *.resource file.
[2019_37f1_spl.zip](https://github.com/Perfare/AssetStudio/files/5756974/2019_37f1_spl.zip)

To avoid cluttering I've removed the earlier upload.
Again, sorry for the trouble.

**Comment by 09williamsad** [comment]
On v0.15.24 some of the 53 audio files export, It looks to be a bug with the WAV converter, as if conversion is turned off then all are exported as valid fsb files.
Here are the fsb files and them converted to ogg. 
[2019_37f1_spl raw and ogg.zip](https://github.com/Perfare/AssetStudio/files/5757235/2019_37f1_spl.raw.and.ogg.zip)

No error message is displayed on export.

**Comment by Poityu** [comment]
Hi @09williamsad,

Oh, you're right, I completely forgot about exporting as *.fsb. 

Hm, it's worth noting that older *.fsb tools (Aezay.dk, id-daemon, Luigi, all about 3~4 years old now) cannot work their magic on the files in question, but the most recent release of vgmstream did the trick. As such, I think the cause is either a bug or a newer version of *.fsb.

Kudos for the workaround!

**Comment by Agent3554** [comment]
How do you guys convert .fsb to any audio files? (.ogg to be specific)
What software or website to convert it? 
I'm trying to search for one in Google, and tried all methods, doesn't convert to audio or play the audio itself.

**Comment by 09williamsad** [comment]
> 
> 
> How do you guys convert .fsb to any audio files? (.ogg to be specific)
> What software or website to convert it?
> I'm trying to search for one in Google, and tried all methods, doesn't convert to audio or play the audio itself.

Foobar with VGMStream plugin.

**Comment by Agent3554** [comment]
> > How do you guys convert .fsb to any audio files? (.ogg to be specific)
> > What software or website to convert it?
> > I'm trying to search for one in Google, and tried all methods, doesn't convert to audio or play the audio itself.
> 
> Foobar with VGMStream plugin.

Thank you! :O
