### ISSUE TITLE
Some assets not showing

### ISSUE THREAD

**Issue by zaczac121** [Perfare/UnityStudio#673]
I've been trying to view the files of Battlestar Galactica: Deadlock, however when I load all the asset files, I have found some textures and models for ships not appearing, for example: I can see the Viper Mark II ship model and its texture file, I can also see the Viper Mark I ship model, however I can NOT see its texture file, meaning I cannot view the texture, and this is the same for several other textures in the game.

![image](https://user-images.githubusercontent.com/5975421/103190636-bb201380-48c9-11eb-8f3d-7a123e362a59.png)
And yes: I have gone through EVERY available texture file in the asset list

**Comment by 09williamsad** [comment]
Please upload the files that you think would contain the texture.

**Comment by zaczac121** [comment]
It should be in this one

[sharedassets27.zip](https://github.com/Perfare/AssetStudio/files/5759266/sharedassets27.zip)

**Comment by 09williamsad** [comment]
You need to include the asset.res file aswell.
As there are likely many files, it may be better to upload all the asset files if you can.

**Comment by zaczac121** [comment]
I can't upload everything due to the fact its 1.86GB altogether, but I can try to give you this one asset file that has the VM2 texture but not the VM1

[sharedassets27.zip](https://github.com/Perfare/AssetStudio/files/5759413/sharedassets27.zip)

**Comment by 09williamsad** [comment]
Does not look like the texture in question would be there, unless it has a different name.
Upload the asset files containing the mesh, or upload all the asset files to a cloud storage service like google drive or mega.

**Comment by zaczac121** [comment]
Here

https://drive.google.com/file/d/1Ajdpa1OpGo5wpcn_wbfaEHxUpgbtCo0n/view?usp=sharing

**Comment by 09williamsad** [comment]
That share is set to request only, you may want to change it to public.

**Comment by zaczac121** [comment]
changed

**Comment by 09williamsad** [comment]
I do not think that HS_VM1_LOD has a texture based on:
1. The material of the model in blender is called "Ghost", normally the material indicates the texture or material, in this case the closest match is a transparency shader of the same name.
2. The top level object/entity containing the mesh is called "ColonialViperMkIProjection", possibly a projection/hologram
3. Other ships with names containing "Projection" do not extract with textures.
4. This is an LOD model.
Those 4 indicate to me that this model only appears in a projection/hologram ingame, and does not have a texture.

However, I can see that you did not include the .level files in your upload, it may be that the non-LOD and textures model you are looking for is in there.

**Comment by 09williamsad** [comment]
Additionally using steamdb.info I can see that there are files in "BSG_Data/StreamingAssets"
Try loading the root/main game folder in AssetStudio instead of individual files, if you are doing this in the first place.

**Comment by zaczac121** [comment]
I was loading the entirety of the BSG_Data folder (minus whats in the 4 sub folders as they aren't asset files and one of them crashes the loader)

**Comment by zaczac121** [comment]
https://drive.google.com/file/d/1MTXb9zkZWHDtZsVJ9xKkxL3-aiaKNKLu/view?usp=sharing

Heres the levels and the rest of the files

**Comment by 09williamsad** [comment]
I have had a look at the level assets and none of them reference the viper MK1 or MK7
[ViperSquads.zip](https://github.com/Perfare/AssetStudio/files/5761338/ViperSquads.zip)
I suspect that the MK1 and 7 are not used as neither of them have textures or are referenced beyond projections.

**Comment by zaczac121** [comment]
They are used, the Mark I is the first fighter you have in the entire game, and I found their textures when I did a Ninja rip of an inspect mode of it, the textures ARE there but somehow they are not shown

**Comment by Perfare** [comment]
The error message I added in the new version. If you don’t encounter any error message during loading, it means that all assets in the file have been loaded.
