### ISSUE TITLE
PR:B4TG animations not playing with mesh

### ISSUE THREAD

**Issue by MarioSonicU** [Perfare/UnityStudio#675]
When I exported one of the models from the game with the animations, when I view it on noesis. Only the hair was animating correctly. Is there a fix for this?

(I'm using the PC version)

![twt](https://user-images.githubusercontent.com/51203488/103435462-bff00a80-4bdc-11eb-9c76-e2799e36c779.PNG)

**Comment by 09williamsad** [comment]
Most likely the animations are not automatically bound, barring some hair.
So you would have to select the animations and animator in the asset list then export the animation with the animation clips.
Also that does not look like the right skeleton.

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by MarioSonicU** [comment]
> Please upload the source file to me.

Here they are.
[s01_scorpina.zip](https://github.com/Perfare/AssetStudio/files/5818080/s01_scorpina.zip)

**Comment by Perfare** [comment]
This problem has been fixed in the new version 0.15.32.
You need to check as shown.
![QQ截图20210115105732](https://user-images.githubusercontent.com/12952226/104675466-88c34280-5720-11eb-8ef5-979ef29fb149.png)
Then use Model-Export selected objects (merge) to export.
