### ISSUE TITLE
asststudio error exporting files

### ISSUE THREAD

**Issue by lolmam** [Perfare/UnityStudio#676]
here a video i tried to extract some files from phigros game and it says error in every audio clip or image i want to extract. pls help me.

https://user-images.githubusercontent.com/69152475/103654038-0abbaa80-4f6e-11eb-9167-03092fcf3f3f.mp4

**Comment by Perfare** [comment]
Similar to #632 . I will change the image processing library recently instead of using GDI+.

**Comment by lolmam** [comment]
> Similar to #632 . I will change the image processing library recently instead of using GDI+.

so it will be in the next update?
