### ISSUE TITLE
Extracting .unity3d file with non-"UnityFS" header

### ISSUE THREAD

**Issue by Altivu** [Perfare/UnityStudio#677]
Application: [KartRider Rush+](https://play.google.com/store/apps/details?id=com.nexon.kart)

Prior to a recent update for the game, the package files could be accessed and extracted by standard means through the AssetStudio program. However, it seems like the developers have changed how the files are encoded, and now instead of all the files having a UnityFS header, they instead have an FBAU header. Attempting to access these files now simply results in 0 or 1 file being loaded, with no data returned.

I am wondering if there are any other means to accessing the files' contents, or if this is considered custom encryption and will thus not be supported. Thank you.

I have included some example files via Google Drive Links:

## Pre-Update (Works with Asset Studio)

[Example of two .unity3d files from pre-update](https://drive.google.com/drive/folders/1L7dUOQrs--hf7dqi_rH3dO2mpdsO0GNq)
[Pre-Update Hex Example (Image)](https://lh3.googleusercontent.com/YpOnWI4-83p5Tx_UWHJiy7CoNTCpx1K97TLWlUEHvrHS8zibM0pRWqLzclJTbo6nitZLU39gmOq8jQ=w1920-h923)

## Post-Update (Does not work with Asset Studio)

[Example of two .unity3d files from post-update](https://drive.google.com/drive/folders/1ygFtjj9aIaLmrKnh4yO3il0WFHuDaE61)
[Post-Update Hex Example (Image)](https://lh6.googleusercontent.com/jUBkz0Q-LHcOubkBUeNc0kI9IfCcc2HFuhTMEWCfbUPdi_sVquV8IpPHuoIV93rS6zTcikR6rV-pAw=w1920-h923)

**Comment by Perfare** [comment]
Sorry, AssetStudio will not consider supporting any form of encryption or modification of Unity files.
