### ISSUE TITLE
Extracting models from Seven Deadly Sins Grandcross

### ISSUE THREAD

**Issue by NotThisJin** [Perfare/UnityStudio#678]
So with the latest updates on the JP version of Grandcross apparently you can't load all the files or they just dont appear in assetstudio. No Errors are logged ever and i also never figured out what file isnt loading.

Link to download the game:
[https://apps.qoo-app.com/en/app/7484](url)

I usually noticed that the files dont load by looking up "hero_escanor" he should have about over 10 alternative outfits.

**Comment by Alexisc0** [comment]
Yes the problem doesn't come from asset studio it's from netmarble.

**Comment by LordKiriYT** [comment]
I hope this gets fixed
