### ISSUE TITLE
Error "stackhash_0a9e" opening 3d model.

### ISSUE THREAD

**Issue by SerPon4ik** [Perfare/UnityStudio#679]
I am using the latest version of the application, the problem is that when you click on the left or right mouse button on the mesh component, the program exits with the error "stackhash_0a9e"
![image](https://user-images.githubusercontent.com/51405064/104213524-71960380-5447-11eb-89c4-c62fb9cb07bf.png)
![image](https://user-images.githubusercontent.com/51405064/104213640-94c0b300-5447-11eb-8050-cc54d7166815.png)

the program crashes only when you open "mesh" when you open another, everything is fine (as you can see on the screenshots)

**Comment by Perfare** [comment]
Sorry, I think this is due to your operating system or hardware, the error cannot be reproduced, I cannot fix it.
