### ISSUE TITLE
When release the new version ?

### ISSUE THREAD

**Issue by tanakasama** [Perfare/UnityStudio#68]
Hi perfare !

When you will release the new version of this one ?

Thanks in advanced.

**Comment by Perfare** [comment]
you can download the latest build version ![Build status](https://ci.appveyor.com/api/projects/status/amw5n3607g45n2v0?svg=true)

**Comment by tanakasama** [comment]
I known where i can download the latest build version. But after v0.7.0, i see have many bug fix at the commit. So i want to known when you will build the next latest version.

**Comment by Perfare** [comment]
I don't know. I have something to do and I need some time to test

**Comment by tanakasama** [comment]
I think you should release to alpha version to people can test it instead of you test it.

**Comment by Tosyk** [comment]
tanakasama, I think Perfare to decide when to release new version to public, until then we have to patiently wait.

**Comment by Perfare** [comment]
I finally released the new version today...
