### ISSUE TITLE
Error when exporting Texture2D file: "Illegal characters in path"

### ISSUE THREAD

**Issue by JameBrer** [Perfare/UnityStudio#680]
![27fc08bb959b89ce2f7dc92884ad90d3](https://user-images.githubusercontent.com/77424995/104541046-caec6700-55ee-11eb-9064-3389a81bc12a.png)
This happens on mostly every texture. I'd upload the file but it's wayyy too big for any service to be uploaded

**Comment by bkslasher** [comment]
Happens to me as well for all Texture2D, built using Unity 2020.2.1.

**Comment by Perfare** [comment]
@JameBrer @bkslasher Please try the new version, Unity 2020.2 is already supported, if you still have problems, please upload the source file to me.

**Comment by bkslasher** [comment]
> @JameBrer @bkslasher Please try the new version, Unity 2020.2 is already supported, if you still have problems, please upload the source file to me.

New version is working great. Thanks.
