### ISSUE TITLE
Import of Replace Textures

### ISSUE THREAD

**Issue by NBAPJ** [Perfare/UnityStudio#681]
Can this program replace or import textures?

**Comment by DreaDream** [comment]
did you find anything out?

**Comment by NBAPJ** [comment]
No I haven't found anything out.  No one ever responded.

**Comment by DreaDream** [comment]
> No I haven't found anything out. No one ever responded.

you do lol, and quickly

**Comment by Perfare** [comment]
If you need to edit assets, please use UABE or UnityPy .
