### ISSUE TITLE
how to read unity text asset?

### ISSUE THREAD

**Issue by mani901** [Perfare/UnityStudio#684]
![Screenshot (17)](https://user-images.githubusercontent.com/77674233/105033389-dcfc5880-5a79-11eb-806e-d99f344598ea.png)
how to read this unity text asset in normal text

**Comment by LolHacksRule** [comment]
Text is not plain, file is possibly binary. You're gonna have to extract it first.

**Comment by mani901** [comment]
> Text is not plain, file is possibly binary. You're gonna have to extract it first.

I have extract this but it shows same language unreadable anyway to convert it into normal text?

**Comment by KiruyaMomochi** [comment]
Hard to say. There might be some way, but decode this binary message is not AssetStudio's task. When a file is *binary*, it may even not contain any text. You can ask people who have extracted the same before, they may have idea.
