### ISSUE TITLE
Read Animation Error

### ISSUE THREAD

**Issue by R3Exia** [Perfare/UnityStudio#685]
Hello,I read the 2017 version of the bundle, and an error was reported when loading AnimationClip. The array dimension exceeded the supported range.

[05734174_2881320.zip](https://github.com/Perfare/AssetStudio/files/5841237/05734174_2881320.zip)

![image](https://user-images.githubusercontent.com/17568285/105152055-b0ac0f00-5b41-11eb-88f6-c76900fa3229.png)

**Comment by Perfare** [comment]
The structure of AnimationClip has changed, which may be due to patch version or modification by the developer. I’m sorry that this will not be fixed.
