### ISSUE TITLE
Hanging after opening another game assets directory in a single session

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/UnityStudio#686]
When opening a game assets directory, the program loads its content fine almost always but when opening another one in the same session, the program eventually hangs after loading content at "Building tree structure" and does not respond. I have encountered this many times even before this update. For example, loading a big directory (412MB) then loading a smaller directory (288MB) causes the program to hang, the same goes for vice versa. Can this please be fixed if possible?
![image](https://user-images.githubusercontent.com/30186527/105445994-11ad1300-5c26-11eb-9a7b-99e0b46b02c5.png)

**Comment by Perfare** [comment]
According to my research, this is a winform problem. I can’t find a solution. I can only suggest that you reopen AssetStudio when loading a new file.
