### ISSUE TITLE
.NET Framework needed is not supported

### ISSUE THREAD

**Issue by AnhQuoc533** [Perfare/UnityStudio#688]
The latest version requires .NET Framework 4.7.2 but when I tried to download it, my operater system does not support this version of .NET Framework and eventually, I cannot use the tool.

**Comment by KiruyaMomochi** [comment]
What version of Windows are you using?

**Comment by AnhQuoc533** [comment]
Windows 10, build 10240

**Comment by KiruyaMomochi** [comment]
Can you have a look at <https://stackoverflow.com/questions/54112889/why-is-net-framework-4-7-2-not-supported-on-this-operating-system-windows-1>

**Comment by AnhQuoc533** [comment]
Sorry but I tried the method you showed and the methods I found on YouTube, all falied.

**Comment by AnhQuoc533** [comment]
The latest version that I can download is 4.6.2

**Comment by piratesephiroth** [comment]
> 
> 
> The latest version that I can download is 4.6.2

so 4.6.2 installs sucessfully but 4.7 doesn't?

**Comment by AnhQuoc533** [comment]
Yes, as I said before, my computer doesn't support that version of .NET Framework.

**Comment by piratesephiroth** [comment]
Well that is weird but it's a problem with your Windows installation.

**Comment by AnhQuoc533** [comment]
No, I said it, my operater system does not support this version of .NET Framework.

**Comment by AnhQuoc533** [comment]
Can I get older version of AssetStudio which doesn't require .NET Framework 4.7.2?

**Comment by piratesephiroth** [comment]
See if those two NET Framework options are enabled in Control Panel -> Programs and Features -> Turn Windows Features On or Off

![image](https://user-images.githubusercontent.com/10672233/106890916-c3d5e780-66c8-11eb-93b3-9f94c4eb3587.png)

If even that is already set then you have to update your Windows.

**Comment by AnhQuoc533** [comment]
> See if those two NET Framework options are enabled in Control Panel -> Programs and Features -> Turn Windows Features On or Off
> 
> ![image](https://user-images.githubusercontent.com/10672233/106890916-c3d5e780-66c8-11eb-93b3-9f94c4eb3587.png)
> 
> If even that is already set then you have to update your Windows.

I have already tried those things you told me and did not succeed.

**Comment by piratesephiroth** [comment]
Have you tried the solutions mentioned here?
(apparently it doesn't work for the Enterprise version)

https://answers.microsoft.com/en-us/windows/forum/windows_10-update-winpc/windows-10-stuck-on-build-10240/4777a37e-4630-4c4d-8fd9-868494c04db0?page=1

**Comment by AnhQuoc533** [comment]
> Have you tried the solutions mentioned here?
> (apparently it doesn't work for the Enterprise version)
> 
> https://answers.microsoft.com/en-us/windows/forum/windows_10-update-winpc/windows-10-stuck-on-build-10240/4777a37e-4630-4c4d-8fd9-868494c04db0?page=1

I tried to update my PC even long time ago and failed. Since this occured, I tried to give it a shot and failed, again.
I was loading the update, then it said the process failed and restart, I did it like 3 times and it did nothing to help.

**Comment by piratesephiroth** [comment]
Well you probably have to install a new version of Windows then.
Eventually you'll find another .NET app that fails to run so it's better to solve the problem directly.

**Comment by AnhQuoc533** [comment]
I told you, didn;t you see, my PC failed to update. I hate Windows Update and that failure even makes me hate it more.

**Comment by AnhQuoc533** [comment]
I just want older version of AssetStudio.

**Comment by AnhQuoc533** [comment]
Well.
