### ISSUE TITLE
Mesh skin problems

### ISSUE THREAD

**Issue by REDxEYE** [Perfare/UnityStudio#689]
Hello, I've encountered an issue with skin export, an example can be seen bellow
![image](https://user-images.githubusercontent.com/17544576/106400886-1d70b480-6432-11eb-8c20-07ab5cf165f3.png)
I found at least 2 games where this issue can be seen

Link to one of the games [NSFW/Furry] https://drive.google.com/file/d/1FDlSz2f7y7KtFndfUdfbgesg9I0mKLZj/view
Path to model in question: level5 -> __unit_woman.000.horse.000 ELERA

**Comment by joeyeroq** [comment]
Is there any update on this issue where the vertices at the center of many joints are not weighted?

**Comment by REDxEYE** [comment]
Okay, I ended up fixing it myself. Here is a version with my fix.
[AssetStudio_weights_fix.zip](https://github.com/Perfare/AssetStudio/files/6291558/AssetStudio_weights_fix.zip)
The issue was in weight channel parsing, AssetStudio was interpreting buffer as an array of float16, while it actually was an array of fixed point floats (uint16 divided by 65535.0f)

**Comment by REDxEYE** [comment]
@Perfare can you please take a look at this patch?
(git didn't let to upload patch file direct, so I zipped it up)
[weight_fix.zip](https://github.com/Perfare/AssetStudio/files/6291587/weight_fix.zip)

**Comment by Perfare** [comment]
It uses a relatively rare 16-bit normalized Integer, I will rewrite that part of the code to deal with all situations, I will close this question when finished.
In addition, can you re-upload the file for me to test ?

**Comment by REDxEYE** [comment]
https://drive.google.com/file/d/147gvu2F5BQ6OZ_JFzClDqp52eHSzcgkF/view?usp=sharing

**Comment by Perfare** [comment]
@REDxEYE Got it, thanks.

**Comment by Perfare** [comment]
It should be correct now.
