### ISSUE TITLE
Exporting issues with textures

### ISSUE THREAD

**Issue by OPAmqericaHPE** [Perfare/UnityStudio#691]
Hello, I am having lots of problems with exporting textures from the game, **Monstrum 2**. I have a GIF below that demonstrates what the problem is and what is going on (I'm not sure why. I'm even on the latest build of Asset Studio and it still won't work)

https://gyazo.com/47e294f3c21885f0dc82e4b598590e80 - GIF

When exporting, part of the texture becomes transparent, meaning it cannot be used. It's erasing most of the texture. The only textures that work are the classic textures (the one in the gif is one of the skins for a monster in Monstrum called the **Brute**.

**Comment by REDxEYE** [comment]
Switch export texture format to TGA.
TGA support straight alpha mode (alpha stored in its own channel, without affecting others)
