### ISSUE TITLE
Cannot Access the file because it is being used by another process

### ISSUE THREAD

**Issue by Alyssciel** [Perfare/UnityStudio#692]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The process cannot access the file 'D:\Steam\steamapps\common\Library Of Ruina\LibraryOfRuina_Data\StreamingAssets\AssetBundles\character_unpacked\CAB-558f4e71bc2051aa67804a61b758ad71.resS' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at AssetStudio.ImportHelper.CheckFileType(String fileName, EndianBinaryReader& reader) in C:\projects\assetstudio\AssetStudio\ImportHelper.cs:line 68
   at AssetStudio.AssetsManager.LoadFile(String fullName) in C:\projects\assetstudio\AssetStudio\AssetsManager.cs:line 61
   at AssetStudio.AssetsManager.Load(String[] files) in C:\projects\assetstudio\AssetStudio\AssetsManager.cs:line 48
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AssetStudioGUI.AssetStudioGUIForm.<loadFolder_Click>d__48.MoveNext() in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudioGUI
    Assembly Version: 0.14.38.0
    Win32 Version: 0.14.38
    CodeBase: file:///D:/Downloads/AssetStudio-0.15.0/AssetStudio-0.15.0/Asset%20Studio%20Gui/AssetStudioGUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AssetStudioUtility
    Assembly Version: 0.14.38.0
    Win32 Version: 0.14.38
    CodeBase: file:///D:/Downloads/AssetStudio-0.15.0/AssetStudio-0.15.0/Asset%20Studio%20Gui/AssetStudioUtility.DLL
----------------------------------------
OpenTK
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///D:/Downloads/AssetStudio-0.15.0/AssetStudio-0.15.0/Asset%20Studio%20Gui/OpenTK.DLL
----------------------------------------
AssetStudio
    Assembly Version: 0.14.38.0
    Win32 Version: 0.14.38
    CodeBase: file:///D:/Downloads/AssetStudio-0.15.0/AssetStudio-0.15.0/Asset%20Studio%20Gui/AssetStudio.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
dnlib
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///D:/Downloads/AssetStudio-0.15.0/AssetStudio-0.15.0/Asset%20Studio%20Gui/dnlib.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///D:/Downloads/AssetStudio-0.15.0/AssetStudio-0.15.0/Asset%20Studio%20Gui/OpenTK.GLControl.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Perfare** [comment]
Please use the latest version.
