### ISSUE TITLE
error previewing and exporting textures

### ISSUE THREAD

**Issue by Dazegambler** [Perfare/UnityStudio#695]
![Screenshot 10_02_2021 12_26_47](https://user-images.githubusercontent.com/70617250/107531365-85926980-6b9b-11eb-894a-cdc115cf6fdd.png)
![error](https://user-images.githubusercontent.com/70617250/107531440-9a6efd00-6b9b-11eb-9908-f31c2726be76.png)

**Comment by Dazegambler** [comment]
the game uses unity 2020.2.3f

**Comment by Perfare** [comment]
Please use the latest version, if you still encounter this problem, please upload the file to me.
