### ISSUE TITLE
Extract file can not correctly parse 2019.4.16f1c1 UnityFS asset files

### ISSUE THREAD

**Issue by yufeilin** [Perfare/UnityStudio#698]
I have a UnityFS asset file and I want to extract sprites in it. As before, I tried to extract them by "Extract Folder" and got an out of memory exception. Then I checked the source code of Asset Studio and found that in the decompressed data block(after the file header), the position that was the "blocksInfoCount" is no longer the  "blocksInfoCount" but a very large integer and cause the out of memory exception(because win10 can not allocate such large memory)
Here is the asset file
[https://drive.google.com/file/d/1SyQ70LjAjkfhSTF9IFAYLkGmO0XdRlh2/view?usp=sharing](url)

and there are some info about it
Name: Atlas
Signature: UnityFS
Version: 7
unityVersion: 5.x.x
unityRevision is 2019.4.16f1c1
Size: 16167411
compressedBlocksInfoSize: 790
uncompressedBlocksInfoSize: 1713
Flags: 579
0x80 == 0
LZ4 or LZ4HC

Thanks for checking this issue

**Comment by Perfare** [comment]
I noticed that the version number has "c", it may be the encryption that is unique to the Chinese version instead of the new format.

**Comment by Asciicodeplus** [comment]
LZ4HC is a high compression variant of LZ4. LZ4HC compression results in larger compressed files than LZMA, but does not require the entire bundle to be decompressed before use.

LZ4HC compression makes it possible to load individual Assets from an Asset Bundle quickly and using less memory than LZMA compressed Asset Bundles. This compression method is not available for recompression at runtime, but LZ4 is.

**Comment by Asciicodeplus** [comment]
> 
> 
> I noticed that the version number has "c", it may be the encryption that is unique to the Chinese version instead of the new format.

https://docs.unity3d.com/2018.3/Documentation/ScriptReference/CompressionType.Lz4HC.html

LZ4HC is a high compression variant of LZ4. LZ4HC compression results in larger compressed files than LZMA, but does not require the entire bundle to be decompressed before use.

LZ4HC compression makes it possible to load individual Assets from an Asset Bundle quickly and using less memory than LZMA compressed Asset Bundles. This compression method is not available for recompression at runtime, but LZ4 is.

https://docs.unity3d.com/2017.2/Documentation/ScriptReference/BuildOptions.CompressWithLz4HC.html
