### ISSUE TITLE
MonoBehavior is incomplete.

### ISSUE THREAD

**Issue by wafflethings** [Perfare/UnityStudio#699]
I've been ripping the assets from Fall Guys, and the DevX decompiler shows more information in the MonoBehaviours that AssetStudio. 
For example:
DevX - ```--- !u!114 &1790416459043180960
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 299150151, guid: 985e452c78d6d95766d98f639e2ec0ed, type: 3}
  m_Name: "Colour_Crownrank_01"
  m_EditorClassIdentifier: 
  _itemId: "colour_crownrank_001"
  _menuDisplaySprite: {fileID: 0}
  primaryColour: {r: 0.04970657, g: 0.3005438, b: 0.07036011, a: 1}
  secondaryColour: {r: 1.135301, g: 0.5349588, b: 0, a: 1}
  primarySmoothness: 0.3
  secondarySmoothness: 0.6
  primaryMetallic: 0.2
  secondaryMetallic: 0.7
  rimColor: {r: 0.2705882, g: 0.4705883, b: 0.2392157, a: 0}
  rimPower: 1.3```

AssetStudio - `{
  "m_GameObject": {
    "m_FileID": 0,
    "m_PathID": 0
  },
  "m_Enabled": 1,
  "m_Script": {
    "m_FileID": 1,
    "m_PathID": 3394
  },
  "m_Name": "Colour_Crownrank_01"
}`

**Comment by wafflethings** [comment]
Github ruined the formatting: 
![image](https://user-images.githubusercontent.com/60797216/108620589-fbf95c00-7424-11eb-9a9a-890d1877e379.png) this is DevX, and
![image](https://user-images.githubusercontent.com/60797216/108620596-061b5a80-7425-11eb-93a6-5bcfbe2a2f34.png)
this is AssetStudio.

**Comment by Perfare** [comment]
Please check the [README](https://github.com/Perfare/AssetStudio/blob/master/README.md#export-monobehaviour) to confirm that you have loaded the assembly directory.

**Comment by wafflethings** [comment]
That was correct, I was confused on what Assembly was. Thanks.
