### ISSUE TITLE
Split logic codes from UI classes

### ISSUE THREAD

**Issue by hozuki** [Perfare/UnityStudio#7]
As you can see, the `UnityStudioForm` class is growing into a god object. Reading it is VERY hard since it has over 3000 lines of code and is not well organized. I think you can consider to separate the core functionalities (i.e. data IO & decoding/encoding) to form a clearer code structure.

**Comment by Perfare** [comment]
hmm... I think it's too hard for me...

**Comment by ordigdug** [comment]
I submitted a pull-request in attempts to re-organize the code, I believe making it easier to wrap your head around.

**Comment by ordigdug** [comment]
I believe this issue can be closed.

**Comment by Perfare** [comment]
@ordigdug ok
