### ISSUE TITLE
Unable to export Sprite file type

### ISSUE THREAD

**Issue by RixisPlayLV** [Perfare/UnityStudio#701]
Whenever i try to export a sprite file type, it simply gives me this error:
![ea07f28494fcf25761b8ea715a8b64b3](https://user-images.githubusercontent.com/79756845/109391208-958da580-791e-11eb-8301-5b40acc3a47d.png)

**Comment by Perfare** [comment]
Please upload the source file, and what is the version of AssetStudio you are using?
