### ISSUE TITLE
Issue with exporting Sprites and Textures

### ISSUE THREAD

**Issue by Khruter** [Perfare/UnityStudio#702]
Hello. Lately, I have been experiencing issues exporting sprites and textures. This issues haven't been present up until a month ago. When I export Sprites/Textures a majority of them end up appearing corrupted, or heavily pixelated. A few examples of what I mean can be seen below. 

For context, the game I have been extracting these files from is called "Library of Ruina". And it appears out of the few I have observed extracting files similarly to me, I'm currently the only experiencing this issue. 

I have uninstalled and reinstalled this program, restarting my computer, re-extracting, and clearing space on my computer. Despite all this the issue has persisted. If there's anything I can do to fix this issue or if I need to wait for a newer version of this program to be released then please let me know.
Any help and information is appreciated.
![Cane5 #312622](https://user-images.githubusercontent.com/79773357/109405161-a567b280-793b-11eb-91da-661a84b81124.png)

![EGO_Wolf_Polymorph_Hit #348418](https://user-images.githubusercontent.com/79773357/109405162-a6004900-793b-11eb-820c-4ed822a03217.png)

![EGO_WhiteNight_Guard](https://user-images.githubusercontent.com/79773357/109405163-a6004900-793b-11eb-8291-6294653c3fad.png)

**Comment by Perfare** [comment]
Please upload the source file to me, I will check if it is the problem with AssetStudio.

**Comment by Khruter** [comment]
> Please upload the source file to me, I will check if it is the problem with AssetStudio.

Thank you! Hopefully these are the correct files. If they happen to not be, then I apologize. 
https://drive.google.com/file/d/1D05WvTDJQRco1Tj84Q4KWc-86H6Eu07O/view?usp=sharing

**Comment by Perfare** [comment]
I have modified the library used by the image processing, and tested the files you provided, it looks like everything is fine.
you can download the latest build version from here https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
