### ISSUE TITLE
问题请教大佬

### ISSUE THREAD

**Issue by ChenLauter** [Perfare/UnityStudio#703]
File-Extract file可以把bundlefile解压成多个资源文件，可以实现把这些资源文件恢复合成一个bundlefile吗？

**Comment by zhukunqian** [comment]
是可以。
bundlefile格式及解压过程都有，只要反向操作一遍就可以了。工具中如果没有提供对应的功能，就需要自己写些代码来实现这个功能。

**Comment by ChenLauter** [comment]
问题解决
