### ISSUE TITLE
FBX files appear to be empty

### ISSUE THREAD

**Issue by iacobDelia** [Perfare/UnityStudio#704]
Hello! I'm trying to get some models from a game. Exporting models from the asset list works as intended, but they're unorganized and I don't know which files are supposed to match each other. So I tried selecting things in the scene hierarchy then exporting them, but all the fbx files appear to be empty when I open them.  Here's the file I'm trying to extract it from: https://drive.google.com/drive/folders/1NZLtBcModdQrt5UbjHxG8IZfhAbLvhm-?usp=sharing

Thanks in advance.

**Comment by Eleiyas** [comment]
Seems like the issue I had was fixed recently, so I'm going to clone and build from source.

**Comment by Perfare** [comment]
You can right-click on the mesh "Go to scene hierarchy" to jump. If the selected object is not bound to the mesh, naturally the fbx file will be empty.
