### ISSUE TITLE
Can't extract assets from UnityFS 5.x.x 2019.4.4f1

### ISSUE THREAD

**Issue by jmakxd** [Perfare/UnityStudio#706]
Hello! I was wondering whether you can add the capability into AssetStudio in extracting assets from UnityFS 5.x.x 2019.4.4f1 Unity compiled games? There is a game that uses this specific version when tried to be read with Notepad, but AssetStudio couldn't even load the game files. Can you please possibly look into this issue? Thank you for doing this!

**Comment by 09williamsad** [comment]
What is the game and I suggest you upload some samples.

**Comment by jmakxd** [comment]
Orzmic, here is the APK: https://drive.google.com/file/d/1_oldPScATybunRXe991gdKOhqNbDA5V5/view?usp=drivesdk

**Comment by Perfare** [comment]
The bundle file in the assets directory should be encrypted.
