### ISSUE TITLE
Attempting to export an Animator who's animation clips failed to load throws an Exception

### ISSUE THREAD

**Issue by Yoraiz0r** [Perfare/UnityStudio#707]
I've attempted to export some animator and its animation clips, for study purposes, when I've hit a rather unfortunate exception.
I cloned the repository to try and diagnose what's been going on with it, and found that `AssetStudio.ModelConverter.ReadCurveData` may fail after `m_ClipBindingConstant.FindBinding`, because it may return null, and there's no handling for that.

Looking deeper into the issue, I've looked at `AssetStudio.AnimationClip`s constructor, it appears to be crashing inside `new AnimationClipBindingConstant(reader);` due to reading an invalid size.

`m_SampleRate = reader.ReadSingle();` reads 60, so I assume that up to that point, the animations are still reading properly, but I haven't figured out where the issue is, exactly, yet.

[Here's a test case zip](https://www.mediafire.com/file/gw8vunzjobs5aew/Test_Case.zip/file)
Attempting to load the folder, or `1004171649_3419760498.unity3d` specifically, should yield a number of these failures.

Any help to figure this out would be highly appreciated - I'd love to see the animations exported properly.

**Comment by Perfare** [comment]
The structure of AnimationClip has been modified and cannot be read correctly.
