### ISSUE TITLE
how to batch import?

### ISSUE THREAD

**Issue by DreaDream** [Perfare/UnityStudio#708]
how do i batch import some new files into the already opened one?

**Comment by 09williamsad** [comment]
Put the files/folders in the same folder then tell asset studio to load that folder.

**Comment by DreaDream** [comment]
then how do i export it back into its original format

**Comment by 09williamsad** [comment]
As far as I am aware there is no option in asset studio to repack files into asset bundles.
"AssetStudio is a tool for exploring, extracting and exporting assets and assetbundles."
