### ISSUE TITLE
Unable to open some AssetBundle files

### ISSUE THREAD

**Issue by zhenchao** [Perfare/UnityStudio#711]
I cannot open certain Assetbundle files from Mole's World Ver0.10.21020101T (Android)
The software did not report an error, but did not load
The header looks like unencrypted UnityFS.
I tried other software, but I couldn't open these files either.

[https://1drv.ms/u/s!ArpHBtnXvt7HxUmwh9xrjfoG50_m?e=ntrldu](url)

**Comment by flow119** [comment]
我也遇到这个问题，UnityFS里获取entryinfo_count为0

**Comment by Perfare** [comment]
File structure should be encrypted or modified.
