### ISSUE TITLE
Generic GDI+ error in System.Drawing.Image.Save [...]

### ISSUE THREAD

**Issue by Only-a-cat** [Perfare/UnityStudio#715]
"Generic GDI+ error
 in System.Drawing.Image.Save
![1](https://user-images.githubusercontent.com/79012222/113217117-caf61d80-9253-11eb-9c7d-3085887deadc.png)
(String filename, ImageCodecInfo encoder, EncoderParameters encoder Params)
 in AssetStudioGUI.Exporter.ExportTexture2D(AssetItem item, String exportPath) in C:\projects\assetstudio\AssetStudioGUI\Exporter.cs: Line 51
 in AssetStudioGUI.Studio.<>c_DisplayClass13_0.<ExportAssets>b__0(Object state) in C:\projects\assetstudio\AssetStudioGUI\Studio.cs: Line 414"

The Asset Studio gave me this error, does anyone know how to solve please ?? is giving me when I try to export in any type and any file!

**Comment by Perfare** [comment]
What version of AssetStudio are you using?

**Comment by tyramen** [comment]
I also have this exact error. I'm on v.0.15.35 .

**Comment by TheashGini** [comment]
I have the same error 😅

**Comment by Perfare** [comment]
I have modified the library used by the image processing, this problem should have been resolved, but the new version has not been officially released, you can download the latest build version from here https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
