### ISSUE TITLE
Error Reading Texture2D

### ISSUE THREAD

**Issue by Moe-Club** [Perfare/UnityStudio#718]
Game : Revelation Mobile
Sample -> [https://drive.google.com/file/d/1AprWbcNpvsJvfOHsRdagDj6Ky8WYKFPU/view?usp=sharing](url)

Error when trying to view or export :
![error](https://user-images.githubusercontent.com/34764230/114471265-8470cd80-9c1a-11eb-8129-40850927bcdd.jpg)

Expected got this :
![10004_92706_d_a_001](https://user-images.githubusercontent.com/34764230/114471327-9ce0e800-9c1a-11eb-8a63-6dae77ec61fd.png)

**Comment by Perfare** [comment]
Texture2D structure has a new custom field `m_StreamingMipmapsLayer`, you need to modify the code to add.
![20210418011056](https://user-images.githubusercontent.com/12952226/115120980-f82c2500-9fe2-11eb-9e2e-6a1694a62d35.png)
