### ISSUE TITLE
UnityFS header but cant open? (Unity 2019.4.13)

### ISSUE THREAD

**Issue by friuns2** [Perfare/UnityStudio#719]
Trying to load asset bundles from this game https://global-offensive-mobile.en.uptodown.com/android

 When I open it in notepad I see Unity FS header, but can't load it any idea why?

**Comment by friuns2** [comment]
[Android.zip](https://github.com/Perfare/AssetStudio/files/6301524/Android.zip)

**Comment by Perfare** [comment]
These files have been encrypted.
