### ISSUE TITLE
How to Build "alpha"

### ISSUE THREAD

**Issue by FonzieMcCloud** [Perfare/UnityStudio#72]
hey!
I just wanted to try the extended gameobject preview from ordidug (https://github.com/ordigdug/UnityStudio) but i have somehow no real clue how to build from the source - can somebody maybe point me in the right direction what programs i need and/or where i can get a manual?

**Comment by questforboobs** [comment]
Download Visual Studio Community from here: https://www.visualstudio.com/vs/community/

Download the source, then double click the file `Unity Studio.sln` to open it in Visual Studio.

From the `Build` menu, select the `Build Solution` option.
