### ISSUE TITLE
Shader exporting - array dimensions exceeded supported range

### ISSUE THREAD

**Issue by lmrst** [Perfare/UnityStudio#720]
It seems with more the complicated shaders, the app cannot handle the preview, the shader size seems to be exceeding the Int32 you are using (the asset studio shows the shader size being 4683536).  Any chance to switch to Int64?

**Comment by Perfare** [comment]
I think there should be a structural reading problem, if possible, please upload the file to me.

**Comment by lmrst** [comment]
Thanks! Sure, for example this one

https://drive.google.com/file/d/13DdRKXZpugnK-rTeXTDcAHWLeiLzbKH_/view

it's build with 2020.3, but I can get you an apk build with 2019, with a similar problem.
