### ISSUE TITLE
Only can extact unreadable TextAsset.

### ISSUE THREAD

**Issue by ustr0aTe** [Perfare/UnityStudio#721]
Hello, Im trying to extract some assets from the following files.
However,im just getting 2 files TextAsset in each Unity3D file and some of those i was pretty sure is image or text file.
I had checked those Unity3D files that were using 2019.4.21f1, which is an official release version.
Is it a new compression that causes the problem?

[item.zip](https://github.com/Perfare/AssetStudio/files/6320321/item.zip)
thanks

**Comment by Perfare** [comment]
The programmer can store any file as a binary file in TextAsset, and you need to decrypt it or perform other operations.
