### ISSUE TITLE
Preview Texture2D error, Export GameObject error

### ISSUE THREAD

**Issue by vlalchinanya** [Perfare/UnityStudio#722]
Hi I have 2 errors in AssetStudioGUI (0.15.23)

First, after loading the game assets, I try to view the contents of Texture2D, but I get the error "The path contains invalid characters" (Screenshot 1)
Secondly, I get a similar error when exporting GameObject to .fbx format along with textures "The path contains invalid characters" (Screenshot 2)
Unity game version - 2020.2.4f1
Is there a way to solve this problem? Or could in-game assets be encrypted?

Thanks
![Screenshot_2](https://user-images.githubusercontent.com/76631545/115120545-b6858500-9fb6-11eb-9e8f-8de1aabc4b74.png)
![Screenshot_3](https://user-images.githubusercontent.com/76631545/115120548-b7b6b200-9fb6-11eb-9bcb-fae943086665.png)

**Comment by Perfare** [comment]
The version is too low, 2020.2 is only supported after 0.15.25.
