### ISSUE TITLE
Unsupported sprite.

### ISSUE THREAD

**Issue by ustr0aTe** [Perfare/UnityStudio#723]
Hello again.
Im having issues with file which can read by your program but cant preview or export.
And other files in the game are work fine. any idea?
[2KZM3O2wxN.zip](https://github.com/Perfare/AssetStudio/files/6329772/2KZM3O2wxN.zip)

**Comment by Perfare** [comment]
The file only contains Sprite, not Texture2D and SpriteAtlas, I think Sprite should be controlled by other SpriteAtlas, and Texture2D exists in other files, you need to load it together.
