### ISSUE TITLE
illegal characters in path

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Perfare/UnityStudio#725]

**Comment by umustbeloggedintododat** [comment]
woops forgot to provide description
so i'm trying to debug and fix a game because of this error
i cant seem to figure it out
im on v0.15.23
the game is called "battle car racing"
https://apkpure.com/battle-car-racing/com.F.N.kooshstudio.battlegameracing

**Comment by Perfare** [comment]
Version too old.

**Comment by umustbeloggedintododat** [comment]
how do I update it
it's the only version i can find without compile+

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio/releases
