### ISSUE TITLE
Cannot load an AssetBundle of version 2020.3.5f1c1

### ISSUE THREAD

**Issue by game-reverse** [Perfare/UnityStudio#728]
I can’t load an assetbundle which starts with UnityFS and its version is 2020.3.5f1c1. It’s in the StreamingAssets folder. But I can load the other archives like “resources.assets”. 

I don’t think it is encrypted because I didn’t find any function to decrypt in the game’s AssemblyCsharp.dll and when I use AssetStudio to load it, it creates a .resS file which is about 2.8GB but cannot load anything.

Maybe the reason is that the version of the game is too new.
Could you please update the AssetStudio to support new versions? Thank you very much!

The assetbundle which I can’t open is here, about 780MB
https://drive.google.com/file/d/1FozQtomVLlVnFZLaTpT51uEFBiksrxSY/view?usp=sharing

The download link of the game is here, about 1GB
https://drive.google.com/file/d/1WxRhPoE7mcUOFaUdE-BQg_HwYSdMSO9l/view?usp=sharing

**Comment by Perfare** [comment]
AssetStudio can now read this file. However, it should be noted that the Shader structure of this version is different from the Shader structure of the Unity f version. AssetStudio will still report an error, but just ignore it.
