### ISSUE TITLE
Failed to resolve assembly: 'system.private.corelib, version=4.0.0.0, culture=neutral, publickeytoken=7cec85d7bea7798e'

### ISSUE THREAD

**Issue by guidra-rev** [Perfare/UnityStudio#729]
I'm trying to export a MonoBehaviour asset. Since this game uses Il2Cpp, I first used [Il2CppDumper ](https://github.com/Perfare/Il2CppDumper) to generate the `DummyDll` folder. Then when I click a MonoBehaviour asset for the first time, I have a dialog asking me to select the assembly folder, so I choose the `DummyDll` folder.
Unfortunately I receive this exception 
![image](https://user-images.githubusercontent.com/57588903/116308910-64a7e080-a7a8-11eb-93ef-5635e603f242.png)

`Failed to resolve assembly: 'system.private.corelib, version=4.0.0.0, culture=neutral, publickeytoken=7cec85d7bea7798e'`

I'm not sure where it's looking for the dll, but I have many .Net Core SDK versions installed on my PC, I have the dll at this path for example : `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.4\System.Private.CoreLib.dll`

I have also tried to copy this dll inside the `DummyDll` folder, but still same issue.

-----------------------------------------------

Update; let's try debugging 

The exception is thrown on line 79
![image](https://user-images.githubusercontent.com/57588903/116600510-aad87d80-a929-11eb-835a-dc44e5afeeab.png)
The argument `typeReference` is a MonoCecil wrapper around `List<EquipmentType>` where `EquipmentType` is an Enum, from the `Assembly-Csharp.dll`
The method `IsUnityEngineObject` lives in `Unity.SerializationLogic.dll`
![image](https://user-images.githubusercontent.com/57588903/116603571-5a631f00-a92d-11eb-9076-c0c21b1049f3.png)

I've added explicit calls just before the throw to see which line throws
![image](https://user-images.githubusercontent.com/57588903/116605991-63092480-a930-11eb-928e-bdb472f6f73d.png)

It's the call to `IsSubclassOf` which throws. It's definition is
![image](https://user-images.githubusercontent.com/57588903/116606364-ea569800-a930-11eb-9e89-8ad68f96f084.png)

Let's do the same, know the thrower is `baseType.Resolve()` . 
![image](https://user-images.githubusercontent.com/57588903/116606860-9ef0b980-a931-11eb-9764-6205711ba417.png)

`baseType` looks like this 
![image](https://user-images.githubusercontent.com/57588903/116607116-e9723600-a931-11eb-895d-cc523c8c6c4b.png)
It's `System.Object` from a the .Net Core Assembly `System.Private.CoreLib.dll`

So Mono Cecil is looking for this dll and can't find it, how could I provide a path to the .Net Core SDK ? And why the GAC isn't automatically searched ?

Where can I find the source code of `Unity.SerializationLogic.dll`, `Unity.CecilTools.dll`, and `Unity.Cecil.dll` ?

**Comment by Perfare** [comment]
Use the .net framework version of Il2CppDumper instead of the .net core version. 
In .net core, most of the basic types are placed in System.Private.CoreLib. But AssetStudio is currently running under the .net framework, so the System.Private.CoreLib library cannot be loaded.

**Comment by guidra-rev** [comment]
That was it thank you !
