### ISSUE TITLE
OBJ export uses local number formatting, breaking the format.

### ISSUE THREAD

**Issue by questforboobs** [Perfare/UnityStudio#73]
If you live in a country where period is the decimal separator, everything is fine; but if you live in a country where the comma is the decimal separator and try to export an OBJ file, your output will use commas for decimal separators, like so:

g ModelName
v 0,04636741 0,7889791 -0,2108947
v 0,06329647 0,7630776 -0,02185177
v 0,1555166 0,7838091 -0,05192223
v 0,1360121 0,662389 0,04327016

This will of course not work, though a workaround is to load the OBJ file in Notepad and change all the commas to periods. The StringBuilder used in ExportMesh needs to be set to use English in order to get the desired behavior in international systems.

**Comment by Perfare** [comment]
Thank you, but StringBuilder.AppendFormat not only used in ExportMesh method, 
it seems to have to be fixed in all method.
