### ISSUE TITLE
Issue with exporting Textures

### ISSUE THREAD

**Issue by AsifGhaffar2220** [Perfare/UnityStudio#730]
Hello. I have been experiencing issues exporting textures. I have only face this issue with one game(Darts Of Fury), with other worked fine. When I load folder then only show every thing except texture of models. When export models then no textures comes.
If there's anything I can do to fix this issue or if I need to wait for a newer version of this program to be released then please let me know.
Any help and information is appreciated.

https://play.google.com/store/apps/details?id=uk.co.yakuto.DartsOfFury

**Comment by Perfare** [comment]
Use the latest version, if you load the file without encountering errors, it means that everything is displayed in the list.

**Comment by AsifGhaffar2220** [comment]
Hi, Thanks for your time, my issue resolved
