### ISSUE TITLE
Asset that looks non encrypted fails to load (Unity 2018.4.23)

### ISSUE THREAD

**Issue by teslabyte** [Perfare/UnityStudio#732]
Example of a file is provided. Looking at it through Hex editor i can see plenty of text so on first look it doesn't seem to be encrypted, yet the program doesn't load the file and doesn't display any error message.
[53f80c77a918f9d911aa5e363c7352af790ee29a.zip](https://github.com/Perfare/AssetStudio/files/6401070/53f80c77a918f9d911aa5e363c7352af790ee29a.zip)

**Comment by Perfare** [comment]
Although the head looks normal, but I think it is still encrypted.
