### ISSUE TITLE
How to export MonoBehaviour with dummy DLL?

### ISSUE THREAD

**Issue by StKelen** [Perfare/UnityStudio#735]
In  the README.md, you mentioned AssetStudio can export MonoBehaviour with assembly DLL. But when I first select MonoBehaviour, it doesn't ask me the directory where the assembly is located. How to specify the dummy folder?

您好，
  您在README中提到，当第一次选择一个MonoBehaviour资源时，AssetStudio会提示指定dll文件夹在哪里。对于il2cpp而言，需要指定dummyDLL文件夹。但是我选择了一个MonoBehaviour之后，并没有要求我指定对应的文件夹。请问应该如何指定文件夹，导出正确的文件？

**Comment by Perfare** [comment]
如果你的MonoBehaviour是在bundle文件里，并且bundle带有MonoBehaviour的结构信息的话，就不会向你要求dll文件。
点击MonoBehaviour查看时可以看右下角，如果MonoBehaviour读取出错会有提示，没有的话MonoBehaviour的结构就是你看到的样子。

**Comment by StKelen** [comment]
好哒，感谢~~
