### ISSUE TITLE
I have trouble exporting anything at all

### ISSUE THREAD

**Issue by lilrichan** [Perfare/UnityStudio#736]
I tried to export sprites and 2D textures from a game I really liked but it always displays this message:

![Screenshot 3_5_2021 10_08_58 PM](https://user-images.githubusercontent.com/80376345/116886925-42a4d700-ac5c-11eb-9738-50a95a3e21f0.png)

I tried using administrator mode, using other releases and redownloading the build but to no avail. I can't even seem to find a directory identical to the one in the message. Am I doing something wrong? @Perfare  Sorry to @ you but I just really need help...

**Comment by Perfare** [comment]
Please upload the source file to me.
