### ISSUE TITLE
Magnum Quest no works :(

### ISSUE THREAD

**Issue by Contra6** [Perfare/UnityStudio#738]
Hi, can you check? Thanks.
[b_scene_a17.zip](https://github.com/Perfare/AssetStudio/files/6428629/b_scene_a17.zip) <<<Download
I looked inside files
![File](https://user-images.githubusercontent.com/55824288/117174453-65f39180-add6-11eb-8e55-f02ea9c194a0.png)

**Comment by SacriGrape** [comment]
This is because some asset bundles have two headers. Deleting everything up to the start of the second UnityFS should let the file be readable

**Comment by Contra6** [comment]
@SacriPudding cool! It works big thanks you. On note for asset.![](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)
![Works](https://user-images.githubusercontent.com/55824288/118354621-865ce200-b574-11eb-9a17-59e2637d17f3.png)
