### ISSUE TITLE
0.15.37 - unusable

### ISSUE THREAD

**Issue by Eleiyas** [Perfare/UnityStudio#739]
Title.

- Using up to 17GB of RAM and even after closing the program, it stays in Task Manager as a process using the same amount of RAM.
- It will now load CAB files, but says "loaded X files - 0 exportable assets"
- Previous versions would show "meshes" as an asset-type in the list of exportable assets, this version makes them all "unexportable" and they don't even appear in the asset list.

- Exporting FBX will either export them completely empty with only collider data, or it will throw up this error:
![image](https://user-images.githubusercontent.com/16349939/117387572-07670a00-aee1-11eb-902b-d9956e02885f.png)

**Comment by Eleiyas** [comment]
Note, the models I'm trying to extract use a generic "body01"/"body02" file-name, which Asset Studio doesn't seem to pick up as exportable (for some reason). When I'm then exporting as merged FBX, it's trying to merge the working meshes with ones that are not actually loaded and then using any other "body01" (of which there are many) to fill in the gap, which is throwing up the error:

example: body01 is also used for various monsters in this game, so it's trying to put a human-NPC head on that of a dragon or something, which obviously won't work.

edit: the monster-related body01 are loading, but the human ones aren't.

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by Perfare** [comment]
According to your screenshot, I think your problem is the same as #707 . The game modified the AnimationClip and other data structures, which caused AssetStudio to fail to read normally, and the wrong file will not be displayed in the list.
