### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by stormygaret15** [Perfare/UnityStudio#740]
![Screenshot 7_5_2021 8_29_01 PM](https://user-images.githubusercontent.com/83821164/117449812-fbc42380-af72-11eb-87cf-01062031360b.png)

exporting just the model work fine but some weird error shows up when i select some animation clips and a model to export.

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by stormygaret15** [comment]
[pkm unite beta.zip](https://github.com/Perfare/AssetStudio/files/6564663/pkm.unite.beta.zip)

**Comment by stormygaret15** [comment]
This is the file that I have trouble with. If you need the full game file please tell me thanks for your help

**Comment by Perfare** [comment]
The developer modified the structure of AnimationClip and needed to modify the source code to read it, but even if AssetStudio was read, the modified DenseClip could not be processed.
![QQ截图20210706093439](https://user-images.githubusercontent.com/12952226/124529579-7ad3bc00-de3d-11eb-921e-6a19137bbb22.png)
