### ISSUE TITLE
Support for Vertex Colours and multiple UV's?

### ISSUE THREAD

**Issue by Sneakyerz** [Perfare/UnityStudio#741]
Afaik, Asset Studio currently does not have these features. These features can come in handy in the future, also, there might be some games that uses Vertex Colours such as anime phone games Idol Masters I believe. And there's tons of Unity games that uses multiple UV's for models such as Metal Revolution.

**Comment by PatrickKing** [comment]
By coincidence I actually just [did some work](https://github.com/Perfare/AssetStudio/pull/764) to enable exporting more of the model's UV maps. 

Also, I'm positive that support to export vertex colours is included, I've seen it working for some meshes. Your 3D program might not show vertex colours by default.
