### ISSUE TITLE
build expired

### ISSUE THREAD

**Issue by buffbears** [Perfare/UnityStudio#744]
The latest build expired. Appveyor deletes artifacts after 1 month.

**Comment by kjhyhy6765** [comment]
is there another way or site to download it?, or when is it coming back

**Comment by SinsofSloth** [comment]
[Release.zip](https://github.com/Perfare/AssetStudio/files/6518656/Release.zip)
This is built from the latest source.

**Comment by buffbears** [comment]
This build has an FBX error when exporting models.

**Comment by r3sus** [comment]
https://github.com/r3sus/AssetStudioBackup/releases

**Comment by buffbears** [comment]
These builds work much better thanks!

**Comment by Perfare** [comment]
I have re-uploaded the latest version in Releases.
