### ISSUE TITLE
Mesh Vertices Incorrectly Exported

### ISSUE THREAD

**Issue by SenorPez** [Perfare/UnityStudio#746]
![image](https://user-images.githubusercontent.com/16673259/119210992-3a7ad300-ba75-11eb-8b68-40858319786b.png)

Mesh vertex connections are incorrect in the export to OBJ and FBX.

Referenced Model: [Model.zip](https://github.com/Perfare/AssetStudio/files/6525625/Model.zip)

**Comment by Perfare** [comment]
Are you using the latest version? I did not encounter your problem.
![捕获](https://user-images.githubusercontent.com/12952226/119557749-2adfef00-bdd3-11eb-98e9-37e32769616c.PNG)

**Comment by SenorPez** [comment]
I'll be able to check tonight!

**Comment by SenorPez** [comment]
Can confirm it works in v0.15.47. Thanks for whatever fixed it!
