### ISSUE TITLE
Stuck on reading assets

### ISSUE THREAD

**Issue by Dazegambler** [Perfare/UnityStudio#748]
i've been trying to use assetstudio on a game i've been using for sometime but now its seens it gets stuck on reading assets never actually progressing.
the dev did Update to the latest long term support release of unity so that might have something to do with it
Edit1:it does reads the assets until a certain point where it doesnt progress anymore

**Comment by Perfare** [comment]
Try to use the latest version, if you still have problems, please feedback to me.
