### ISSUE TITLE
全部导出问题！

### ISSUE THREAD

**Issue by yianti** [Perfare/UnityStudio#75]
Perfare 你好！
UnityStudio是一个非常赞的工具。非常喜欢。
有个问题请教一下，为什么在3D拆分导出的时候模型格式用的是FBX格式，而全部导出的时候用的obj格式，最大的问题是obj导出之后是不带UV的。而fbx是带UV的。
是否可以支持全部导出的时候OBJ带正确的UV，或者全部导出的时候也使用FBX格式？
非常感谢！

**Comment by Perfare** [comment]
Export上部分用来导出模型，下部分用来导出素材
obj的uv问题已经修复了，[这里](https://ci.appveyor.com/project/Perfare/unitystudio/branch/master/artifacts)下载最新编译版本

**Comment by yianti** [comment]
非常感谢回复~
上部分是专门用来导出模型的。下半部分是导出包含模型在内的所有文件，贴图文本声音等。这个明白的。
之前的疑问是，同一个模型用模型方式导出的时候FBX格式可以包含UV和材质信息。而用全部导出里边的模型是导出OBJ格式，导出时候UV问题（已经修复，赞！），而且也没有材质信息。所以才有建议是不是全部导出的时候也采用FBX的方式导出模型相关。或者OBJ也支持材质信息。
纯属交流哈~希望Perfare 不要介意。非常感谢修复UV。
