### ISSUE TITLE
I did not understand the solution, please, video

### ISSUE THREAD

**Issue by RabehR** [Perfare/UnityStudio#752]
I did not understand the solution, please, video
![Capture](https://user-images.githubusercontent.com/84939607/119897871-ebb5c780-bfa5-11eb-9c28-fbb4e896a00b.PNG)

**Comment by Perfare** [comment]
AnimationClip cannot be extracted separately, it can only be exported with the model.
https://github.com/Perfare/AssetStudio#export-model
