### ISSUE TITLE
AssetStudio v0.15.47 - Failing to load files now

### ISSUE THREAD

**Issue by Eleiyas** [Perfare/UnityStudio#753]
![image](https://user-images.githubusercontent.com/16349939/120046751-c4451600-c00a-11eb-84e4-7d83fbde555f.png)

**Comment by Perfare** [comment]
Please upload source file.

**Comment by Eleiyas** [comment]
> Please upload source file.

you mean the CAB file I am trying to open, correct?

**Comment by Perfare** [comment]
@Eleiyas Of course the file you opened.

**Comment by Eleiyas** [comment]
[CAB-0000a3bec1d5ae972cfccca9d36502d2.zip](https://github.com/Perfare/AssetStudio/files/6563544/CAB-0000a3bec1d5ae972cfccca9d36502d2.zip)
[CAB-0000f9be29d14f836a1a4bc3bcb8cb3b.zip](https://github.com/Perfare/AssetStudio/files/6563545/CAB-0000f9be29d14f836a1a4bc3bcb8cb3b.zip)

**Comment by Perfare** [comment]
Encrypted file.

**Comment by Perfare** [comment]
According to the file name, the file should be extracted from the bundle file, it may be the encrypted bundle file that caused the wrong decompression.

**Comment by Eleiyas** [comment]
> According to the file name, the file should be extracted from the bundle file, it may be the encrypted bundle file that caused the wrong decompression.

it's strange you say that, because my last opened issue from version 15.37 was using the same files - where assetstudio would load these cabs, but struggle exporting some files.

now, it's just straight up refusing to open them full-stop.

**Comment by Perfare** [comment]
Any version of AssetStudio cannot load the file you provide. In the past version, there will be no prompt for this kind of file, but "No file loaded" is displayed in the lower right corner. In the recent update, I changed it to a specific error message pop-up. After you close the error window, the program behaves the same as before. 
Even if some files are loaded by luck, I think most of them should not work properly, just like your issue #739

**Comment by Eleiyas** [comment]
> Any version of AssetStudio cannot load the file you provide. In the past version, there will be no prompt for this kind of file, but "No file loaded" is displayed in the lower right corner. In the recent update, I changed it to a specific error message pop-up. After you close the error window, the program behaves the same as before.
> Even if some files are loaded by luck, I think most of them should not work properly, just like your issue #739

Ahh ok, that makes sense. 

I'll have to try manually editing the source to see what's what then.
Thanks for replying to my issues :)
