### ISSUE TITLE
Getting loads of different errors when loading just one file

### ISSUE THREAD

**Issue by flleeppyy** [Perfare/UnityStudio#756]
I have no idea why I'm getting so many errors. AssetStudio has never behaved like this before

![image](https://user-images.githubusercontent.com/18307183/120909281-75116d80-c628-11eb-9309-6727b98546ac.png)
![image](https://user-images.githubusercontent.com/18307183/120909283-78a4f480-c628-11eb-96f7-6b3af034499a.png)
![image](https://user-images.githubusercontent.com/18307183/120909308-b1dd6480-c628-11eb-9db6-019c04d86222.png)

It goes on for ages.

**Comment by cebtenzzre** [comment]
I get errors like this on v0.15.43 but not on v0.15.37. Must be some kind of regression.

**Comment by Perfare** [comment]
This error is usually because the structure of Unity has been modified, or the file itself is encrypted.
You can upload the file to me and I will check it.

**Comment by cebtenzzre** [comment]
@flleeppyy could you try v0.15.37 to see if you and I are encountering the same issue? If the older AssetStudio works for both of us then chances are your file is fine and there's just a problem with the latest code.

**Comment by rand0m0User** [comment]
these errors also happen when attempting to load larger game files, the file(s) ive encountered these problems with are located [here](https://sjc2.dl.dbolical.com/dl/2012/10/28/FactionWars-v107-10-05-12-sdfsdfsd.zip?st=QCnikis5rVlLlSHU9qf0lg==&e=1625889866]) (geez i hope the url embeds properly)
