### ISSUE TITLE
Monobehaviour dump and UABE

### ISSUE THREAD

**Issue by seelebrn** [Perfare/UnityStudio#757]
Hello ! 
Thanks, I'd like to thank you for your work on AssetStudio.
I'm not sure it's been asked before, but I understand AS doesn't have an import function, which makes UABE the only (?) viable solution to import dump into assets for modding. 
If I understand well, AS and UABE don't use the same class structures to dump Monobehaviour as json/txt. So I was wondering if there is a way to make both dumps compatible, so it would be possible to import AS Dump files with UABE. 

I hope it's rather clear, English isn't my native language. 
Thanks in advance.

**Comment by Perfare** [comment]
AssetStudio will not consider supporting UABE format.
You can currently try to use UnityPy to edit MonoBehaviour.
