### ISSUE TITLE
no audio clip is showing up

### ISSUE THREAD

**Issue by Ryukomat44** [Perfare/UnityStudio#758]
im trying to get some of the audio assets of SCP unity 0.7.9 (for non commercial use obviously) but there is nothing but a single espaniol file. idk if this is an issue or its cause im an amateur to this gui but please help
![Annotation 2021-06-07 132827](https://user-images.githubusercontent.com/79204745/120989349-b3c43680-c794-11eb-81c2-d8278a8386e2.png)

**Comment by Perfare** [comment]
#579
