### ISSUE TITLE
hi, there was some problem 

### ISSUE THREAD

**Issue by westyyy** [Perfare/UnityStudio#759]
i am trying to export  Animation clip,and there is a problem,thanks in advance.
![изображение_2021-06-07_191218](https://user-images.githubusercontent.com/75077472/121022588-46c89500-c7c4-11eb-92f0-fabe89507a34.png)
![изображение_2021-06-07_191229](https://user-images.githubusercontent.com/75077472/121022620-4d570c80-c7c4-11eb-8c63-34309e30fb4b.png)

**Comment by Perfare** [comment]
AnimationClip cannot be extracted separately, it can only be exported with the model.
https://github.com/Perfare/AssetStudio#export-model
