### ISSUE TITLE
Request: unpack multiple assetbundles to a single folder.

### ISSUE THREAD

**Issue by questforboobs** [Perfare/UnityStudio#76]
At the moment, if you select `File | Extract bundle...` and select multiple .assetbundle files, or if you select `File | Extract directory...` and point it to a folder with multiple .assetbundle files, each .assetbundle file creates its own "Filename_unpacked" folder with a single CAB-hash file inside it.

This is annoying if you then want to load all the assets at once in order to browse them, as you either need to open each file individually, or first move them all into a single folder manually before opening the folder.

I propose a new feature where multiple .assetbundle files would, by default, put their contents in a single folder called "Unpacked". An option in the Settings window allows the previous behavior to remain, for those users that prefer it.

**Comment by Perfare** [comment]
Use File-Load file to load bundle file, "Extract bundle" just a debug function and users don't need to use it
