### ISSUE TITLE
Does not export animator and animations.

### ISSUE THREAD

**Issue by MrGrizzzzly** [Perfare/UnityStudio#761]
In Might & Magic X - Legacy why the is not exported animator and animation clips, can be fixed?
https://drive.google.com/file/d/187wRY4QCM2_eXR3f3alTMmxpc0Qnc_zk/view?usp=sharing
![no export](https://user-images.githubusercontent.com/85544489/121141402-1c7ae400-c865-11eb-8c5a-373ffef180e1.jpg)

**Comment by MrGrizzzzly** [comment]
> In Might & Magic X - Legacy why the is not exported animator and animation clips, can be fixed?
> ![no export](https://user-images.githubusercontent.com/85544489/121141402-1c7ae400-c865-11eb-8c5a-373ffef180e1.jpg)

**Comment by MrGrizzzzly** [comment]
> In Might & Magic X - Legacy why the is not exported animator and animation clips, can be fixed?
> ![no export](https://user-images.githubusercontent.com/85544489/121141402-1c7ae400-c865-11eb-8c5a-373ffef180e1.jpg)
[https://drive.google.com/file/d/187wRY4QCM2_eXR3f3alTMmxpc0Qnc_zk/view?usp=sharing](url)

**Comment by Perfare** [comment]
It is now fixed.
