### ISSUE TITLE
Failure to load Texture2D assets from Pokemon UNITE (Switch) (2019.4.4f1)

### ISSUE THREAD

**Issue by SciresM** [Perfare/UnityStudio#769]
Files are loaded successfully by DevX Unity Editor, supposedly.

I got Texture2Ds to load by adding an extra u32 read to the texture2d deserialization section (before image data size), but I don't think that's actually correct.

As it is, AssetStudio reads size=1 and reads out of bounds data as images.

![image](https://user-images.githubusercontent.com/8676005/123484191-d0e26d00-d5bc-11eb-9feb-d359ef38464d.png)

Archive format is 2019.4.4f1.

**Comment by SciresM** [comment]
I think there's also something parsing wrong with meshes, too.

**Comment by Perfare** [comment]
According to your description, the structure of Texture2D has been modified.
If the file is a bundle file, click the ‘asset classes’ tab in the program to view the structure and code comparison of Texture2D, and then modify the code.

**Comment by SciresM** [comment]
I'm not sure that I understand. There is nothing in the asset classes pane.
![image](https://user-images.githubusercontent.com/8676005/123503730-9652f180-d609-11eb-932d-5426d2eb0130.png)

**Comment by ElChicoEevee** [comment]
Perfare if you want to look about heres a bundle https://cdn.discordapp.com/attachments/684782424068063322/858093002261790760/72692037_dlc_0_r248013_0.bundle

**Comment by Perfare** [comment]
Obviously the developer deleted the structural information to prevent others from viewing it. The best thing to do in this case is to try to obtain structural information from the executable file.
Coincidentally, the file for this issue #740 is also from Pokemon UNITE, it’s just that it’s the Android version. Structure information is still retained in this bundle file. I modified the code to verify that the structure of AnimationClip is the same as the file provided by @ElChicoEevee. So you can also consider obtaining bundle files from other platforms that still retain structural information.

**Comment by ElChicoEevee** [comment]
@Perfare with Mesh is the same right? Cause android bundles models could be opened NSwitch ones not

**Comment by Perfare** [comment]
@ElChicoEevee In the #740 file, only the AnimationClip structure is different from the original one. Because I don’t have the latest file, my guess is that the version of NSwitch is newer. In the new version, the developer modified the structure of Texture2D and Mesh. Perhaps you can find the structure information from the latest Android version.

**Comment by ElChicoEevee** [comment]
Interesting... ok thanks for the info!!

**Comment by ElChicoEevee** [comment]
this is what i got with asset classes
[28 Texture2D Base.txt](https://github.com/Perfare/AssetStudio/files/6766851/28.Texture2D.Base.txt)
[43 Mesh Base.txt](https://github.com/Perfare/AssetStudio/files/6766849/43.Mesh.Base.txt)

**Comment by Perfare** [comment]
@ElChicoEevee The structure of these two files has not been modified.

**Comment by ElChicoEevee** [comment]
so editing The Mesh/Texture2D.cs from classes folder (ill wait someone do it cause i dont have knowledge about it) could make these bundles viewable/previewable?

**Comment by Perfare** [comment]
As long as the code of Mesh/Texture2D.cs is modified to the modified structure, it can be read normally.
According to the information provided by @SciresM, Texture2D only needs to add ReadInt32 before the image data size. 
The structure of the mesh is too complicated, and it is difficult to guess the modifications made by the developer before there is no structural information.
