### ISSUE TITLE
Loading Folder Building Assets List Error

### ISSUE THREAD

**Issue by Dragonkris30** [Perfare/UnityStudio#775]
Why does the AssetStudio gives me this error when I have been loading the folders multiple times before but after a few mobile games updates folders now it's this error?

System.OutOfMemoryException: Array dimensions exceeded supported range.
at System.Collections.Generic.List`1.set_Capacity(Int32 value)
at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)

**Comment by Bognet-projects** [comment]
I run into the problem a few times as well, but not just with mobile games. The error is probably due to the game developers added more assets into a single bundle than the GUI can load/handle. :(

**Comment by Perfare** [comment]
You need to upload the source file to me.

**Comment by Dragonkris30** [comment]
> 
> 
> You need to upload the source file to me.

Well it's the entire game folder I want to load into the AssetStudio.
