### ISSUE TITLE
Error in GenshinImpact

### ISSUE THREAD

**Issue by 1vanK** [Perfare/UnityStudio#776]
Way to reproduce:
1) Install https://genshin.mihoyo.com (this is free game)
2) File->Load file->GenshinImpact_Data

![1](https://user-images.githubusercontent.com/13021826/124386166-c8d3ad00-dce1-11eb-86fb-c13ea47ec499.png)

**Comment by Sneakyerz** [comment]
The files are decrypted. You cannot extract content from this game, but others has managed to crack the decryption BUT won't share the extracted content such as 3D models because for some unknown reason?

**Comment by Perfare** [comment]
As far as I know, GenshinImpact encrypted the file and modified the structure, you cannot open it directly with AssetStudio.

**Comment by FlasheryTV** [comment]
How can i open it? i tryed with too many programs and nothing, some help pls?

**Comment by ds5678** [comment]
https://github.com/khang06/AssetStudio
