### ISSUE TITLE
UnityFS 5.x.x 0.0.0 not export 

### ISSUE THREAD

**Issue by zhouwenc** [Perfare/UnityStudio#778]
UnityFS 5.x.x 0.0.0 not export 
[DA62FB01A88DFCA0B3CC0B1F1F4189A5135F776E.zip](https://github.com/Perfare/AssetStudio/files/6764004/DA62FB01A88DFCA0B3CC0B1F1F4189A5135F776E.zip)

**Comment by Perfare** [comment]
This type of file can currently be loaded in the latest build version, you can download it from here 
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
Note that you need to enter the correct version of Unity to load.
