### ISSUE TITLE
Error:Array dimension is out of range

### ISSUE THREAD

**Issue by danuonuo** [Perfare/UnityStudio#779]
Hey,I tried to export the unity file with this software, but it failed, as shown in the figure.
![image](https://user-images.githubusercontent.com/40296672/124541489-1b34db00-de54-11eb-8461-3115bc432799.png)

**Comment by Perfare** [comment]
You need to upload game files to me.

**Comment by danuonuo** [comment]
> You need to upload game files to me.

This is the game files.
https://drive.google.com/file/d/15CQavRkkk-PABIu82FX_kuJw7Y8ePLrz/view?usp=sharing

**Comment by Perfare** [comment]
The developer customized the Unity structure.
