### ISSUE TITLE
I can't open file unity 2019.4.15f1 

### ISSUE THREAD

**Issue by libeyondea** [Perfare/UnityStudio#780]
I can't open .assetbundle file
![image](https://user-images.githubusercontent.com/57558120/124597802-18ef7280-de8e-11eb-8471-d332e4ad6672.png)

**Comment by libeyondea** [comment]
File here: [scene_design_pvptest.assetbundle](https://github.com/de4th-zone/test/raw/main/scene_design_pvptest.assetbundle)

**Comment by de4th-zone** [comment]
> I can't open .assetbundle file
> ![image](https://user-images.githubusercontent.com/57558120/124597802-18ef7280-de8e-11eb-8471-d332e4ad6672.png)

**Comment by GGure** [comment]
i was going post the same thing as well game have new update they use unity 2019 version and i got the same problem.

**Comment by Perfare** [comment]
File is encrypted.
