### ISSUE TITLE
Streaming Assets Support

### ISSUE THREAD

**Issue by Pootisp** [Perfare/UnityStudio#785]
So I Encountered A Game called "Counter Side" i tried to extract the files but it seem the files is compiled with better streaming asset
https://assetstore.unity.com/packages/tools/input-management/better-streaming-assets-103788
would you please add a support for files compiled with better streaming assets addon

**Comment by Perfare** [comment]
It does not affect the format of the asset. The most likely cause of your problem is that the game encrypts the file.
