### ISSUE TITLE
Problem when trying to open files from Ben 10: Power Trip

### ISSUE THREAD

**Issue by BenFourArms39023** [Perfare/UnityStudio#786]
Hi! I have a problem with Ben 10 Power Trip's files when I try to import or extract them in AssetStudio. They don't extract. :(, Maybe you could support every file for Ben 10 Power Trip? I'll get the zip link. https://drive.google.com/file/d/1DwmHrRBIZDaXpAWUK2SFm84cVQtYxYxg/view?usp=sharing

You might wanna support files like .assets or .resS or level or maybe all the Unity game files that begin with "shared" or "global" or "level".

**Comment by BenFourArms39023** [comment]
Don't ignore the issue! Just reply please! :facepalm:

**Comment by ds5678** [comment]
This might not be exactly what you're looking for, but I was able to extract your whole game with [AssetRipper](https://github.com/ds5678/AssetRipper).

**Comment by Perfare** [comment]
I tested the file you provided without any problems.
In addition, it should be pointed out that you cannot load a .resS file separately, it can only be read through other asset files.

**Comment by BenFourArms39023** [comment]
It's the problem by Unity Studio V0.9.0, sorry.
