### ISSUE TITLE
Import Error after v0.15.37

### ISSUE THREAD

**Issue by zneb** [Perfare/UnityStudio#787]
I tried v0.15.37, v0.15.47, and 0.16.0.

While importing assets from _Bloons TD 6_, on the latter 2 versions I get the following error multiple times:
![Capture](https://user-images.githubusercontent.com/18729406/125206232-27ee7000-e254-11eb-9a30-4262b53424e4.PNG)
On version v0.15.37 there is no issue.

**Comment by Perfare** [comment]
You need to upload the source file to me.
