### ISSUE TITLE
Issue loading UnityFS files of Unity 2019.4.17f

### ISSUE THREAD

**Issue by llomsiang** [Perfare/UnityStudio#788]
While trying to import the file it seems to have trouble [finding the correct type](https://github.com/Perfare/AssetStudio/blob/7ab2cda120ec08d34a7a3c52cd31ab97272a2815/AssetStudio/SerializedFile.cs#L141). 

![image](https://user-images.githubusercontent.com/64302108/125304504-f0ec8d00-e32d-11eb-9f8b-c252ccab37b7.png)

My best guess would be that the offset changed slightly? I am not sure about the header offsets, so having a hard time debugging this.

**The file:** [city_building_1010.zip](https://github.com/Perfare/AssetStudio/files/6802109/city_building_1010.zip)
**AssetStudio version:**  v0.16.0

**Comment by Perfare** [comment]
The real error is that lz4 failed to decompress, this file should have been encrypted.
