### ISSUE TITLE
KartRider Rush + obb files can't b loaded

### ISSUE THREAD

**Issue by Tosyk** [Perfare/UnityStudio#792]
Basic game from APK is loads fine:
![image](https://user-images.githubusercontent.com/24209966/126324688-9c27d375-3e16-4f02-a7d2-de02a7af0ec0.png)

but the files from these 2 OBBs don't want to load even if I directly ask AS to do so:
![image](https://user-images.githubusercontent.com/24209966/126325096-71d12c54-1b39-4eee-b568-949223403d63.png)

Here's one of these folders:
[00.zip](https://github.com/Perfare/AssetStudio/files/6848291/00.zip)

**Comment by Perfare** [comment]
All files start with "FBAU", should be encrypted.
