### ISSUE TITLE
YU-GI-OH! RUSH DUEL: SAIKYOU BATTLE ROYALE!! DEMO animationclip issue

### ISSUE THREAD

**Issue by Andree12** [Perfare/UnityStudio#794]
I tried to export animator with animationclips with the but they don't load up properly as expected.
[cha000a.zip](https://github.com/Perfare/AssetStudio/files/6867354/cha000a.zip)

**Comment by JebediahKermanKSP** [comment]
its because the animationclips aren't even exported at all.

**Comment by Perfare** [comment]
Sorry, humanoid animation is not supported.
