### ISSUE TITLE
Exception with packaged System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by justastranger** [Perfare/UnityStudio#795]
So I've been building an [application](https://github.com/justastranger/CarcassSpark/) to facilitate modding the game Cultist Simulator, and one of the features is to be able to load the game's assets and display icons for the cards. This worked fine until the latest updates of the game forced me to update to 0.16.0 of Asset Studio. And it worked fine for me afterwards but I got a report of a 
[FileLoadException](https://github.com/Perfare/AssetStudio/files/6871603/FileLoadException.txt). In an attempt to reproduce the exception, I renamed the dll, launched the program (successfully reproducing the exception) and then named it back. After that I started getting the exception with the original filename, despite nothing fundamentally changing with the assembly. Yet somehow it still worked just fine if I launched it through Visual Studio (debug and release configurations). And even if I copy the mentioned assembly from the build folder to the program's install location and overwrite the copy stored there, it still throws the same exception. I'm at a loss as to how this is even possible.

**Comment by justastranger** [comment]
Apparently Visual Studio auto generates binding redirects that fix this (when I actually ship the config file they're in 🙄). Not sure if I should close this or not.

**Comment by Perfare** [comment]
I’m sorry I didn’t understand this problem. I won’t encounter any problems when building AssetStudio alone, so I can’t help you.

**Comment by justastranger** [comment]
IIRC, the issue was basically that there are some old versions of .net
binaries that are used by one of the libraries AssetStudio uses and if you
don't set up a binding redirect (which, as far as I understand, tells the
program to look for a different version of the binary than the one it's
compiled against), you get the exception I linked to. I believe that the
image library is the culprit. If there are any updates to that, or if
you're able to update its dependencies yourself, that would fix it. It's
unnecessary work though as long as the binding redirects are configured
properly.

On Sunday, September 19, 2021, Perfare ***@***.***> wrote:
> Closed #795.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci3.googleusercontent.com/proxy/WT3H6K21glCVf3flDsZVfklFSgbv7XddYVGlAfuVLG6SWz58zsvnfBVAb5VvDUIVp8BHICdeSJYc2xNGShgKH34Vj-7fJKvkuRbgY5VgtXRdQZFuflec7JpBjMpSZs1Sa4uw8is0whpyeAjcUhSEmNhnqYkT-odAl3fb5EQMJGqrpcYVBzRSloXHDk22p8-7I-pbYmV-T2IKBQFxy5c8NwaMnZf4PDeJTV3L-Pqy5AjFoqa6JJ_6y4Ifazeus4CObkAuO3Q=s0-d-e1-ft#https://github.com/notifications/beacon/ABUC3VZLXAL6MQPFQMDXR53UC2UN5A5CNFSM5A44KROKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGPAAAAAAJ5OEDFK.gif>
