### ISSUE TITLE
AnimationClips are exported by name only

### ISSUE THREAD

**Issue by JebediahKermanKSP** [Perfare/UnityStudio#796]
When I export an animator with the selected animationclips it only exports the rigged model and the animation's name. Noesis shows it as a 31-frame animation clip but with no animation at all.

edit: The developer of AssetStudio has been inactive since July 6 2021. Oh well.

**Comment by Perfare** [comment]
Because you didn’t upload the file to me, I don’t know the specific situation, but it should be noted that AssetStudio does not support humanoid AnimationClip.

**Comment by MrGrizzzzly** [comment]
There is an early topic on this problem /issues/782

**Comment by Perfare** [comment]
@MrGrizzzzly No one upload any files even in this issues.

**Comment by MrGrizzzzly** [comment]
> @MrGrizzzzly No one upload any files even in this issues.

Ok here is the link https://drive.google.com/file/d/187wRY4QCM2_eXR3f3alTMmxpc0Qnc_zk/view?usp=sharing 
The red bar indicates the only animation that is not exported
![anm](https://user-images.githubusercontent.com/85544489/127637767-3b991286-8bf2-46cf-be04-9dc72840e32c.jpg)

**Comment by Perfare** [comment]
@MrGrizzzzly AssetStudio cannot find the bones used in this animation, so it cannot be exported.
All in all, AssetStudio can only guarantee that most animations can be processed normally, and some animations are sorry I can’t do anything.
