### ISSUE TITLE
Shader reading/loading is not fix in v0.16.0

### ISSUE THREAD

**Issue by djinnet** [Perfare/UnityStudio#797]
Steps that I did: 
download the new update of assetstudio as zip file.
Open zip file.
Open assetstudioGUI exe
Drag & drop the folder
The prompts shows up.

It works fine in the v0.15.37 version without any prompts, but in v0.15.47 and later it shows up!

This makes me suspect that the stream didn't close properly? Can someone verified that it's also happening to them?

![image](https://user-images.githubusercontent.com/9974608/126865745-37420e57-d7cd-4e4d-b07b-8c81d3ff197a.png)

(sorry for the danish description. It basically said "cannot read at the end of the stream")

**Comment by Perfare** [comment]
You need to upload the source file to me.

**Comment by djinnet** [comment]
I cannot upload the source file since it's from a group of friends that works as an indie company. They are aware of me and they are comfortable & trust me for using the software to read their assets, since I am using the software to their wiki as purpose.

If that means this issue cannot progress without me breaking the trust of my friends for giving the source, then I am fine with not progress at all. However I would like to know if there are an alternative method to use instead? 

If there are no alternative, then it's fine. After all, the important part of this issue is that **ya** are aware of this bug and I hope that someone else who have the same bug as mine can give their source to ya. 

I am sorry that I cannot be to any help at all than let ya know about the bug.

**Comment by Perfare** [comment]
I cannot fix any errors without the source file.
