### ISSUE TITLE
doesn't recognize mesh files of MARVEL Realm of Champions

### ISSUE THREAD

**Issue by Tosyk** [Perfare/UnityStudio#798]
It seems like AS can't read files meshes (android game) most of the time.
Even those who can be "read" (the one expanded on the screenshot) are not possible to extract
![image](https://user-images.githubusercontent.com/24209966/126868300-ee8ffb22-4161-433a-8a78-cb9fd6922c5e.png)

Here's example of files:
[character.zip](https://github.com/Perfare/AssetStudio/files/6872383/character.zip)

**Comment by Perfare** [comment]
If you think that these TextAssets are Mesh, then the developer has stored the Mesh in the TextAsset in some form, and you need to decrypt it yourself.
