### ISSUE TITLE
Trojaner!!!!!

### ISSUE THREAD

**Issue by TorresVisuals** [Perfare/UnityStudio#799]
Dont Download usefull but Trojaner in it

**Comment by D33pfield** [comment]
Welcome to your first day on Github! 

Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.

**Comment by TorresVisuals** [comment]
> Welcome to your first day on Github! 
> 
> 
> 
> Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.

I scanned with virustotal and it found an trojaner

**Comment by D33pfield** [comment]
> > Welcome to your first day on Github!
> > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> 
> I scanned with virustotal and it found an trojaner

Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag.

**Comment by TorresVisuals** [comment]
> > > Welcome to your first day on Github!
> 
> > > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> 
> > 
> 
> > I scanned with virustotal and it found an trojaner
> 
> 
> 
> Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag. 

I first scanned the zip file housewall or so flagged an trojaner then i scanned the exe file there was 2 flags first a 
vicious and then another time trojan from housewall

**Comment by TorresVisuals** [comment]
> > > Welcome to your first day on Github!
> 
> > > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> 
> > 
> 
> > I scanned with virustotal and it found an trojaner
> 
> 
> 
> Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag. 

Weird i had an older version now i scanned the newest nothing

**Comment by D33pfield** [comment]
> > > > Welcome to your first day on Github!
> > 
> > 
> > > > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> > 
> > 
> > > 
> > 
> > 
> > > I scanned with virustotal and it found an trojaner
> > 
> > 
> > Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag.
> 
> I first scanned the zip file housewall or so flagged an trojaner then i scanned the exe file there was 2 flags first a
> vicious and then another time trojan from housewall

Okay. I assume this was done on the [0.16.0](https://github.com/Perfare/AssetStudio/commit/c85873b7297c0e350e0d52e17ae5b7fa40a81846) release. 

I've gone ahead and done the same with the results here if you'd like to check them out. [AssetStudio.v0.16.0.zip Virus Total Scan](https://www.virustotal.com/gui/file/badc1aa356fe0623ce4053d1a81c22f852c72cb882ca30f1876a37d930d2fbc8)

I've also given  the exe from the 0.16.0 release a run though and have the results here [AssetStudioGUI.exe Virus Total Scan](https://www.virustotal.com/gui/file/330705a49fdb1ee3e46cb81c727d02eafdb4e261399b23284574b3d3d5cb5f99)

Taking a look at the first upload time of these two files on virustotal I noticed they were both done over 24 hours ago. If you could include the links to your scans it would help clear up for everyone what's happening. Worst case what this means is that the files I uploaded were not the same files you had uploaded. I advise making sure malicious software on your machine isn't making changes to downloaded files or uploaded files. You can do this by downloading something that has a SHA256 checksum: posted with it.

**Comment by D33pfield** [comment]
> > > > Welcome to your first day on Github!
> > 
> > 
> > > > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> > 
> > 
> > > 
> > 
> > 
> > > I scanned with virustotal and it found an trojaner
> > 
> > 
> > Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag.
> 
> Weird i had an older version now i scanned the newest nothing

What version?

**Comment by TorresVisuals** [comment]
> > > > > Welcome to your first day on Github!
> 
> > > 
> 
> > > 
> 
> > > > > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I scanned with virustotal and it found an trojaner
> 
> > > 
> 
> > > 
> 
> > > Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag.
> 
> > 
> 
> > I first scanned the zip file housewall or so flagged an trojaner then i scanned the exe file there was 2 flags first a
> 
> > vicious and then another time trojan from housewall
> 
> 
> 
> Okay. I assume this was done on the [0.16.0](https://github.com/Perfare/AssetStudio/commit/c85873b7297c0e350e0d52e17ae5b7fa40a81846) release. 
> 
> 
> 
> I've gone ahead and done the same with the results here if you'd like to check them out. [AssetStudio.v0.16.0.zip Virus Total Scan](https://www.virustotal.com/gui/file/badc1aa356fe0623ce4053d1a81c22f852c72cb882ca30f1876a37d930d2fbc8)
> 
> 
> 
> I've also given  the exe from the 0.16.0 release a run though and have the results here [AssetStudioGUI.exe Virus Total Scan](https://www.virustotal.com/gui/file/330705a49fdb1ee3e46cb81c727d02eafdb4e261399b23284574b3d3d5cb5f99)
> 
> 
> 
> Taking a look at the first upload time of these two files on virustotal I noticed they were both done over 24 hours ago. If you could include the links to your scans it would help clear up for everyone what's happening. Worst case what this means is that the files I uploaded were not the same files you had uploaded. I advise making sure malicious software on your machine isn't making changes to downloaded files or uploaded files. You can do this by downloading something that has a SHA256 checksum: posted with it. 

First i had an older version of assets studio and i shutted down my pc and i try to remove the virus so i cant give you the link i think i will desinfect my pc and then download the newest version

**Comment by D33pfield** [comment]
> First i had an older version of assets studio and i shutted down my pc and i try to remove the virus so i cant give you the link i think i will desinfect my pc and then download the newest version

Please share what version this was so we can take a look and the developers can feel at ease they are not putting anyone at risk

**Comment by TorresVisuals** [comment]
> > > > > > Welcome to your first day on Github!
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > Might want to make specific reference to this "Trojaner" you are alleging the software has. I'm not sure if you noticed but all the source is uh... right here in the repo.
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > I scanned with virustotal and it found an trojaner
> > 
> > > > 
> > 
> > > > 
> > 
> > > > Ah! Okay. Well lets figure this out together then. What file or files was it that you uploaded to virustotal to be scanned? Do you have a link to the report? The specific vendors virustotal uses will most of the time go into detail with what it was that caused the flag.
> > 
> > > 
> > 
> > > I first scanned the zip file housewall or so flagged an trojaner then i scanned the exe file there was 2 flags first a
> > 
> > > vicious and then another time trojan from housewall
> > 
> > 
> > 
> > Okay. I assume this was done on the [0.16.0](https://github.com/Perfare/AssetStudio/commit/c85873b7297c0e350e0d52e17ae5b7fa40a81846) release. 
> > 
> > 
> > 
> > I've gone ahead and done the same with the results here if you'd like to check them out. [AssetStudio.v0.16.0.zip Virus Total Scan](https://www.virustotal.com/gui/file/badc1aa356fe0623ce4053d1a81c22f852c72cb882ca30f1876a37d930d2fbc8)
> > 
> > 
> > 
> > I've also given  the exe from the 0.16.0 release a run though and have the results here [AssetStudioGUI.exe Virus Total Scan](https://www.virustotal.com/gui/file/330705a49fdb1ee3e46cb81c727d02eafdb4e261399b23284574b3d3d5cb5f99)
> > 
> > 
> > 
> > Taking a look at the first upload time of these two files on virustotal I noticed they were both done over 24 hours ago. If you could include the links to your scans it would help clear up for everyone what's happening. Worst case what this means is that the files I uploaded were not the same files you had uploaded. I advise making sure malicious software on your machine isn't making changes to downloaded files or uploaded files. You can do this by downloading something that has a SHA256 checksum: posted with it. 
> 
> First i had an older version of assets studio and i shutted down my pc and i try to remove the virus so i cant give you the link i think i will desinfect my pc and then download the newest version

I think 10.0 or 13.0

**Comment by D33pfield** [comment]
>I think 10.0 or 13.0

 Neither of these versions contain pre-built binaries. I've scanned all releases that contained windows binaries and they all are clean. If you'd like links to the reports ask and I can share them also.  Again, I suggest making sure your machine is not or was not priorly infected before wildly accusing developers who volunteer their free time as hosting malicious code.

**Comment by TorresVisuals** [comment]
> >I think 10.0 or 13.0
> 
> 
> 
>  Neither of these versions contain pre-built binaries. I've scanned all releases that contained windows binaries and they all are clean. If you'd like links to the reports ask and I can share them also.  Again, I suggest making sure your machine is not or was not priorly infected before wildly accusing developers who volunteer their free time as hosting malicious code. 

I open my i think infected pc the version i had is 15.32

**Comment by LuthorDevelopment** [comment]
Checked with Windows Defender, Node32, McAfee and Kaspersky, nothing found. Dont waste time with a Virus-Report which probably comes from a porn site

**Comment by TorresVisuals** [comment]
> Checked with Windows Defender, Node32, McAfee and Kaspersky, nothing found. Dont waste time with a Virus-Report which probably comes from a porn site

I scanned with VirusTotal my zip had a virus
