### ISSUE TITLE
Export -> Selected assets always extracts OBJ only

### ISSUE THREAD

**Issue by Tosyk** [Perfare/UnityStudio#801]
Whatever settings I've tried AS always extracts OBJ only, means no anim or skeleton or textures
![image](https://user-images.githubusercontent.com/24209966/127229126-13aa496a-308b-447d-8123-b7228dca4c92.png)

How to make it extract FBX+anim+textures?

here's examples for testing: 
[marvel_strike_force_char_example.zip](https://github.com/Perfare/AssetStudio/files/6888829/marvel_strike_force_char_example.zip)

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#export-model

**Comment by Tosyk** [comment]
thanks, I know this. But why Export Selected Assets doesn't want to export FBX with textures and skeleton? it worked before.
the link you posted doesn't answer this unfortunately :/

**Comment by KirknSpock** [comment]
New to the program, however, Go to the Model option to extract FBX files. The Options menu has an export option that allows you to change some specifications to the FBX searching pass. This is where I'm stuck, as I'm able to extract a majority of the models, and many more if I play around with the settings, however, I'm too new to do anything but experiment. Hopefully, that helps you/someone.

**Comment by Perfare** [comment]
Only Animator will be exported as fbx.
