### ISSUE TITLE
Color Separated from Image

### ISSUE THREAD

**Issue by Ragingsura** [Perfare/UnityStudio#805]
i keep getting this weird white pixilated images without any color while getting a separate image with colors on it 
![10XX_Shentaixiaoyu_pI_2](https://user-images.githubusercontent.com/52991546/127898567-ce61e422-ee84-45af-b0f5-78aca9293b5e.png)
![10XX_Shentaixiaoyu_pC_2](https://user-images.githubusercontent.com/52991546/127898772-2e77fd28-d6d4-4eeb-9d6f-b0640dda80e3.png)
How can i fix this

**Comment by Perfare** [comment]
This problem has nothing to do with AssetStudio. AssetStudio only exports the original form of the resource. As for how to deal with the game, you need to think about it yourself.
