### ISSUE TITLE
"Unable to load Object" on image data (sprite/texture), only audio data loads

### ISSUE THREAD

**Issue by whiteangel123** [Perfare/UnityStudio#807]
I loaded a folder full of files, so it's hard to tell which files specifically is getting the errors, but after testing random singular files, I found that the files containing audio and "Mono Behaviour" files will load. Everything else gives me an Unable to load error. When I look at the file types detected in the error messages, what makes errors are "Game Object" files, and images.

The folder of data is here: [LINK](https://www.4shared.com/s/fW-NEu4Bwea)

Unity type is 5.x.x

**Comment by whiteangel123** [comment]
@Perfare Here's a sample screenshot of the issue
[https://64.media.tumblr.com/9dda2916ac65a9800d47fa129a35aa7c/a8a1f4febe1d7ae4-31/s500x750/71bdaddc885ef5fb2489a41a9dc8398688b5d3ef.png](url) 
What do you think is the problem here?

**Comment by Perfare** [comment]
According to your screenshot, the game should modify the structure of some data in Unity.

**Comment by whiteangel123** [comment]
@Perfare Does that mean the file cannt be unpacked? All non-audio files that I tried to load into AssetStudio (from this particular game) cannot be unpacked.
