### ISSUE TITLE
Monobehaviour cannot be read or read error

### ISSUE THREAD

**Issue by mskgroup** [Perfare/UnityStudio#809]
![屏幕截图 2021-08-08 114843](https://user-images.githubusercontent.com/51709279/128620068-79151c6c-2c2d-46cc-aab8-d60ada251c04.png)

Many monobehaviours cannot read the content, and some will report errors, and very few can be read normally

**Comment by mskgroup** [comment]
games：https://drive.google.com/file/d/1_tEyT6FAk8KR6kYLIP5gm-Wj-JcSOfeA/view?usp=sharing

**Comment by Perfare** [comment]
I did not encounter any problems during the test, please make sure you have loaded the normal and complete Managed folder.
