### ISSUE TITLE
UnityStudio can't read/extract xml files? 

### ISSUE THREAD

**Issue by jclitwin** [Perfare/UnityStudio#81]
Yo,

Perfare why UnityStudio can't detect xml files?

Example file:
https://th1-qjmu.static.kunlun.com/CDN_Resourse/Android/1100/GameSite/local/GameRes.unity3d

Can you help me?

**Comment by Perfare** [comment]
I don't know what you want to do, I tested this file extract is fine

**Comment by jclitwin** [comment]
Try open GameRes.unity3d file in Unity Studio. If you open this file with Unity Assets Bundle Extractor I can saw theses files and extract raw.

https://image.prntscr.com/image/O7qnMn7oT_K1mmQq7JA9RQ.png

But unfortunately Unity Studio can't saw theses files for me extract.

**Comment by Perfare** [comment]
File - Load file - select bundle file
