### ISSUE TITLE
Not an issue, but how do you compile a folder?

### ISSUE THREAD

**Issue by josiauh** [Perfare/UnityStudio#810]
I'm making a mod for among us, but I can't seem to compile the folder where I extracted the files. Is there a way to do that?

**Comment by josiauh** [comment]
Somebody please answer this. This has been up for a month and I can't compile it still.

**Comment by Perfare** [comment]
You may need UABE or https://github.com/K0lb3/UnityPy

**Comment by josiauh** [comment]
> You may need UABE or https://github.com/K0lb3/UnityPy

I'm confused with UnityPy and UABE might not support it anymore.
