### ISSUE TITLE
Array dimension exceeded supported range & Non-negative number required

### ISSUE THREAD

**Issue by atsniperthin** [Perfare/UnityStudio#816]
When importing it cause this error

![image](https://user-images.githubusercontent.com/46410060/129243781-c201089e-3317-4cfa-a932-2f33ebdaf7cf.png)
![image](https://user-images.githubusercontent.com/46410060/129243845-0149ec95-c7e8-4d55-b146-ea465d419d87.png)

The game is Arena of Valor
[sample.zip](https://github.com/Perfare/AssetStudio/files/6977468/sample.zip)

**Comment by Perfare** [comment]
File is encrypted.

**Comment by Perdanaeka** [comment]
i just want to clarify to this issue, so this is the dead end of exporting from the game or is there any workaround to solve this?
