### ISSUE TITLE
AssetStudio doesn't properly read Among Us' AudioClips

### ISSUE THREAD

**Issue by A-nonymous027** [Perfare/UnityStudio#818]
The asset selected was readable until some update caused this:
![Screenshot (1)](https://user-images.githubusercontent.com/79244637/129472165-8c5794a1-e77b-4828-b62e-67d538b85abd.png)

The raw data looks like this when read by Audacity:
![image](https://user-images.githubusercontent.com/79244637/129472283-08eb980b-c262-4d66-b619-4c13b2fc1894.png)
That's not how Among Us' sabotage alarm is supposed to sound like.

**Comment by MagnaOpossum** [comment]
High chance is that it's encrypted.
