### ISSUE TITLE
Out of memory errors when opening assets from Unity 2.5.x games

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/UnityStudio#820]
Viewing of Unity asset data files from games using Unity 2.5.x on my end makes the program fail to read them and spit out many memory errors when trying to load AnimationClip objects. Unpacking the game's unity3d file first doesn't help. Versions beyond 0.15 have this problem, I think 0.14 too but I could be wrong. I have only tried WebPlayer games so I'm not sure if this effects other platforms. Hiding debug messages help load assets either way, but it won't load every asset. The games run perfectly so they definitely aren't corrupted in anyway. Any advice aside from temporarily downgrading/using other tools or planning to fix it?. Thanks so much, I haven't updated the tool in a while and felt like exploring these two games.

Looney Tunes: Wild About Wile-E (v2.5.0.f5):
![image](https://user-images.githubusercontent.com/30186527/129648259-2eff97dd-c147-4812-be2e-add3db57d7df.png)
[Unpacked](https://github.com/Perfare/AssetStudio/files/6996532/wile_coyote_and_road_runner.unity3d_unpacked.zip)
Looney Tunes: Robot Rampage (v2.5.1.f4):
![image](https://user-images.githubusercontent.com/30186527/129649438-43d0fed2-e514-4dfc-9600-3fe2bcd9e19a.png)
![image](https://user-images.githubusercontent.com/30186527/129649691-8e91270e-b68d-4fd6-b9ab-a10b70ba7411.png)

**Comment by Perfare** [comment]
I am sorry that AssetStudio does not fully support Unity 2.5, and I am not considering it at the moment. You can try https://github.com/mafaca/UtinyRipper
