### ISSUE TITLE
no animationclip on export

### ISSUE THREAD

**Issue by KrevetkaOo** [Perfare/UnityStudio#823]
after export there are no animation clips because they are not exported
![clips](https://user-images.githubusercontent.com/15080586/129867094-1bd352ce-f0cf-40eb-ae9e-7382d1a9d0c9.png)

**Comment by MrGrizzzzly** [comment]
There have already been many topics about non-exported animation clips... but I think the more important problem is that the animation clips that asset studio can export are exported incorrectly: animations are distorted and about 50% of key frames are missing.

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#with-animationclip
The animationclip file cannot be exported separately.
