### ISSUE TITLE
AssetStudioGUI

### ISSUE THREAD

**Issue by nobitakute** [Perfare/UnityStudio#824]
I export assetbundles. with the software AssetStudioGUI it creates the MonoBehaviour folder. now how do i pack it into assetbundles. or import the new file in the created MonoBehaviour folder into the MonoBehaviour folder of the assetbundles. I need the ability to import files or import folders of AssetStudioGUI software.

**Comment by Perfare** [comment]
You can try UABE or https://github.com/K0lb3/UnityPy to edit the file.
