### ISSUE TITLE
Incomplete audio file export for Unity 2.5.x

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/UnityStudio#828]
I'm trying to export a game's music. The game I'm looking at is Wild About Wile E.. Everything else is easy to export but the audio files export incorrectly. The audio files cannot be played in AssetStudio but can be exported and played after removing the 8 byte metadata header to the raw file, however some bytes from the bottom of the file exported are not present in the file, causing the file to end slightly abruptly, which also makes it mismatch the raw file size in the metadata header. Using "the other tool" exports audio files correctly with the proper end bytes after removing the header. Can exporting of these files be fixed in a later update? Thanks so much.

For example:

left: music_ingame.ogg from assetstudio right:  "the other tool"

![image](https://user-images.githubusercontent.com/30186527/131276985-8bbf5631-fab9-48d3-b3a2-e2d0a9361236.png)

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by LolHacksRule** [comment]
Sorry about that, here it is.
[wile_coyote_and_road_runner.unity3d.txt](https://github.com/Perfare/AssetStudio/files/7211893/wile_coyote_and_road_runner.unity3d.txt)

**Comment by Perfare** [comment]
#820
