### ISSUE TITLE
Loading a lot of files will cause a "Array dimensions exceeded supported range" error

### ISSUE THREAD

**Issue by HueyCan** [Perfare/UnityStudio#829]
When loading a folder with a lot of files, AssetStudioGUI will send an "Array dimensions exceeded supported range" error when it's building the asset list. 
AssetStudioGUI will refuse to load all the files any further after that. 
I had 3,099 files to load when this error happened. 
Not sure what's the limit on how many files can be loaded but loading less files (this time being 1,138) seems to work fine.

![exceeded_supported_range](https://user-images.githubusercontent.com/31521545/131551192-f113def4-8047-460a-99b6-c08bb4c13894.png)

**Comment by Perfare** [comment]
I need source files to locate the problem.
