### ISSUE TITLE
2 issues: non-standard normal maps and transparent surfaces

### ISSUE THREAD

**Issue by jkerman2000** [Perfare/UnityStudio#838]
Issue 1: Many Unity games utilize unique red-tinted normal maps. Would it be possible to add a converter that would automatically change them to the traditional purple?

Issue 2:
When importing an FBX model into blender, only the diffuse and normal textures are loaded, no specular/reflectivity maps. Also, the alpha channel is set to the diffuse texture, resulting in all surfaces being translucent.

**Comment by Perfare** [comment]
1. I will consider adding, but I still recommend users to convert by themselves.
2. The program can only guess the attribute of the texture by the file name, so under normal circumstances, the program will not try to identify it, only export all, you need to manually set it yourself.
