### ISSUE TITLE
Asset studio crashing when selecting texture2D  

### ISSUE THREAD

**Issue by HeroFluxx** [Perfare/UnityStudio#840]
When I'm selecting any 2d texture from the asset list asset studio would immediately crash

**Comment by Perfare** [comment]
You need to upload the source file to me.

**Comment by HeroFluxx** [comment]
Sure thing I will

**Comment by HeroFluxx** [comment]
Here's the file
https://anonfiles.com/j7UfJ5I4u0/CUHZV_N51_8_SUTLMJUXVCUPJ_LUJ_EUJMCF_KT_KT_SCQ_pak

**Comment by Perfare** [comment]
The texture2D structure has been modified.

**Comment by HeroFluxx** [comment]
That's very interesting
