### ISSUE TITLE
Unity 5 files from "Sheltered" are not loading correctly. Preview is throwing error.

### ISSUE THREAD

**Issue by bartlomiejduda** [Perfare/UnityStudio#842]
I'm using AssetStudio 0.16.0 and textures/sprites and audio files from "Sheltered" game (epic version) are not loading correctly in preview mode.
https://i.imgur.com/SHlvlN9.png

Here is the sample
https://drive.google.com/file/d/1WYXfMDrA3h1-WGdnunybo5jdeEeMs52x/view?usp=sharing

**Comment by Perfare** [comment]
The error message has clearly told you that the necessary files are missing.
