### ISSUE TITLE
how to export the complete map of a game? 🤔

### ISSUE THREAD

**Issue by BabyWhite69** [Perfare/UnityStudio#843]
Hi, I'm trying to export the game "rust legacy", I'm only interested in the map and some other objects, but actually I only have problems with the map because it is exported only half, it's weird, maybe facepunch use some script to create the rest of the map I do not know the truth, I would like to know if there is a way to export the entire map.

![image](https://user-images.githubusercontent.com/80644505/133726342-0d72fc3e-67c3-4ba5-a6ac-2167291c966e.png)
![image](https://user-images.githubusercontent.com/80644505/133726399-f52abde5-b270-47da-94a8-a12de7e3d13a.png)
![image](https://user-images.githubusercontent.com/80644505/133726437-f2d4bb6c-d0a6-4b0c-ac53-95fa0ec06b37.png)

Since this game can no longer be found original, I try to extract the resources from the pirated versions, I have tried with several versions like these:

1. https://www.mediafire.com/file/z0yxpyj41qxcov9/RustDayZero2021+BAJA+GAMA.rar/file
2. https://mega.nz/file/iQZhVDyb#nnW6ePOCGo9Olbvj-FPsUF0U1lxHdQT47NQ9Ie9St-Y
3. https://www.mediafire.com/file/tb2xb3nnzqwdfgl/Rust_Yoneis_V0.3_Render.rar/file

**Comment by Perfare** [comment]
try [AssetRipper](https://github.com/ds5678/AssetRipper)
