### ISSUE TITLE
Error while reading bundle file xxxx System.OutOfmemoryException

### ISSUE THREAD

**Issue by fisker583** [Perfare/UnityStudio#844]
![image](https://user-images.githubusercontent.com/24962231/133885789-b9438731-f5db-469f-81d3-6ae3ed292f3d.png)

**Comment by Perfare** [comment]
你需要提供源文件给我，另外根据报错99%是加密的bundle

**Comment by fisker583** [comment]
[file.zip](https://github.com/Perfare/AssetStudio/files/7207230/file.zip)
2个文件在源文件夹同一目录，1个能识别，1个不能

**Comment by Perfare** [comment]
E5DA7C22220ED74BD904EA57C823F6A0已加密
