### ISSUE TITLE
2022.1 fails to load assets on 0.15.43-0.16.0 but works on 0.15.37

### ISSUE THREAD

**Issue by MrPurple6411** [Perfare/UnityStudio#845]
Something in https://github.com/Perfare/AssetStudio/compare/v0.15.37...v0.15.43 broke being able to load the files from 2022.1 game Timberborn

everything after 0.15.37 fails to load the games files but it does still work on 0.15.37

some of the errors on newer versions in the pics below
![AssetStudioGUI_HwIniIx4cL](https://user-images.githubusercontent.com/7858500/133910992-df84dce5-886e-4d90-8b09-d28d370ec79e.jpg)

![AssetStudioGUI_6meprXFKvX](https://user-images.githubusercontent.com/7858500/133910994-e87f069d-0e11-45f4-ad47-5a0e5aca2a4d.jpg)
![AssetStudioGUI_peFUQGLqaN](https://user-images.githubusercontent.com/7858500/133910995-41981f91-62e4-49f5-b544-64004a6bb421.jpg)
![AssetStudioGUI_qG81Ba7THY](https://user-images.githubusercontent.com/7858500/133910996-7e926132-053a-4c54-ae0c-b00405f9afca.jpg)

![AssetStudioGUI_17cACgH3R3](https://user-images.githubusercontent.com/7858500/133910997-ce2ece86-2394-4427-8088-282042264aaa.jpg)

**Comment by Perfare** [comment]
I haven’t seen the official release of 2022.1, so it doesn’t support it. 
You only need to close the 'show error message' in the Debug menu, and the behavior of the program will be the same as before.
