### ISSUE TITLE
Preview perfomance issues with textures >1024

### ISSUE THREAD

**Issue by SamSWAT911** [Perfare/UnityStudio#846]
Yo, thanks for this awesome tool. My issue is that there seems to be something wrong with the texture preview in the latest version 16.0. It takes much longer to load textures larger than 1024x1024 compared to the old version 15.47. The delay between my click and texture display with the size of 2048x2048 in the preview window is about ~4 seconds. Maybe it's my pc, but why was it fine before?

https://user-images.githubusercontent.com/85660970/134041065-561b2388-18bb-4b36-8268-41aec8d49878.mp4

**Comment by Perfare** [comment]
The new version replaces the image processing library, it takes more time to process images, but the compatibility is better.
