### ISSUE TITLE
Error while reading bundle file, System.ArgumentOutOfRangeException: Non-negative number required

### ISSUE THREAD

**Issue by EirFun** [Perfare/UnityStudio#848]
I couldn't load the bundle files, I thought it was because i'm trying to load them all at once but I've tried importing one file instead and it didn't work either. Any solution to fix this? Thanks in advance.

![image](https://user-images.githubusercontent.com/66686750/134531702-8c1a59a0-4945-4def-a236-1aa459c44591.png)

Here i included some of the files that I was trying to load

[bundle.zip](https://github.com/Perfare/AssetStudio/files/7218689/bundle.zip)

**Comment by Perfare** [comment]
Encrypted file.

**Comment by lLawliet1208** [comment]
> Encrypted file.

how to decrypt that?
