### ISSUE TITLE
Pokemon Unity Error

### ISSUE THREAD

**Issue by Contra6** [Perfare/UnityStudio#849]
Hello. There a solution? The game is done on Unity. Thanks
![Error](https://user-images.githubusercontent.com/55824288/134754506-28c057eb-36db-4065-80dd-3ea320bcd1dc.png)
<<< [Pokemon.zip](https://github.com/Perfare/AssetStudio/files/7229026/Pokemon.zip) <<< Download

**Comment by 09williamsad** [comment]
Assuming that is Pokemon Unite, it is encrypted.
