### ISSUE TITLE
This error shows up when i trying to open assets. Don't know the reason why

### ISSUE THREAD

**Issue by frostyFabric** [Perfare/UnityStudio#850]
[the picture](https://media.discordapp.net/attachments/892021059266678794/892025604738781214/unknown.png?width=374&height=478), [the file](https://mega.nz/file/9SZTxIQL#nNGYeXNnRXUJzuDnAIv39etrJqxH3T1QBjm-wygYP4w)

**Comment by MagnaOpossum** [comment]
I have this same problem. I don't know why it's happening.

**Comment by Perfare** [comment]
Should have been fixed.
