### ISSUE TITLE
idk what this is

### ISSUE THREAD

**Issue by rzl69** [Perfare/UnityStudio#854]
![image](https://user-images.githubusercontent.com/91812835/135736642-1cfcfec9-d769-4502-994d-e26e7ad6cd12.png)
![image](https://user-images.githubusercontent.com/91812835/135736663-16c0017f-3541-4828-8aee-82a156cc9296.png)

**Comment by rzl69** [comment]
i cant get meshes it gives error

**Comment by Perfare** [comment]
Please upload the source file to me.

**Comment by Perfare** [comment]
Should have been fixed.
