### ISSUE TITLE
UnityStudio V.0.9.0 crashing when loading assets from another folder or local disk space

### ISSUE THREAD

**Issue by BenFourArms39023** [Perfare/UnityStudio#857]
Hi @Perfare
Unity Studio V.0.9.0 crashes when I try to load a Unity game's assets from another local disk space or folder.
Is this a error or bug?
Can it get fixed?
The game I'm trying to rip is Ben 10 (2017 Reboot Game).

**Comment by kiletw** [comment]
Now version is v0.16.0.
Try use latest version.

**Comment by BenFourArms39023** [comment]
I have it running but I had to use .NET Framework 4.0.
Because .NET Framework 4.7.2 failed installation everytime.

**Comment by Perfare** [comment]
UnityStudio V.0.9 is out of date and no longer in maintenance.
