### ISSUE TITLE
When I use AssetStudio export assets, "skeleton. Skel" has a random code

### ISSUE THREAD

**Issue by peas00001** [Perfare/UnityStudio#858]
![1-1](https://user-images.githubusercontent.com/92373583/136951020-8c6856f0-469c-4a80-8f65-0ec8484a67d5.png)
Is this file encrypted? Or is there a language coding error?
https://mega.nz/file/3r5UyIhB#bnny8muNc3lzBcpYQUbuYhRx5Cz4UcJDi_G0H5QPj28
This is the file

**Comment by Perfare** [comment]
TextAsset is not necessarily plain text, it can also be used to store binary data.
