### ISSUE TITLE
can't open .assetbundle file from Unity 5 2019.4.15f1

### ISSUE THREAD

**Issue by didixgates** [Perfare/UnityStudio#859]
i have problem to open .assetbundle file from Unity 5 2019.4.15f
![Screenshot (23)](https://user-images.githubusercontent.com/92426011/137088011-3557e896-2d1d-4625-b6ed-8c7ecae1734c.png)
1.

**Comment by HWOUq1xd7c** [comment]
BundleFile.cs下258行的blockInfoCount在解Unity 5 2019.x的包时会异常巨大（几十万），有些则为0，是不是.ab文件的结构变化了

**Comment by Perfare** [comment]
You need to upload the source file to me, but most likely because the file is encrypted.

**Comment by HWOUq1xd7c** [comment]
> You need to upload the source file to me, but most likely because the file is encrypted.

在对应unity版本下用c#代码尝试解包，会要求提供密码，应该就是加密了
