### ISSUE TITLE
How can I solve 'The unity version has been stripped'?

### ISSUE THREAD

**Issue by sfgewg** [Perfare/UnityStudio#860]
![how](https://user-images.githubusercontent.com/92506174/138026768-9161942a-f7cb-4837-a908-3feddfce9646.png)

I have no idea what's wrong with it

**Comment by ds5678** [comment]
Do you have a file you can upload that causes this?

**Comment by sfgewg** [comment]
> Do you have a file you can upload that causes this?

Tried to upload here but this page dosen't support this file type. I'll try for google drive, so can you please wait a bit?

**Comment by sfgewg** [comment]
> Do you have a file you can upload that causes this?

https://drive.google.com/drive/folders/1MqDXen-EsddEPyzq2B1PEQBg3ajsknK2?usp=sharing

there's much more, but those are all same errors so i just uploaded few

**Comment by ds5678** [comment]
Other than the 2 text files and the mp4 file, your files are 2020.3.18

**Comment by sfgewg** [comment]
> Other than the 2 text files and the mp4 file, your files are 2020.3.18

can you explain a bit more?

**Comment by ds5678** [comment]
`00a7d6fdc456fca8517e4b1a30d56242` and `00a061f7455693af8acbdb09fdc053e8` are text files, not asset bundles.

`00b77dbe5299514c3e817caa57c45f37` is an mp4 video file.

`00bee661bcce064b71118b9af988d690` is not stripped.

The rest are stripped.

**Comment by ds5678** [comment]
I viewed the files in a [hex editor](https://hexed.it/)

**Comment by sfgewg** [comment]
> I viewed the files in a [hex editor](https://hexed.it/)

![11](https://user-images.githubusercontent.com/92506174/138031426-39e0ab2e-ec98-431a-90d5-e57b9e5a68c0.png)

tried 00bee661bcce064b71118b9af988d690 in assetstudio, but it says that this file is also unity version is stripped

**Comment by H0LIXI** [comment]
![image](https://user-images.githubusercontent.com/19890189/140502365-f0fdf22e-f5e5-472a-8863-673537296dab.png)
I ran into this same issue. 
And I try to set unity version at "Options/Specify Unity version".
But I also get error: IndexOutOfRangeException at SerializedFile.cs line 222
![image](https://user-images.githubusercontent.com/19890189/140502962-dcd391a0-f6b2-4d70-9a07-8e1d5dc97b8b.png)

**Comment by Perfare** [comment]
@tangpeilin You'll need to enter the full Unity version, for example '2020.3.21**f1**'.
