### ISSUE TITLE
Importing Textures?

### ISSUE THREAD

**Issue by KitOdin** [Perfare/UnityStudio#861]
so umm, im trying to mod a game, but i cant find any sort of "import" button.
how do you import textures?

**Comment by echomusician** [comment]
as far as i am aware this is a tool to extract and view. not to insert

**Comment by Mr-Foxtrot** [comment]
while it was intended to extract and view, the addition of an import feature would be helpful. There so far isn't any active tools that support modern unity versions like this one. so a import tool to replace textures, meshes, etc. would be extremely helpful and maybe even the first to allow basic texture modding and model swapping.

**Comment by Perfare** [comment]
You can try UnityPy
