### ISSUE TITLE
can't open assetbundle file... 

### ISSUE THREAD

**Issue by ManKMan2546** [Perfare/UnityStudio#862]
![Screenshot (106)](https://user-images.githubusercontent.com/92899184/138194988-97a08f30-cb1b-4cd4-885d-579bd288c8bd.png)

**Comment by ManKMan2546** [comment]
[skin11.zip](https://github.com/Perfare/AssetStudio/files/7385227/skin11.zip)
All file from this [File from arena of valor game]

**Comment by ManKMan2546** [comment]
okay file is encrypt.... how do i solve it

**Comment by asdfghjklu2000** [comment]
Did you specify the unity version in AssetStudio?

**Comment by ManKMan2546** [comment]
> Did you specify the unity version in AssetStudio?

Idk but i think is 2019.2.x version

**Comment by asdfghjklu2000** [comment]
![arenaOfValor](https://user-images.githubusercontent.com/45062925/138383877-f391362e-b5e1-432a-89b8-819efac2b0f0.png)
According to network packet captured by Thor, the unity version of AOV should be 2019.4.15f1.
You can try to enter this in AssetStudio by click "Options"→"Specify Unity version"

**Comment by ManKMan2546** [comment]
> ![arenaOfValor](https://user-images.githubusercontent.com/45062925/138383877-f391362e-b5e1-432a-89b8-819efac2b0f0.png) According to network packet captured by Thor, the unity version of AOV should be 2019.4.15f1. You can try to enter this in AssetStudio by click "Options"→"Specify Unity version"

![Screenshot (107)](https://user-images.githubusercontent.com/92899184/138403177-443a6d2f-0518-470c-8fe6-48999a3d2b67.png)

as before...

**Comment by ManKMan2546** [comment]
and i have new issue. i can't open assetstuidoGUI.exe in normal file(exe file) but i open the assetgui.exe in .rar file it can open//How??
