### ISSUE TITLE
Problem loading assets from data folder

### ISSUE THREAD

**Issue by Ryomi13902** [Perfare/UnityStudio#864]
So I tried to load some assets from the data folder of an app but it didn't work. The asset data seems to be in a file format instead of data format. Is there a way to load them?
![image](https://user-images.githubusercontent.com/65694320/138554056-31186cc2-cd2b-4dc3-8a85-822c32e171cc.png)

**Comment by Perfare** [comment]
This usually means that the file is encrypted or not a Unity file, you can try to upload a file to me and I will check it.

**Comment by Ryomi13902** [comment]
Here's the file. Thank you for your help!
[Shared.zip](https://github.com/Perfare/AssetStudio/files/7573767/Shared.zip)

**Comment by Perfare** [comment]
None of these files contain Unity header.
