### ISSUE TITLE
Can't find the current build artifact.

### ISSUE THREAD

**Issue by Hitoshura12** [Perfare/UnityStudio#865]
Hello,
I wanted to download the executable but I couldn't find it in Appveyor. All I get is this message : The build job does not contain any artifacts.
I have all browser plugins disabled, and the download works for the source code but that's merely the source...not the build.
Any idea why this is happening? 
Thank you.

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio/releases
