### ISSUE TITLE
Error while reading web file **.bundle NullReferenceException

### ISSUE THREAD

**Issue by xiaoas** [Perfare/UnityStudio#867]
I updated from version 0.15.32 cuz the old version was failing to show the assets of a specific game.
Now the new version is giving these errors.
![image](https://user-images.githubusercontent.com/14904657/140347923-0b3fe7c4-1814-4eb1-8093-a4d182dd1a3c.png)
Similar errors show for a couple files on 'load folder'.

**Comment by foxwhite25** [comment]
There is a workaround, you can goto C:\project\assetstudio and clone this repo

**Comment by Perfare** [comment]
Should have been fixed.
