### ISSUE TITLE
If the game is macOS version, AssetStudio try to read "unity default resources" from wrong path

### ISSUE THREAD

**Issue by iokotono** [Perfare/UnityStudio#868]
in macOS, "unity default resources" file are located in `Game.app/Contents/Resources/unity default resources`, and other resources are `Game.app/Contents/Resources/Data/*`.

but AssetStudio try to read "unity default resources from `Game.app/Contents/Resources/Data/` instead of `Game.app/Contents/Resources/`, and it throws unhandled FileNotFoundException.

**Comment by Perfare** [comment]
Very strange error, AssetStudio will try to read unless the file exists, and it is impossible to throw FileNotFoundException anyway. 
Please upload the complete file to me if possible.

**Comment by iokotono** [comment]
it seems to bug of wine-mono, just install Microsoft .NET and works. sorry.
