### ISSUE TITLE
Files from Unity 5.6.3p3 won't be opened

### ISSUE THREAD

**Issue by johnwithlenon** [Perfare/UnityStudio#869]
Hi. Thank you for the awesome program.
Today I have an Android game that I think the program isn't support? I'm using AssetStudio v0.16.0, and the file I'm trying to open is UnityFS version 5.6.3p3

I think it isn't encrypted because I can see the "CAB-" name and the file name. I can also see some bone name like "Tunic_Bone", "L_Clavicle", "UpperArm".

Samples here:
[https://www.mediafire.com/file/7d5midunpcdat0t/pc_male.zip/file](https://www.mediafire.com/file/7d5midunpcdat0t/pc_male.zip/file)

If I open the file "pc_male___0.ab", nothing happens. And if I open the file "group_pc_male___0.ab", an error dialog appears saying:
`System.OverflowException: Array dimensions exceeded supported range.`
So maybe these files are linking together?

EDIT: There is a high chance that it's encrypted,

**Comment by Perfare** [comment]
The version of these bundle files has been modified to 7 causing read failure. You can comment out the following code to successfully load.
https://github.com/Perfare/AssetStudio/blob/d08b78c2cf57c74025d9aeecef22e3e135300edc/AssetStudio/BundleFile.cs#L209-L212
