### ISSUE TITLE
Having trouble with .asset files, but not .assets?

### ISSUE THREAD

**Issue by Vandoitale** [Perfare/UnityStudio#874]
I'm attempting to rip some sprites from the PC version of a mobile game, I successfully could get the UI elements by shoving sharedassets0.assets into the Studio...
![image](https://user-images.githubusercontent.com/86098867/142508957-19181149-5fc3-473a-b891-4e1e500b8ca8.png)
![image](https://user-images.githubusercontent.com/86098867/142508994-33b65cef-f7b2-4114-8614-e9f0b7a57488.png)

But the relevant part I'm interested in, the sprites, are all in the StreamingAssets folder as .asset files.

![image](https://user-images.githubusercontent.com/86098867/142509058-08037bf6-ed86-4047-bd87-9e1b2ab74057.png)

I attempted to load them into Unity directly, but even on the latest version I didn't get a single result other than that they might be corrupted or that they were made using a newer version.
Shoving them into the Studio only results in no files being loaded, there's also not a single .assets file in the StreamingAssets folder.
![image](https://user-images.githubusercontent.com/86098867/142509229-3c96f0f2-5872-4393-9471-36cd468609a7.png)

Any way someone could help with this issue? Is there perhaps something I can do to grab all of those .asset files and get them into an .assets file?

**Comment by ds5678** [comment]
You should be able to load the bundles with AssetStudio, even if you have to move them into the same folder.

However, there is another way. [AssetRipper](https://github.com/ds5678/AssetRipper) lets you recover the game back into a Unity project with all the assets.

**Comment by Perfare** [comment]
This usually means that the file is encrypted or not a Unity file, you can try to upload a file to me and I will check it.

**Comment by Vandoitale** [comment]
Didn't work unfortunately, .asset files weren't recognized as Unity files by AssetRipper.

**Comment by Vandoitale** [comment]
Sure, [here's one of the files.](https://drive.google.com/file/d/1bPol1_AOF0WXxI_bUq4GH4ZfXP7-subj/view?usp=sharing)

**Comment by Perfare** [comment]
The file should be encrypted.
