### ISSUE TITLE
Webfile 读取有问题

### ISSUE THREAD

**Issue by foxwhite25** [Perfare/UnityStudio#875]
![image](https://user-images.githubusercontent.com/39846845/142573160-fdd220f0-243f-418c-87af-ef41dff30c36.png)
使用版本v0.16.0

**Comment by Perfare** [comment]
我推测这原本是bundle文件但是使用了gzip压缩导致AS识别成webfile，你可以源文件给我看一下

**Comment by Perfare** [comment]
应该已被修复，如果还有问题请回复我
