### ISSUE TITLE
Issue with exporting textures.

### ISSUE THREAD

**Issue by verygladen** [Perfare/UnityStudio#877]
Hey! I was ripping a game called "Steven Universe: Unleash the Light", and while i was getting to a majority textures, they appear like this, seemly unsized, copied, and corrupted. I have no idea why this happens and I can't find a fix with this. Some textures even crash the application by just clicking on them in the asset list. Other assets seem to not want to preview/export at all due to an unsupported version, but I have no idea what version UTL uses. Please let me know if I'm doing something wrong or exporting it wrong!
![image](https://user-images.githubusercontent.com/37459940/142711161-63dcd0e8-6837-41ed-ad45-009d2d5c08b1.png)

**Comment by Perfare** [comment]
You need to upload the source file to me.
