### ISSUE TITLE
Can't see scene hierarchy with Pokemon BDSP Pokemon Models

### ISSUE THREAD

**Issue by Lilothestitch16** [Perfare/UnityStudio#878]
I'm having trouble with the Pokemon BDSP Models in AssetStudio. I'm not seeing it in the scene hierarchy.

![unknown2](https://user-images.githubusercontent.com/8963276/142742014-6ef06ccd-1c98-479e-9b04-2e2af11343e8.png)

**Comment by Perfare** [comment]
If the file you select does not contain GameObject, you will not see anything in the scene hierarchy.
