### ISSUE TITLE
Can't extract textures

### ISSUE THREAD

**Issue by Carpethop** [Perfare/UnityStudio#881]
Hi, I'm trying to extract some models and textures from the Android/iOS versions of a mobile game named "M&M’S Adventure", I successfully extracted models, but when it starts exporting textures it wont stop giving me same error and eventually just crash, it seems like bundle files encrypted or just contain unsupported textures format.
![image](https://user-images.githubusercontent.com/11527788/143139485-74dba092-73e9-465e-a02f-3adf8f43ebf0.png)

**Comment by Perfare** [comment]
You need to upload the wrong file to me.
