### ISSUE TITLE
where is AssetStudioFBXNative.dll

### ISSUE THREAD

**Issue by andriuy000** [Perfare/UnityStudio#883]
where is AssetStudioFBXNative.dll

**Comment by johnwithlenon** [comment]
Inside x86/x64 folder?

**Comment by nigelmerle** [comment]
hello i am trying to extract marvel strike force, it is a game on android...but all my models are being exported to .obj and not .fbx...is there something i am doing wrong ? 
Also i noticed that all the animation remain in a .dat file....is there a possibility to extract a .dat file ?
