### ISSUE TITLE
version bug

### ISSUE THREAD

**Issue by dhl1206** [Perfare/UnityStudio#884]
I can export Sprite file normally when using v0.15.47 , however when I upgrade AS to v0.16 , there is a no response problem when I export some Sprite file. Here is the issue file.
[jiangfeng_2.zip](https://github.com/Perfare/AssetStudio/files/7611475/jiangfeng_2.zip)

**Comment by Perfare** [comment]
After testing, the reason is that it took a lot of time to cut the image. I need some time to study how to deal with it. Currently, I recommend you to use the 0.15.47 version.

**Comment by Perfare** [comment]
This bug has been fixed, although the speed is still not as fast as the old version, but I think it is acceptable.
The new version has not been released yet, you can download it from here first
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
