### ISSUE TITLE
unable to load object errors -- -please help !  find attached problematic files

### ISSUE THREAD

**Issue by nigelmerle** [Perfare/UnityStudio#889]
![Screenshot (211)](https://user-images.githubusercontent.com/17375811/144695663-4c0714d8-ea34-455f-8e23-cab8529777e7.png
[Problematic files.zip](https://github.com/Perfare/AssetStudio/files/7653259/Problematic.files.zip)

**Comment by nigelmerle** [comment]
the root of the skeleton was renamed to character name but why  ???

**Comment by nigelmerle** [comment]
when i try to import fbx in unity. I get a biped error

**Comment by nigelmerle** [comment]
![Screenshot (212)](https://user-images.githubusercontent.com/17375811/144696774-ff7fc9b6-7aea-485b-8f5d-774942d09b3e.png)


screenshot of error when i imported the fbx to unity

**Comment by nigelmerle** [comment]
i try modify the biped in 3ds max but it doesnt work, i think there is a problem in asset studio, there must be some kind of precision error

**Comment by Perfare** [comment]
I did not encounter any problems with the files you provided.
If you cannot edit the model, you can change the animation type to Generic.

**Comment by nigelmerle** [comment]
But why is the model twisting in all the directions?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Perfare** [comment]
I didn’t see any distortion, it should only be the first frame of the animation. If the exported model contains animation, it will look like this when imported into Unity.

**Comment by nigelmerle** [comment]
When i exported the model i selected everything in the scene mode and in the second window aa well....which makes all the animations play at once on the model ...is it the right way to export the models....if i do not select the second window, the animations doesn't play on the character..i noticed also only anim plays on the character, the animations who are names differently does not play on the model

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
