### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [Perfare/UnityStudio#89]
My unity3d file says "no children" and has nothing it it even thoug there things in it

**Comment by RagdollZombie** [comment]
I'm getting the same issue, can someone help out?

**Comment by Perfare** [comment]
I think you should make clear what you want to do first, and then you'd better upload a file to me.

**Comment by TheRealPiggyWiggy** [comment]
githum does not support .unity3d

**Comment by Perfare** [comment]
You can choose to compress it into ZIP files or upload it to other places

**Comment by TheRealPiggyWiggy** [comment]
the file size is too big

**Comment by Stellarspace** [comment]
If it's a .unity3d file, you have to export the contents of the .unity3d file first. What is the file size? Upload it to [Mega](https://mega.nz/)

**Comment by Perfare** [comment]
Sorry, if you can't provide the file I can't do anything.
