### ISSUE TITLE
Error when I try to extract or play any AudioClips 2030.3.21f1

### ISSUE THREAD

**Issue by Drivium** [Perfare/UnityStudio#892]
Even clicking on one of the files generates this error:
![image](https://user-images.githubusercontent.com/10969752/145537899-1caa3e6f-66b7-4d8d-9ed2-0aabea00db69.png)

I had been using v0.15 and just updated to latest hoping it would fix the issue, but it persists. Says it cannot find the file sharedassets1.resource. I dumped the entire data.unity3d file and there doesn't seem to be anything by that name in the file. Not sure if that's the issue or not.

**Comment by Perfare** [comment]
You can upload the source file to show me.
It is worth mentioning that although AS reads from the asset it needs sharedassets1.resource, but it may actually be sharedassets1.resS.
