### ISSUE TITLE
Asset Patching

### ISSUE THREAD

**Issue by K0lb3** [Perfare/UnityStudio#893]
Hello,
I would like to ask if you plan to make it possible to patch assets or if you would accept a PR that would make this possible.
I'm asking because I would like to work on that feature, or well, port it from my python port of AssetStudio (UnityPy) to AssetStudio itself.

The background is, that I noticed some days ago that it's possible to wrap AssetStudio in pythonnet and make its core functionalities work on all major platforms that way as well.  Not only is this solution faster than my python port, but it would also directly implement features I haven't come around to implement in UnityPy yet.
The only big downside of it is, that some features of UnityPy will be lost, of which the most important one is asset patching,
which is why I would like to work on a framework that allows this to be done via AssetStudio as well.

**Comment by Perfare** [comment]
Asset patching has always been a feature I want to add. I added it to the plan before, but unfortunately I didn’t have much energy to maintain AssetStudio in the past two years, and this plan has been stranded. If you are willing to help, I would be very happy accept.
Considering that I may not be able to process the PR in time, I have already added you to the collaborators. If you want to work, you can start at any time.

**Comment by K0lb3** [comment]
Thanks for the trust.
And I can understand the problem with the lack of time, I will probably run into the same problem within 1-2 months,
so I more or less want to push through most of my pending workload for free projects in the meantime.

The asset patching I've created in UnityPy seems to work fine for most cases by now,
so I would more or less try to add it to AssetStudio 1:1 as far as it's possible.
I made a quick check of AssetStudio just now and noticed that only one part of AssetStudio has to be slightly changed overall to support the feature, and that is that the metadata of the web- and bundle files have to be kept around to make it possible to rebuild the original internal structure of the file.

Considering the editing of the objects themselves,
I would start with editing them via their typetree at first, as that is a universal solution.
I was thinking about making it possible to directly do so in a text window in a displayed json format,
next to importing the edited version via yaml and json.
In all cases, the imported data has to fit the given node structure, but I guess that this restriction is honestly for the best, as Unity would likely crash anyway if the data doesn't fit its format.
My current python implementation for that part can be found at [here](https://github.com/K0lb3/UnityPy/blob/91def6017f8fd6b3d494f46d1a0e1f0393e75b82/UnityPy/helpers/TypeTreeHelper.py#L388).

Once the import via typetree works I would work on the Texture2D import next, as that one is a bit hard to do by normal people and a bit tricky as well. Usually, it's fine to simply replace the image_data and the format with RGB/A, but at the very least DXT and ETC compressed textured have to be recompressed to that format, as otherwise UnityPy will either crash or display a black texture. I guess that the internal shader handler requires those specific formats, dunno.
For this job I'm currently using [wolfpld/etcpak](https://github.com/wolfpld/etcpak) which according to user feedback seems to do the compression fine. I guess implementation of it like you currently did with your texture2ddecoder should do.



Cough, and after such a text wall, a small question at the side. 
Would it be fine to change some small parts of AssetStudio to make it easier to use as a library instead of as its main functionality? That is ofc, without breaking anything existing.
e.g. the path resolving of the DllLoader is a bit troublesome, as it uses the dir of the current main process, which is e.g. in the case of a wrapper via pythonnet the python dir instead of the dir of AssetStudio.
So, can I make some PRs regarding problems like this as well?

**Comment by Perfare** [comment]
Compressed textures are indeed an important item in the asset patch, and there is no problem if you want to cite other libraries at present. I will also consider looking through the information and codes to try to organize all the compression codes into a library so that the original texture format can be maintained.
I don’t actually have any requirements for AssetStudio, I think you can make any changes you want.
I have added you on Discord, and there are other questions we can talk about over there. I will close this issue.
