### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by Li-ZhuoHang** [Perfare/UnityStudio#895]
Excuse me,  I want to unpack a mobile game called meteor heroes from Netease.The game is 3.8G in size, but I can't find it on android phone. I tried to find it in the path of/Android /data, but the file is only 68MB, so I don't know where the data file of the game is. Could you tell me?

**Comment by MrSoup678** [comment]
That requires either a rooted phone or Android emulator. Once you have either download the game here, download its data.
Once finished you have to peek into the filesystem. I did so in case of SMT:Dx2. Downloaded data should be on (root) /data/.Forgot where exactly.

**Comment by 805557409** [comment]
Thank you for your reply. I have successfully extracted the files, but I met a problem. I tried to extract animations according to your tutorial, but all I got were skeletons without animations, could you help me have a look? please
This is the file I extracted: https://drive.google.com/file/d/1GRrN5hA0QfzruUHCqhG_SvMlGtY_W-ht/view?usp=sharing

**Comment by 805557409** [comment]
Could you help me?I Would be most grateful.
