### ISSUE TITLE
Lz4 decompression error

### ISSUE THREAD

**Issue by PhoenixICE** [Perfare/UnityStudio#897]
[avg_hero_33006.controller.zip](https://github.com/Perfare/AssetStudio/files/7716620/avg_hero_33006.controller.zip)
According to the header this seems to be a UnityFS 5.x.x 2018.4.32f1 file but it throws when trying to decompress
![image](https://user-images.githubusercontent.com/2542611/146127367-5ccbc8a5-72a5-43e0-8d05-846b3aa65a98.png)

**Comment by Perfare** [comment]
The file has two headers, you need to cut off the 0x140 byte obstructing header at the beginning.
![QQ截图20211215150703](https://user-images.githubusercontent.com/12952226/146139862-e107fbd4-c072-4b1c-8bd4-bfbb9970bdd9.png)
