### ISSUE TITLE
Why do garbled characters appear when extracting my TextAsset file? Garbled characters generally appear on files with the suffix ske.

### ISSUE THREAD

**Issue by 1003712420** [Perfare/UnityStudio#906]
Why do garbled characters appear when extracting my TextAsset file? Garbled characters generally appear on files with the suffix ske
![QQ截图20211224183720](https://user-images.githubusercontent.com/71360959/147345613-b74f4eed-5074-4d57-95f4-7b4055f269b5.png)

**Comment by MinekPo1** [comment]
This file most likely has binary data saved in it. This is not a bug with the software.
