### ISSUE TITLE
Textures and Sprites appear garbled.

### ISSUE THREAD

**Issue by TSMULT-DAVE** [Perfare/UnityStudio#907]
Texture2D and Sprite assets appear garbled when extracting from a particular game.
AssetStudio Version: net6.v0.16.21 
Unity version: 2020.3.14f1
Game platform: Nintendo Switch
I believe this is the same or a very similar issue to #890.

![Screenshot_Win10-vm1_2021-12-24_06:40:07](https://user-images.githubusercontent.com/96623143/147356559-cc168aed-48b5-4547-ba78-e572bae3eb7c.png)
![sactx-2-2048x2048-DXT5-Adv-95d59a01](https://user-images.githubusercontent.com/96623143/147356600-4baeefd2-29c0-4b2c-b86e-0f0697e487c3.png)
[sharedassets2.assets.zip](https://github.com/Perfare/AssetStudio/files/7774469/sharedassets2.assets.zip)

**Comment by craftersshaft** [comment]
Same issue happens on switch version of Nickelodeon All-Star Brawl and Ryan's Rescue Squad, not sure where to upload files

**Comment by Perfare** [comment]
I checked and only a few pictures have these problems and I didn't find any errors, that's what those pictures look like.
