### ISSUE TITLE
Error while reading bundle

### ISSUE THREAD

**Issue by Anathar5052** [Perfare/UnityStudio#917]
Hello I have this error on the new files imported by the update of the game but not the old files which are there since the first updates and I manage to read them perfectly, it is a security added by the devs or a file that AssetStudio cannot read ? ( I have the latest update for AssetStudio )
Can you correct the problem I am attaching the file ;
Thank you for your reply .
https://mega.nz/file/yvZUFbYL#exTWLtjt77KIDsbF7dWNeNM5TmRMDCzbYRqdcxm72jg
![Capture](https://user-images.githubusercontent.com/30155108/149229616-9d3aa648-ab6d-4f2c-a73e-7990a10b7947.PNG)

**Comment by Perfare** [comment]
Need to trim the first 150 bytes of the file.

**Comment by Anathar5052** [comment]
> Need to trim the first 150 bytes of the file.

Sorry but I did not understand how to read the file with your message :/

**Comment by ds5678** [comment]
> > Need to trim the first 150 bytes of the file.
> 
> Sorry but I did not understand how to read the file with your message :/

You need to use a hex editor like https://hexed.it/

**Comment by Anathar5052** [comment]
> > > Need to trim the first 150 bytes of the file.
> > 
> > 
> > Sorry but I did not understand how to read the file with your message :/
> 
> You need to use a hex editor like https://hexed.it/

Ok Thanks for help :)
