### ISSUE TITLE
Errors on loading asset.

### ISSUE THREAD

**Issue by Shuraken007** [Perfare/UnityStudio#919]
Hello, I have some problems with reading asset.
![image](https://user-images.githubusercontent.com/23379636/149619864-6eb4046c-2ae5-4081-804f-1d3f7b238200.png)

Unity vetsion should be 2021.1.3fl
Use your last build
[data.unity3d_unpacked.zip](https://github.com/Perfare/AssetStudio/files/7874836/data.unity3d_unpacked.zip)
used level0 asset
any idea what can I do with this?

**Comment by Shuraken007** [comment]
Founded problem.
Shader.cs -> class SerializedProgram

`             if ((version[0] == 2020 && version[1] > 3) ||
               (version[0] == 2020 && version[1] == 3 && version[2] >= 2) || //2020.3.2f1 and up
               (version[0] == 2021 && version[1] > 1) ||
               (version[0] == 2021 && version[1] == 1 && version[2] >= 4) || //2021.1.4f1 and up
            {
                m_CommonParameters = new SerializedProgramParameters(reader);
            }`

version 2021.1.3fl requires this SerializedProgramParameters too

I have different versions of the same shader for different versions of apk / unity
2019.2.10fl   VS  2021.1.3fl

So - 2019 version takes x3 Int32 to serialize x3 empty Program
and 2021 version takes x53 Int32 to serialize x5 empty Program + end of the not empty Program
total 8 + 5 * 9 = 53

![image](https://user-images.githubusercontent.com/23379636/151204966-107ba3d5-81db-447c-abc0-8e48af73bd16.png)

**Comment by Shuraken007** [comment]
supposed solution
add new condition for 2021.1.3.1 ?
just don't know if 2021.1.3.0 was
`               (version[0] == 2021 && version[1] == 1 && version[2] >= 3 && version[3] >= 1))`

**Comment by Shuraken007** [comment]
@Perfare plz check this, probably you need some file examples or anything else

**Comment by Shuraken007** [comment]
Also there was file "unity default resourses"
it has same problems
but it have other version
`2021.1.0b12`

here are files - working on old version 2019 - and with shader error on 2021
[files_report.zip](https://github.com/Perfare/AssetStudio/files/7943890/files_report.zip)

**Comment by Shuraken007** [comment]
Also, can you say, where from you get protocols for assets compression / decompression? I think that this are Unity interiors. Disassembly or there are somewhere description?

**Comment by ds5678** [comment]
As with AssetRipper and all other Unity ripping software, everything we know comes from 4 places:
1. Unity documentation
2. Type tree dumps
3. Ghidra / Ida
4. Manual experimentation (hopefully not too much of this)
