### ISSUE TITLE
Texture seems corrupted

### ISSUE THREAD

**Issue by mercury233** [Perfare/UnityStudio#922]
Example file: [000d72a3.zip](https://github.com/Perfare/AssetStudio/files/7898560/000d72a3.zip)
It should be this picture
![8041](https://user-images.githubusercontent.com/13391795/150168142-aa642e81-8e28-44d7-8012-4ca3f01ad79f.png)
But
![image](https://user-images.githubusercontent.com/13391795/150168438-3ce871ca-4a56-41ef-a4d8-8a27217721df.png)

It is from the game 010039E012F40000 of switch, almost all textures extracted by AssetStudio are corrupted.

Do the game encrypted the textures, or AssetStudio didn't parse them correctly?

**Comment by ds5678** [comment]
~~Encrypted~~ swizzled textures

**Comment by Arymond** [comment]
Export raw run in Raw Texture Cooker check Switch Swizzle and the format it shows in AssetStudio done.

**Comment by mercury233** [comment]
@Arymond Thank you!
![image](https://user-images.githubusercontent.com/13391795/160790577-6e651a13-af00-4885-b456-c8f58ab19fff.png)

**Comment by ghost** [comment]
Personally I've only ever gotten that method to work with one game.  Everything else gives me this:
![193368235-029f9ffb-3d43-4142-9bc3-7f6b844f58ad 1](https://user-images.githubusercontent.com/13072654/202979163-fcb3f22f-fc2f-4a51-8814-a0cb28b54656.png)
(That is the full sized output of a large texture run through this program...  I even get the same result manually specifying all the details like resolution/etc.)
This also doesn't handle some newer formats like ASTC which simply aren't even available to it.  (And ASTC seems to be used in more and more things lately -- especially on the Switch with its less powerful hardware.)  Also I think it has limited support for texture sizes outside of the POW2 ranges.  Unity doesn't seem to particularly care about texture sizes and I've seen some games with crazy texture numbers like say 1237x231 or something.  (Yeah, odd numbers, not multiples of 2 or 16 or anything GPUs would like to see.  Unity really really does not care it seems, so devs don't care on many.)

Given the nature of AssetStudio, it really needs to be able to unswizzle textures on its own eventually.
