### ISSUE TITLE
What is serializationData?

### ISSUE THREAD

**Issue by pet345** [Perfare/UnityStudio#928]
I would like to know where to put the translation
Then when I was unpacking, I found that there is a serializationData in the monobehavior, which contains nothing but numbers.
I didn't see anything like the name
I want to know how to analyze this?
![image](https://user-images.githubusercontent.com/66313068/151344612-e83faa94-afdf-4916-90be-d82014d3ed2b.png)
![image](https://user-images.githubusercontent.com/66313068/151344675-d2a31cb2-6ae3-4faf-a5e6-82ac7f3728cd.png)

**Comment by zwrtron** [comment]
Everything below m_Name property in MonoBehaviour is related to business logic (custom programming) of the Unity application.

**Comment by Shuraken007** [comment]
use 
https://github.com/Perfare/Il2CppDumper
on il2cpp file
(smth like game/lib/arm64-v8a/lil2cpp.so   for android apk)
- it will read this exe and restore some class structures
on preview Monobehaviour - AssetStudioGui usually opens folder and ask to show DummyDll to use that structures

also you can use
https://github.com/djkaty/Il2CppInspector
it will resotre that structures at readable c# files - you may try to find smth there

**Comment by pet345** [comment]
> use https://github.com/Perfare/Il2CppDumper on il2cpp file (smth like game/lib/arm64-v8a/lil2cpp.so for android apk)
> 
> * it will read this exe and restore some class structures
>   on preview Monobehaviour - AssetStudioGui usually opens folder and ask to show DummyDll to use that structures
> 
> also you can use https://github.com/djkaty/Il2CppInspector it will resotre that structures at readable c# files - you may try to find smth there

I can't use Il2CppInspector
In fact, the dll originally used for unpacking was first unpacked with Il2CppDumper
But there is still no way to analyze serializationData
After that I looked at dump.cs and saw where possible
But I don't know what to do next
![)8BMM6~%Y }TTUPNT25F3IO](https://user-images.githubusercontent.com/66313068/151757707-fd3491a3-6bd9-419b-a633-d42e4c3c0736.png)

**Comment by Perfare** [comment]
This is developer-customized data stored in Monobehaviour. As for what this data is for, you may need to decompile it using tools like ida.
