### ISSUE TITLE
weird, cant export texture

### ISSUE THREAD

**Issue by seanqiu1** [Perfare/UnityStudio#93]
weird, cant export texture, who can help me
![problem11](https://user-images.githubusercontent.com/32211931/30769280-8cfca96e-a048-11e7-9d50-797ec54e3629.JPG)

**Comment by Perfare** [comment]
This file contains a .resS file, you should put them in the same directory.

**Comment by seanqiu1** [comment]
thx! may i ask how to put them in the same directory, or is there any link i can take look, much appreciated!

**Comment by Perfare** [comment]
use ctrl+c  and ctrl+v make the .resS file in the same folder as the file you opened.

**Comment by seanqiu1** [comment]
much appreciated!!!! it worked!!!
one more question, is this contains game resource also?, how to extract it? 
![t43t43](https://user-images.githubusercontent.com/32211931/30780460-b918f4c6-a13d-11e7-8812-b4b96b839ca3.jpg)
much appreciated !!!much appreciated!!

**Comment by Perfare** [comment]
If you export files in resources.assets, data will be read in resources.assets.resS and exported

**Comment by seanqiu1** [comment]
much appreciated! 
actually, what i'm try to ask is how come i can't find all assets from game, such as animation files, this is folders form resources.assets, only character model  
![2](https://user-images.githubusercontent.com/32211931/30946183-1048ac88-a435-11e7-9152-8687f0fa5be0.jpg)

**Comment by Stellarspace** [comment]
You’ll never get animations.

**Comment by Perfare** [comment]
Please see README, UnityStudio can't export animation.
