### ISSUE TITLE
[FeatureRequest] .unity scene export

### ISSUE THREAD

**Issue by dnnkeeper** [Perfare/UnityStudio#930]
It would be very handy to be able to export scene as .unity not as .fbx file. 
I need some lod groups and lighting components properly set to make use of the extracted scene but in fbx format all lods are merged together and lighting setup is different.
Will it be difficult to implement? I could try porting YAML exporter from uTinyRipper but maybe this feature is already in development so I'm asking here just in case.

**Comment by ds5678** [comment]
I don't want to step on Perfare's toes, but this is the kind of thing that [AssetRipper](https://github.com/AssetRipper/AssetRipper) specializes in.

**Comment by Perfare** [comment]
Like @ds5678  said, use AssetRipper to output the YAML file you need.
