### ISSUE TITLE
Can't download latest build

### ISSUE THREAD

**Issue by Caldoric** [Perfare/UnityStudio#937]
any time i try to download anything from the AppVeyor site, it just gives me the following message:

"{"message":"Artifacts download limit (1024 MB/day) exceeded."}"

it's rather annoying.

**Comment by Caldoric** [comment]
pretty sure i don't have any sort of "artifact download limit" on my side of things. maybe the website's being screwy?

**Comment by DestroyTargetNonBasicLand** [comment]
Apparently Appveyor seems to have started using stricter quota limits.. I reckon it would be best if the nightly downloads where migrated to the github mirror @Perfare.

Thank you kindly.

**Comment by Perfare** [comment]
Added.
