### ISSUE TITLE
My PC can't open Unity Studio

### ISSUE THREAD

**Issue by CrazyDAC** [Perfare/UnityStudio#94]
Is this work with window XP? I can't open it and it doesn't even say what error is it.
https://imgur.com/aq0JGb0.png
My PC have framework 4 and C++ 2012. I read readme and it say required 2013 and 2015, but my sister PC is wondow 7, have framework 4 and only C++ 2008 but still can open it.

**Comment by Perfare** [comment]
Window XP is too old, I don't have to think about whether UnityStudio can run on XP at all.
