### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by ShiinaRinne** [Perfare/UnityStudio#941]
在读取一个很大的shader文件时出错
源文件：https://drive.google.com/file/d/1pGPhajxTuIooms45aUV1ZHlq8i9HePoo/view?usp=sharing

![157OTOS3%)JQRNJJV}U3OWO](https://user-images.githubusercontent.com/45081750/158109265-611c98bb-0205-4883-bb3d-0fac3c975e1d.png)
想要读的shader的m_KeywordsSize是60936，但当i=47872时，position就已经读取到了末尾，继续循环会报标题中的错误
![I8DHMO@GM_9NH(URVQKP(D2](https://user-images.githubusercontent.com/45081750/158109298-1d41b64a-3367-4907-89e4-b4f6ca2eb7e6.png)

(感觉是SerializedFile里读的大小或者源文件有问题，但尝试修了四五个小时也没能解决)

**Comment by Perfare** [comment]
你给的谷歌链接没法直接下载。一般来说这个地方不太可能报错，需要源文件才能调试看看

**Comment by ShiinaRinne** [comment]
https://drive.youngmoe.com/s/7QHy
换了个链接，需要整个的apk或者exe吗

**Comment by Perfare** [comment]
已修复
