### ISSUE TITLE
Lz4 decompression error

### ISSUE THREAD

**Issue by ksharperd** [Perfare/UnityStudio#943]
[this file](https://github.com/Perfare/AssetStudio/files/8279897/pgr.zip) is UnityFS 5.x.x 2018.4.30f1 file but it throws this error when trying to decompress
![图片](https://user-images.githubusercontent.com/45651732/158719705-e51929dd-c6b6-4b81-8f01-115eb430a9e2.png)

**Comment by Perfare** [comment]
encrypted file.
