### ISSUE TITLE
Export error [An error occured when processing the image]

### ISSUE THREAD

**Issue by ghost** [Perfare/UnityStudio#944]
![IMG_20220318_214216](https://user-images.githubusercontent.com/101903695/159081687-eea4920c-1ef9-4302-84a8-90e1d9ace45e.jpg)

What does this mean? Can i do something to fix it?

**Comment by Perfare** [comment]
You need to update your AssetStudio version.

**Comment by ghost** [comment]
My version is the latest as far as i see v0.16.21 net6 variant.

**Comment by Perfare** [comment]
upload source files to me.

**Comment by ghost** [comment]
[fffce3b13e48c6fac0dfe5859aacc8ef.zip](https://github.com/Perfare/AssetStudio/files/8307940/fffce3b13e48c6fac0dfe5859aacc8ef.zip)

**Comment by Perfare** [comment]
There is something to improve, I will fix it asap.

**Comment by ghost** [comment]
Ok. Thank you

**Comment by ghost** [comment]
Sorry if it's a dumb question, but how do the fixes/commits work, like how do i use them in AssetStudio if it isn't a new version release

**Comment by Perfare** [comment]
You can download it from here first, 
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
I will add some improvements before releasing the new version
