### ISSUE TITLE
Specifying the Unity version requires double quotes

### ISSUE THREAD

**Issue by QuinnBast** [Perfare/UnityStudio#946]
When setting the unity version in the GUI, you need to put double quotes around the version number otherwise it does not get parsed properly and throws a stack trace.

This throws a stack trace:

![image](https://user-images.githubusercontent.com/22599103/159388841-d1032e59-6ab5-406c-bd06-6f590a2b1f7f.png)
![image](https://user-images.githubusercontent.com/22599103/159388909-2066a3a7-86b5-45ec-832a-b79bc51d2e0b.png)

This does not:

![image](https://user-images.githubusercontent.com/22599103/159388814-c5c3f966-3d23-4ecb-9c27-c24a5959689a.png)

**Comment by Perfare** [comment]
The error is because you didn't fill in the full Unity version, e.g. 5.6.2f1.
Adding double quotes just happens to bypass the check.
