### ISSUE TITLE
little witch academia crash when trying to export models

### ISSUE THREAD

**Issue by teknikalarkitekt** [Perfare/UnityStudio#947]
I have uploaded the files to a file sharing thing I just found on google. It crashes before exporting anything when I click "export all split"

here is the link https://ufile.io/f/mdx2t

I found an old issue that was closed because the OP didn't give the owner the files but I have provided some files so hopefully this will get solved now

**Comment by Perfare** [comment]
Did not encounter any problems with the files you provided, please make sure you are using the latest version.

**Comment by teknikalarkitekt** [comment]
There's 3 different versions of the latest version which one do I click? I
have the one that starts with the number 4 and has a bunch of numbers

**Comment by Perfare** [comment]
just the running framework is different
https://github.com/Perfare/AssetStudio#requirements

**Comment by teknikalarkitekt** [comment]
if it works for you, can you upload the extracted models for me or teach me how you got it to work? For me it just freezes for a few seconds when I click export all objects (split) and then crashes without an error message or anything. Could it be something interfering with it? it works fine with files from other games.

**Comment by Perfare** [comment]
There is nothing wrong with your operation. If you are using the latest version, then I don't know the reason. I provide you with the extraction model of two files. If you want others, please rely on yourself.
[model.zip](https://github.com/Perfare/AssetStudio/files/8327369/model.zip)

**Comment by teknikalarkitekt** [comment]
I figured out the problem. for some reason I can't put a file folder into the same folder as these files because they share the same name and my computer for some reason is treating them as the same kind of file. I fixed it by renaming the files
