### ISSUE TITLE
Export raw as a proyect

### ISSUE THREAD

**Issue by cualquiercosa327** [Perfare/UnityStudio#951]
Excuse me, can you delete this?
Thanks

**Comment by ds5678** [comment]
@cualquiercosa327 and I discussed this privately in a very pleasant conversation

**Comment by cualquiercosa327** [comment]
Excuse me, I don't want critize Asset Ripper. 
in fact I put an issue two weeks ago but after seing your post I have  look it and it is not there nor I have any notification on my email.
I believe it has been some mistake for my part: tomorrow morning I will put it with the computer. 

Anyway I believe they could share code as things as preview work better on this and other work better on the other. 
Again excuse me
