### ISSUE TITLE
Asset Crashing when decompressing.

### ISSUE THREAD

**Issue by NickGurMatic69** [Perfare/UnityStudio#97]
UnityStudio stops responding with similar assets to this one. https://mega.nz/#!M8IQyZoJ!mWJjdWPJazN22QpLy2Ok2Tnb30SwI5D7djKhPuY8HGs

**Comment by Perfare** [comment]
I tested it and couldn't find any issues.

**Comment by Stellarspace** [comment]
Are you using Perfare’s build of Unity Studio?

**Comment by NickGurMatic69** [comment]
I am using the build from commit cc74130ad450b742e33405d31f73d03e3a192e95

**Comment by Perfare** [comment]
You can use debug mode to check for errors.
Besides, I tested the latest build version https://ci.appveyor.com/project/Perfare/unitystudio/branch/master/artifacts
also couldn't find any issues.
