### ISSUE TITLE
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 131072 bytes 

### ISSUE THREAD

**Issue by p0pZeroSn** [Perfare/UnityStudio#971]
Cannot open the sound library of the game "Rise of Kingdoms" made with Unity, due of this error:

```
Error while reading bundle file C:\Users\User Account\sounds.lb 
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 131072 bytes 
   at AssetStudio.BundleFile.ReadBlocks(EndianBinaryReader reader, Stream blocksStream) in 
C:\projects\assetstudio\AssetStudio\BundleFile.cs:line 311
   at AssetStudio.BundleFile..ctor(FileReader reader) in 
C:\projects\assetstudio\AssetStudio\BundleFile.cs:line 71
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath) in 
C:\projects\assetstudio\AssetStudio\AssetsManager.cs:line 174
```

https://drive.google.com/file/d/1MW2LW-dZA0JoTko-k_zdNQeRnmcKN7B3

Solution: Delete all bit entries from the first "UnityFS" specification to the next "UnityFS" specification.

**Comment by PackageInstaller** [comment]
i also encountered this problem

**Comment by p0pZeroSn** [comment]
Solved then.

**Comment by p0pZeroSn** [comment]
Solution: Delete all bit entries from the first "UnityFS" specification to the next "UnityFS" specification.

**Comment by PackageInstaller** [comment]
Hey bro, after I follow what you said, it prompts that the dimension of the array is exceeded. Do you know why?

**Comment by chenhang-cd** [comment]
i still have this problem. use https://github.com/Perfare/AssetStudio/releases/download/v0.16.40/AssetStudio.net472.v0.16.40.zip

**Comment by PackageInstaller** [comment]
那个好像要改东西
