### ISSUE TITLE
Getting this issue trying to open a file

### ISSUE THREAD

**Issue by GBMasMore** [Perfare/UnityStudio#976]
![ERROR](https://user-images.githubusercontent.com/103982511/168100363-55dbafd4-6938-42fd-8a1e-6350d05ade45.png)

**Comment by MisterFeilong** [comment]
Getting a close one as well. I guess it AS got screwed after latest windows update
![image](https://user-images.githubusercontent.com/105666109/168647008-9d2c84aa-b71c-43b6-bcb8-d33dd8c9ff86.png)

**Comment by Backman** [comment]
> ![ERROR](https://user-images.githubusercontent.com/103982511/168100363-55dbafd4-6938-42fd-8a1e-6350d05ade45.png)

Which version of Unity was used to produce the bundle file that you're trying to load?

I'm experiencing the same issue, but only on some Unity versions.
These are the versions that I've been able to test on and get the same error
- 2020.3.34f1
- 2021.3.2f1

**Comment by zhangjiequan** [comment]
And I try to fixed it, it seen to work fine now.
See for details : https://github.com/Perfare/AssetStudio/pull/981
Download My release version here : [zhangjiequan/AssetStudio@zhangjiequan%2Fv0.16.42 (release)](https://github.com/zhangjiequan/AssetStudio/releases/tag/zhangjiequan%2Fv0.16.42)

**Comment by Backman** [comment]
> And I try to fixed it, it seen to work fine now.
> See for details : https://github.com/Perfare/AssetStudio/pull/981
> Download My release version here : [zhangjiequan/AssetStudio@zhangjiequan%2Fv0.16.42 (release)](https://github.com/zhangjiequan/AssetStudio/releases/tag/zhangjiequan%2Fv0.16.42)

I tested your pull request and it works like a charm!

**Comment by zhangjiequan** [comment]
> ![](https://user-images.githubusercontent.com/103982511/168100363-55dbafd4-6938-42fd-8a1e-6350d05ade45.png)


@GBMasMore 
I met the same problem, and I tried to fixed it.
Now it seems to be working properly.
Here's the link for details: https://github.com/Perfare/AssetStudio/pull/981
Click here to download my fixed release: https://github.com/zhangjiequan/AssetStudio/releases/tag/zhangjiequan%2Fv0.16.42

**Comment by MisterFeilong** [comment]
> And I try to fixed it, it seen to work fine now. See for details : #981 Download My release version here : [zhangjiequan/AssetStudio@zhangjiequan%2Fv0.16.42 (release)](https://github.com/zhangjiequan/AssetStudio/releases/tag/zhangjiequan%2Fv0.16.42)

![image](https://user-images.githubusercontent.com/105666109/169410086-031c1991-648b-4492-985b-fb2f7a616748.png)


Tried it but still doens't work, this is the version it fails to me (I suppose that's how you get the unity version since i can't open any files with AS GUI to check LOL)

**Comment by zhangjiequan** [comment]
> > And I try to fixed it, it seen to work fine now. See for details : #981 Download My release version here : [zhangjiequan/AssetStudio@zhangjiequan%2Fv0.16.42 (release)](https://github.com/zhangjiequan/AssetStudio/releases/tag/zhangjiequan%2Fv0.16.42)
> 
> ![image](https://user-images.githubusercontent.com/105666109/169410086-031c1991-648b-4492-985b-fb2f7a616748.png)
> 
> Tried it but still doens't work, this is the version it fails to me (I suppose that's how you get the unity version since i can't open any files with AS GUI to check LOL)

@MisterFeilong 

Emmmm, based on the stack traces, I guess the problem you met is not the same issue as ours.
Anyway, I'll try my best to see what happened.

I want to kown:
After latest windows update? What is your windows system version?
What is your AssetBundle's Unity version? 2021.2.14? Where is that screenshot taken from?
Would you upload the AssetBundle file, so that I can reproduce the issues?

**Comment by MisterFeilong** [comment]
> 

1- Ye, all problems started when I updated through windows update IDK why.
2- I don't know which one it is exactly, that's why I got said screenshot, to see "if that helps", it's a Prehistoric kingdom file
3- https://drive.google.com/drive/folders/1tUOREHZ863JAFDmaacO3_Ii5j0bY5mOA?usp=sharing

**Comment by GBMasMore** [comment]
On my case I still got the error:
![Test1](https://user-images.githubusercontent.com/103982511/169458190-68f9b9b7-f30e-40b7-ba41-62cec8e5d5df.png)

Even after being forced to Update Windows, I still get the same error.
Anyway, I will leave the archive after I open on Hex, as it shows to use the 2017 version.
![Test2](https://user-images.githubusercontent.com/103982511/169458296-4c35ddc4-39c3-4778-80b4-0037178952fa.png)

**Comment by Perfare** [comment]
@GBMasMore you need to upload the source file to me

**Comment by GBMasMore** [comment]
Wait, it is allow to upload a sample of the source file here?

**Comment by Perfare** [comment]
@GBMasMore I won't be able to detect the specific reason if you don't upload the file, but from your screenshot, the file is encrypted by the Chinese version of Unity.

**Comment by GBMasMore** [comment]
So I can upload some of the data of the game. That will make it easier.
But before let me explain what I've found about the data itself:

I've tested in several versions of AssetStudio, each one giving a different error dialogue. I even try to open with others Unity "browsers" data, which in some program actually end in crashing it. Only one was able to "kinda openly" just for end half-freeze and unable to really show all the data of the file yet it end opening.
For what I learn "maybe" the encryption goes aside that was made with the Chinese version of the Unity, is that revolve around the version it was done and the Lz4 compression.

Here are some samples of the game main data. if you need other type or anything for guide you just let me know:

https://mega.nz/folder/cPFWzZST#rPNSa-iKnRdq99zmJOB_JQ

**Comment by GBMasMore** [comment]
So no one can give a solution to the problem? is really impossible to unpack Chine Assets? As I've try with other Chinese game and it actually open the assets, even with older version. But not this game.

**Comment by Perfare** [comment]
I'm sorry that as long as the game uses the Chinese version of Unity's encryption, you can't open it directly, maybe you can find a solution elsewhere, but it's definitely not here.
