### ISSUE TITLE
Some audio and picture files cannot be compiled and exported, which annoys me. Please solve it, thank you.

### ISSUE THREAD

**Issue by fubattery** [Perfare/UnityStudio#977]
File link: https://pan.baidu.com/s/1-52ucoVONSUn0vo7oYEjbw?pwd=u2kh 
Extraction code: u2kh

Below are the details of the problem：
Error while reading bundle file D:NQQ文件
2134519783\FileRecv\base}assetsbasegamedatas
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 91bytes
在Assetstudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projectsjassetstudio\Assetstudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位置
c:yprojectsiassetstudio\Assetstudio\BundleFile.es:行号68
在Assetstudio.AssetsManager.LoadBundleFile(FileReader reader, string
originalPath)位置C\projects\assetstudio\AssetstudioAssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件
2134519783\FileRecv\base\assets\languagedatas
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 91bytes
在Assetstudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projectsjassetstudio\AssetStudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位詈
c\projectsassetstudio\Assetstudio\BundleFile.es:行号68
在Assetstudio.AssetsManager.LoadBundleFile(FileReader reader, string
originalPath)位置C\projects\assetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件12134519783\FileRecv\basejassetsimodelheads
System.IO.IOException:Lz4 decompression error, write -1 bytes but expected 373bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C\projectsiassetstudio\AssetStudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位置
C\projectsjassetstudio\AssetstudiolBundleFile.cs:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader,String
originalPath)位置C:\projects\assetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件
12134519783\FileRecvbase\assetsimodelinformations
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 91bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projectsjassetstudio\AssetStudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位詈
C:\projectsiassetstudioiAssetstudio\BundleFile.es:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, string
originalPath)位置C:\projectsjassetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件12134519783FileRecv\base]assetsimodels
system.IO.IOException: Lz4 decompression error, write -1 bytes but expected 2933bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projectsjassetstudio\AssetStudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位置
c:yprojectsiassetstudio\Assetstudio\BundleFile.cs:行号68
在Assetstudio.AssetsManager.LoadBundleFile(FileReader reader, String
originalPath)位置C\projectsjassetstudio\Assetstudio\AssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件
2134519783\FileRecv\basejassetsimusicblurimages
System.lO.IOException: Lz4 decompression error, write -1 bytes but expected 5533bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projects\assetstudio\Assetstudio\BundleFile.cs:行号248
在AssetStudio.BundleFile..ctor(FileReader reader)位置
Cyprojects\assetstudioiAssetstudio\BundleFile.es:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String
originalPath)位置C:\projects\assetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:NQQ文件
12134519783\FileRecvbasejassetsimusiccharts
System.IO.IOException:Lz4 decompression error, write -1 bytes but expected 2681bytes
在Assetstudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projects\assetstudio\AssetStudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位置
C:yprojectsjassetstudio\Assetstudio\BundleFile.cs:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String
originalPath)位置C:\projectsjassetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:NQQ文件12134519783FileRecv\basejassetsimusicclips
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected15767 bytes
在Assetstudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置 C:\projects\assetstudio\Assetstudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位置
C:yprojectsjassetstudio\Assetstudio\BundleFile.cs:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, string
originalPath)位置C:\projectsjassetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件
12134519783\FileRecvibaselassetsimusicorignimages
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected37303 bytes
在Assetstudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projects\assetstudio\Assetstudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位詈
C1projectsjassetstudioiAssetstudio\BundleFile.es:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader,String
originalPath)位置C\projectsjassetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:NQQ文件12134519783FileRecv\base\assetsjotherdatas
system.IO.IOException: Lz4 decompression error, write -1 bytes but expected 91bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projectsjassetstudio(AssetStudio\BundleFile.cs:行号248
在AssetStudio.BundleFile..ctor(FileReader reader)位詈
c:yprojects\assetstudio\Assetstudio\BundleFile.cs:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String
originalPath)位置C:\projects\assetstudio\AssetStudio\AssetsManager.cs:行号175

Error while reading bundle file D:\QQ文件\2134519783\FileRecvbase\assets\rankssystem.IO.IOException: Lz4 decompression error, write -1 bytes but expected 343bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projectsjassetstudio\AssetStudio\BundleFile.cs:行号248
在Assetstudio.BundleFile..ctor(FileReader reader)位置
C:\projectsiassetstudioiAssetstudio\BundleFile.es:行号68
在Assetstudio.AssetsManager.LoadBundleFile(FileReader reader, string
originalPath)位置C\projectsjassetstudio\AssetStudioAssetsManager.cs:行号175

Error while reading bundle file D:NQQ文件
12134519783\FileRecv\basejassetsiStreamingAssets
System.lIO.IOException: Lz4 decompression error, write -1 bytes but expected 91bytes
在AssetStudio.BundleFile.ReadBlocksInfoAndDirectory(EndianBinaryReaderreader)位置C:\projects\assetstudio\AssetStudio\BundleFile.cs:行号248
在AssetStudio.BundleFile..ctor(FileReader reader)位置
C:yprojectsiassetstudio\Assetstudio\BundleFile.cs:行号68
在AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, string
originalPath)位置C\projects\assetstudio\AssetStudioAssetsManager.cs:行号175

I hope you can help me solve this problem as soon as possible, and I am grateful.

**Comment by Perfare** [comment]
File is encrypted.
