### ISSUE TITLE
Unable to read Seven Deadly Sins Grand Cross assets

### ISSUE THREAD

**Issue by AbdielOM15** [Perfare/UnityStudio#978]
I was trying to load SDS:GC Data but it always show me this window, I've searched for somre posible solutions but nothing works, I want so bad to have this assets, can someone help me?
![imagen_2022-05-13_075552870](https://user-images.githubusercontent.com/90002435/168287772-3487968e-846a-45e7-a2a3-11b64a613b80.png)

**Comment by Dristan2005** [comment]
Before it worked but now I tried to extract the 3D but of the thousands of files that there are none could load and AssetStudio tells me: No was file loaded 😔😔😔

**Comment by Perfare** [comment]
File is encrypted.
