### ISSUE TITLE
Getting "unable to load object" anytime i

### ISSUE THREAD

**Issue by MisterFeilong** [Perfare/UnityStudio#982]
Before windows updated, everything worked fine. But now, everytime I try to open ANY file from ANYTHING, i get this error.
![image](https://user-images.githubusercontent.com/105666109/168646464-98a235ab-9b8a-411e-89f0-83f30470412d.png)

Happens with all files. And sometimes, assetstudioGUI uses around 15GB of RAM memory for nothing, crashing my computer if I wait to see "what happens"

**Comment by MisterFeilong** [comment]
![image](https://user-images.githubusercontent.com/105666109/168657981-b2cdd8f9-17d6-4a08-a9e4-5c1325d34577.png)

**Comment by MisterFeilong** [comment]
![image](https://user-images.githubusercontent.com/105666109/169409924-c2073962-9bf1-4326-b56c-34b808bed1da.png)
Unity version

**Comment by Perfare** [comment]
I found the file you uploaded from another issue, your file version is 2021.3, the release version is not supported, you can download the latest build from here first
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
