### ISSUE TITLE
Problem on loading the asset on class with AnimationCurve field that is next to Array

### ISSUE THREAD

**Issue by asin83** [Perfare/UnityStudio#984]
I have touble with loading the assset data of the class that have AnimationCurve field next to Array.

For example:
```csharp
public class MonoScene : MonoBehaviour {
    [SerializeField] 
    private CinemachineVirtualCamera[] _10timesCamera;
    [SerializeField] 
    private AnimationCurve _fovCurve;
}
```
On generating the TypeTree in TypeDefinitionConverter,

```csharp
                    case "UnityEngine.AnimationCurve":
                        Helper.AddAnimationCurve(nodes, name, indent + 1);
```
- TreeNode _10timesCamera m_Level : 1
- TreeNode Array m_Level : 2
- TreeNode size m_Level : 3
- TreeNode data m_Level : 3
- TreeNode m_FileID m_Level : 4
- TreeNode m_PathID m_Level : 4
- TreeNode AnimationCurve  m_Level : 2
...

On reading the first array field by TypeTreeHelper, 
```csharp
                    if (i < m_Nodes.Count - 1 && m_Nodes[i + 1].m_Type == "Array") //Array
                    {
                        if ((m_Nodes[i + 1].m_MetaFlag & 0x4000) != 0)
                            align = true;
                        var vector = GetNodes(m_Nodes, i);
```
The function ”GetNodes” collects also AnimationCurve.
```csharp
private static List<TypeTreeNode> GetNodes(List<TypeTreeNode> m_Nodes, int index)
        {
            var nodes = new List<TypeTreeNode>();
            nodes.Add(m_Nodes[index]);
            var level = m_Nodes[index].m_Level; //_10timesCamera m_Level: 1
            for (int i = index + 1; i < m_Nodes.Count; i++)
            {
                var member = m_Nodes[i];
                var level2 = member.m_Level; 
                if (level2 <= level)// AnimationCurve (m_Level: 2) also collected  
                {
```

**Comment by Perfare** [comment]
It looks like I added the wrong indent + 1, can you provide me with the relevant files for me to test?

**Comment by Perfare** [comment]
Try the latest version, I think it should be fixed.

**Comment by asin83** [comment]
Unfortunately, because I used V2.6 Genshin impact's assets, it's difficult to share with you. (It's require local path CAB index and Il2Cpp dummy dll, and so on.)
Target file is 00003335/CAB-a6efc3dedc4cb2b9203da8587204cb14 -> MonoGachaScene .

Successfully loaded this file.
Thank you.
