### ISSUE TITLE
Error Read Type

### ISSUE THREAD

**Issue by gameplayoffert** [Perfare/UnityStudio#986]
Hi, i tried AssetStudio on a unity game assets but i get an error when i want to read the Monobehaviour assets. As wrote in the title the error is "Error while read type" so do you know why ? Actually i'm searching a specific class for a specific weapon but i don't find this class into the AssemblyCsharp so is there a possibility for this script to be inside an asset file ?

**Comment by Perfare** [comment]
please check https://github.com/Perfare/AssetStudio#export-monobehaviour
