### ISSUE TITLE
Not correctly getting AudioClip from .resS

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/UnityStudio#99]
Trying to get music from a game, here's a zip where I stripped the assets down to some example files:
[Seabeard.zip](https://github.com/Perfare/UnityStudio/files/1342272/Seabeard.zip)

As you can see, UnityStudio can extract the grass AudioClip, but the one which comes from a file with a .resS counterpart appears to be just a few bytes, definitely not correct! Do you know whats wrong?

(Its also worth noting this file crashes UnityStudio when FMOD tries to parse it. It would be best idea to put parsing in some sort of try catch to prevent the application from closing from erroneous files.)

**Comment by Perfare** [comment]
Thank you for the file, I have fixed this problem.

**Comment by MichaelPriebe** [comment]
Thanks! Very quick! Works perfectly.
