### ISSUE TITLE
error while reading?

### ISSUE THREAD

**Issue by Liujunhua007** [Perfare/UnityStudio#995]
![QQ截图20220608015707](https://user-images.githubusercontent.com/62129047/172450704-78c0318f-fd67-4eb5-b09b-5783316c7bdc.png)
is this file encrypted?

**Comment by Vlad0sZ** [comment]
Same in v0.16.21 and 0.16.40.
Unity version: 2021.3.2f1
Addressables: 1.19.19
![image](https://user-images.githubusercontent.com/29272029/172564912-2776a746-1240-49ec-a030-4e9e79aa1ffa.png)

**Comment by Perfare** [comment]
2021.3.2f1 is not supported in release version.
You can download the latest build from 
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
or
https://github.com/Perfare/AssetStudio/actions

**Comment by Liujunhua007** [comment]
The latest version is used and still cannot be opened.

**Comment by Perfare** [comment]
@Liujunhua007 Your files are encrypted.
